-- 각종증명서인쇄(원본 E020606): 발급 대장. 발행번호 = 발행일의 해 - 그해 차례.
CREATE TABLE hr_certificates (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    issue_year  integer      NOT NULL,
    issue_seq   integer      NOT NULL,
    kind        varchar(20)  NOT NULL,
    employee_id bigint       NOT NULL,
    purpose     varchar(200),
    issue_date  date         NOT NULL,
    CONSTRAINT fk_hr_certificates_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT uk_hr_certificates_issue_no UNIQUE (issue_year, issue_seq),
    CONSTRAINT ck_hr_certificates_kind CHECK (kind IN ('EMPLOYMENT', 'RESIGNATION', 'CAREER'))
);
CREATE INDEX idx_hr_certificates_employee_id ON hr_certificates (employee_id);
