-- 외근 이동수단 마스터(원본 외근입력 E070254 [이동수단] 코드도움, 2026-10-03 실측).
--
-- 원본 이동수단은 글자가 아니라 마스터에서 고른다 — '이동수단검색' [차량번호][차량명][차종],
-- [신규 및 수정] → '이동수단리스트' → [신규(F2)] '이동수단등록'(이동수단코드 · 이동수단명 · 구분 차량/차량아님 ·
-- 차종 경차 · 소형차 · 준중형차 · 중형차 · 대형차 · 승합차 · 화물차), [사용중단/재사용].
-- 외근 기록은 고른 코드 · 이름을 그대로 적어 둔다(field_works.vehicle_no · vehicle_name).
CREATE TABLE field_vehicles (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code       varchar(30)  NOT NULL,
    name       varchar(100) NOT NULL,
    is_vehicle boolean      NOT NULL DEFAULT true,
    car_type   varchar(20),
    active     boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_field_vehicles_code UNIQUE (code)
);
