-- 일용근로 근무입력(원본 E020138): 전표(일자-No.)마다 근무일자 · 일용근로 사원 · 근무기록(일근무 일수) · 금액.
CREATE TABLE daily_work_entries (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp(6) without time zone,
    updated_at      timestamp(6) without time zone,
    slip_date       date          NOT NULL,
    slip_no         integer       NOT NULL,
    line_no         integer       NOT NULL,
    work_date       date          NOT NULL,
    daily_worker_id bigint        NOT NULL,
    quantity        numeric(10,2) NOT NULL,
    amount          numeric(15,0),
    CONSTRAINT fk_daily_work_entries_daily_worker_id FOREIGN KEY (daily_worker_id) REFERENCES daily_workers(id)
);
CREATE INDEX idx_daily_work_entries_daily_worker_id ON daily_work_entries (daily_worker_id);
CREATE INDEX idx_daily_work_entries_slip ON daily_work_entries (slip_date, slip_no);
