-- 일용근로 급여계산/대장(원본 E020139): 대장 · 근무기록확정 · 계산 줄.
CREATE TABLE daily_pay_ledgers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    pay_month   varchar(7)   NOT NULL,
    seq         integer      NOT NULL,
    name        varchar(100) NOT NULL,
    paid_month  varchar(7)   NOT NULL,
    pay_date    date         NOT NULL,
    period_from date         NOT NULL,
    period_to   date         NOT NULL,
    confirmed   boolean      NOT NULL DEFAULT false,
    CONSTRAINT uk_daily_pay_ledgers_month_seq UNIQUE (pay_month, seq)
);
CREATE TABLE daily_work_confirms (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_id       bigint        NOT NULL,
    daily_worker_id bigint        NOT NULL,
    days            numeric(10,2) NOT NULL,
    CONSTRAINT fk_daily_work_confirms_ledger_id FOREIGN KEY (ledger_id) REFERENCES daily_pay_ledgers(id),
    CONSTRAINT fk_daily_work_confirms_daily_worker_id FOREIGN KEY (daily_worker_id) REFERENCES daily_workers(id)
);
CREATE INDEX idx_daily_work_confirms_ledger_id ON daily_work_confirms (ledger_id);
CREATE INDEX idx_daily_work_confirms_daily_worker_id ON daily_work_confirms (daily_worker_id);
CREATE TABLE daily_pay_lines (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_id       bigint        NOT NULL,
    daily_worker_id bigint        NOT NULL,
    days            numeric(10,2) NOT NULL,
    gross_pay       numeric(15,0) NOT NULL,
    income_tax      numeric(15,0) NOT NULL,
    local_tax       numeric(15,0) NOT NULL,
    net_pay         numeric(15,0) NOT NULL,
    CONSTRAINT fk_daily_pay_lines_ledger_id FOREIGN KEY (ledger_id) REFERENCES daily_pay_ledgers(id),
    CONSTRAINT fk_daily_pay_lines_daily_worker_id FOREIGN KEY (daily_worker_id) REFERENCES daily_workers(id)
);
CREATE INDEX idx_daily_pay_lines_ledger_id ON daily_pay_lines (ledger_id);
CREATE INDEX idx_daily_pay_lines_daily_worker_id ON daily_pay_lines (daily_worker_id);
