-- 근태항목등록(원본 E020701): 근태입력이 고르던 고정 목록(연차 · 반차 · 병가 · 경조 · 공가 · 기타)을 항목 마스터로.
CREATE TABLE attendance_kinds (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code       varchar(20)  NOT NULL,
    name       varchar(20)  NOT NULL,
    kind_group varchar(50),
    type       varchar(20)  NOT NULL,
    hour_unit  boolean      NOT NULL DEFAULT false,
    remark     varchar(500),
    active     boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_attendance_kinds_code UNIQUE (code),
    CONSTRAINT uk_attendance_kinds_name UNIQUE (name),
    CONSTRAINT ck_attendance_kinds_type CHECK (type IN ('BASIC', 'VACATION', 'COMMUTE'))
);
INSERT INTO attendance_kinds (created_at, updated_at, code, name, type, hour_unit, active) VALUES
    (now(), now(), '30001', '연차', 'VACATION', false, true),
    (now(), now(), '30002', '반차', 'VACATION', false, true),
    (now(), now(), '30003', '병가', 'BASIC', false, true),
    (now(), now(), '30004', '경조', 'BASIC', false, true),
    (now(), now(), '30005', '공가', 'BASIC', false, true),
    (now(), now(), '30006', '기타', 'BASIC', false, true);
