-- 휴가항목등록(원본 E020702) + 근태항목의 [휴가코드]. 근태유형이 '휴가' 인 근태항목은 휴가항목 하나를 가리킨다.
-- 처음 심어 둔 연차 · 반차(휴가 유형)가 가리킬 '올해 연차' 항목을 하나 심는다.
CREATE TABLE vacation_kinds (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    code        varchar(20)  NOT NULL,
    name        varchar(50)  NOT NULL,
    period_from date         NOT NULL,
    period_to   date         NOT NULL,
    carry_over  boolean      NOT NULL DEFAULT false,
    remark      varchar(500),
    active      boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_vacation_kinds_code UNIQUE (code)
);
INSERT INTO vacation_kinds (created_at, updated_at, code, name, period_from, period_to, carry_over, active)
VALUES (now(), now(), '20001', extract(year from now())::int || '연차',
        make_date(extract(year from now())::int, 1, 1), make_date(extract(year from now())::int, 12, 31), false, true);

ALTER TABLE attendance_kinds ADD COLUMN vacation_kind_id bigint;
ALTER TABLE attendance_kinds ADD CONSTRAINT fk_attendance_kinds_vacation_kind_id
    FOREIGN KEY (vacation_kind_id) REFERENCES vacation_kinds(id);
CREATE INDEX idx_attendance_kinds_vacation_kind_id ON attendance_kinds (vacation_kind_id);
UPDATE attendance_kinds SET vacation_kind_id = (SELECT id FROM vacation_kinds WHERE code = '20001')
WHERE type = 'VACATION';
