-- (회사 스키마) 간이지급명세서(E030116) — 원본 [신규(F2)] '간이지급명세서파일생성' 으로 만드는 한 장.
-- 자료구분(간이 근로소득 · 간이 거주자 사업소득 · 간이 거주자 기타소득) · 지급연월(근로는 반기, 사업 · 기타는 달) ·
-- 신고일자 · 담당자 부서명 · 성명 · 전화번호(셋 다 필수) · 제출자(직접제출 · 세무대리인). 금액은 들고 있지 않고
-- [조회] 때마다 급여명세 · 기타원천세에서 센다(2026-10-04 실측).
CREATE TABLE simple_payment_statements (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind           varchar(20)  NOT NULL CHECK (kind IN ('LABOR', 'BUSINESS', 'OTHER')),
    pay_year       integer      NOT NULL,
    period         integer      NOT NULL,
    report_date    date         NOT NULL,
    manager_dept   varchar(100) NOT NULL,
    manager_name   varchar(100) NOT NULL,
    manager_phone  varchar(50)  NOT NULL,
    submitter      varchar(10)  NOT NULL CHECK (submitter IN ('DIRECT', 'AGENT')),
    created_at     timestamp,
    updated_at     timestamp
);
