-- 소득자등록(세무 › 기타원천세 E030301) — 기타원천세를 지급받는 사람 · 법인의 마스터(2026-10-04 loginaa 실측).
-- 구분(법인 · 개인) · 사업자등록번호 · 주민(법인)등록번호(필수) · 상호 · 성명(대표자명)(필수) · 주소 · 영문명 · 사업장소재지 ·
-- 소득자구분코드(실지명의구분 111 · 211 …) · 업종구분코드(940903 학원강사 …, 지급 줄의 기본값) · 은행명 · 계좌(증서)번호 ·
-- 기타구분(비거주자 · 외국인 · 비실명) · 생년월일 · 계정코드 · 모바일 · Email · 적요. 목록의 [삭제/삭제취소]는 지우지 않고 표시만 한다.
CREATE TABLE withholding_payees (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind             varchar(20)  NOT NULL CHECK (kind IN ('CORPORATE', 'INDIVIDUAL')),
    biz_reg_no       varchar(20),
    reg_no           varchar(20)  NOT NULL,
    trade_name       varchar(100),
    name             varchar(100) NOT NULL,
    address          varchar(200),
    english_name     varchar(100),
    biz_address      varchar(200),
    payee_kind_code  varchar(3),
    industry_code    varchar(6),
    bank_name        varchar(50),
    account_no       varchar(50),
    non_resident     boolean      NOT NULL DEFAULT false,
    foreigner        boolean      NOT NULL DEFAULT false,
    non_real_name    boolean      NOT NULL DEFAULT false,
    birth_date       varchar(8),
    account_code     varchar(20),
    mobile           varchar(30),
    email            varchar(100),
    memo             varchar(500),
    deleted          boolean      NOT NULL DEFAULT false,
    created_at       timestamp,
    updated_at       timestamp
);
