-- 테넌트 스키마를 public(본사) 과 같은 모양으로 맞춘다.
--
-- 왜 필요했나: 지금까지 스키마 변경을 db/migration 에만 넣고 db/tenant 에는 넣지 않았다.
-- 테넌트 스키마는 회사를 만들 때 V1__tenant_baseline.sql 이 한 번 실행되고 그 뒤로는 아무것도
-- 따라오지 않아서, 본사에 테이블·컬럼이 늘 때마다 테넌트만 뒤처졌다. 실제로 테이블 15개와
-- 컬럼 25개가 빠져 있었다(short_messages 통째, schedule_events.location/attendees,
-- sales_lines.lot_no 등). 테넌트 회사로 로그인해 그 화면을 열면 'column does not exist' 로
-- 터진다. ddl-auto:validate 는 기동할 때 기본 스키마만 보므로 이 어긋남을 잡지 못한다.
--
-- 앞으로: 스키마를 바꾸면 db/migration 과 db/tenant **양쪽에** 넣는다.
-- TenantMigrationRunner 가 기동할 때마다 등록된 모든 회사 스키마에 db/tenant 를 적용한다.
-- V1__tenant_baseline.sql 은 기존 테넌트에 '적용됨'으로 박혀 있으므로 절대 고치지 않는다
-- (고치면 체크섬이 어긋나 기존 테넌트의 마이그레이션이 통째로 멈춘다).
--
-- 이 파일의 DDL 은 손으로 쓰지 않고 public 스키마에서 그대로 떠 왔다.

-- ── 1. 빠진 테이블 ─────────────────────────────────────────────
CREATE TABLE chat_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    room_id bigint NOT NULL,
    sender_id bigint,
    content text NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE chat_room_members (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    last_read_at timestamp(6) without time zone
);
ALTER TABLE chat_room_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chat_room_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE chat_rooms (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(100),
    direct boolean DEFAULT false NOT NULL,
    direct_key character varying(40),
    created_by_id bigint,
    last_message_at timestamp(6) without time zone
);
ALTER TABLE chat_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME chat_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE collect_sources (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(100) NOT NULL,
    category character varying(40) NOT NULL,
    endpoint character varying(200) NOT NULL,
    paged boolean DEFAULT false NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL
);
ALTER TABLE collect_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME collect_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE custom_field_defs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    entity_type character varying(40) NOT NULL,
    field_key character varying(50) NOT NULL,
    label character varying(100) NOT NULL,
    field_type character varying(20) NOT NULL,
    options character varying(500),
    required boolean DEFAULT false NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL
);
ALTER TABLE custom_field_defs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME custom_field_defs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE custom_field_values (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    entity_type character varying(40) NOT NULL,
    entity_id bigint NOT NULL,
    field_key character varying(50) NOT NULL,
    value character varying(1000)
);
ALTER TABLE custom_field_values ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME custom_field_values_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE evidence_attachments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    entity_type character varying(30) NOT NULL,
    entity_id bigint NOT NULL,
    doc_no character varying(50),
    doc_date date,
    evidence_date date,
    method character varying(20) NOT NULL,
    worker character varying(50),
    note character varying(300),
    file_id bigint,
    CONSTRAINT ck_evidence_method CHECK (((method)::text = ANY ((ARRAY['TAX_INVOICE'::character varying, 'CARD'::character varying, 'CASH_RECEIPT'::character varying, 'STATEMENT'::character varying, 'ETC'::character varying])::text[])))
);
ALTER TABLE evidence_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME evidence_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE mall_accounts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(20) NOT NULL,
    partner_id bigint,
    seller_id character varying(100),
    memo character varying(300),
    active boolean DEFAULT true NOT NULL
);
ALTER TABLE mall_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mall_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE mall_item_mappings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    mall character varying(50) NOT NULL,
    mall_product_code character varying(100) NOT NULL,
    mall_product_name character varying(200),
    item_id bigint NOT NULL,
    active boolean DEFAULT true NOT NULL
);
ALTER TABLE mall_item_mappings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mall_item_mappings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE medical_device_reports (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    report_month character varying(7) NOT NULL,
    period_from date NOT NULL,
    period_to date NOT NULL,
    line_count integer NOT NULL,
    total_qty numeric(18,2) DEFAULT 0 NOT NULL,
    file_id bigint,
    created_by character varying(50)
);
ALTER TABLE medical_device_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME medical_device_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE my_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    owner_id bigint NOT NULL,
    item_id bigint NOT NULL,
    default_qty integer DEFAULT 1 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);
ALTER TABLE my_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME my_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE short_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    sender_id bigint,
    recipient_id bigint NOT NULL,
    partner_id bigint,
    content text NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    read_at timestamp(6) without time zone,
    archived boolean DEFAULT false NOT NULL,
    link_source character varying(40),
    link_ref character varying(100),
    link_path character varying(200)
);
ALTER TABLE short_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME short_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE spam_rules (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    kind character varying(20) NOT NULL,
    pattern character varying(200) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    note character varying(200),
    CONSTRAINT ck_spam_rules_kind CHECK (((kind)::text = ANY ((ARRAY['FROM_ADDRESS'::character varying, 'SUBJECT'::character varying, 'BODY'::character varying])::text[])))
);
ALTER TABLE spam_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spam_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE stored_file_data (
    id bigint NOT NULL,
    data bytea NOT NULL
);
CREATE TABLE stored_files (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(260) NOT NULL,
    content_type character varying(120),
    size_bytes bigint NOT NULL,
    uploader character varying(50)
);
ALTER TABLE stored_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME stored_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY chat_room_members
    ADD CONSTRAINT chat_room_members_pkey PRIMARY KEY (id);
ALTER TABLE ONLY chat_rooms
    ADD CONSTRAINT chat_rooms_direct_key_key UNIQUE (direct_key);
ALTER TABLE ONLY chat_rooms
    ADD CONSTRAINT chat_rooms_pkey PRIMARY KEY (id);
ALTER TABLE ONLY collect_sources
    ADD CONSTRAINT collect_sources_pkey PRIMARY KEY (id);
ALTER TABLE ONLY custom_field_defs
    ADD CONSTRAINT custom_field_defs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY custom_field_values
    ADD CONSTRAINT custom_field_values_pkey PRIMARY KEY (id);
ALTER TABLE ONLY evidence_attachments
    ADD CONSTRAINT evidence_attachments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY mall_accounts
    ADD CONSTRAINT mall_accounts_code_key UNIQUE (code);
ALTER TABLE ONLY mall_accounts
    ADD CONSTRAINT mall_accounts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY mall_item_mappings
    ADD CONSTRAINT mall_item_mappings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY medical_device_reports
    ADD CONSTRAINT medical_device_reports_pkey PRIMARY KEY (id);
ALTER TABLE ONLY my_items
    ADD CONSTRAINT my_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY short_messages
    ADD CONSTRAINT short_messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY spam_rules
    ADD CONSTRAINT spam_rules_pkey PRIMARY KEY (id);
ALTER TABLE ONLY stored_file_data
    ADD CONSTRAINT stored_file_data_pkey PRIMARY KEY (id);
ALTER TABLE ONLY stored_files
    ADD CONSTRAINT stored_files_pkey PRIMARY KEY (id);
ALTER TABLE ONLY chat_room_members
    ADD CONSTRAINT uk_chat_room_members UNIQUE (room_id, user_id);
ALTER TABLE ONLY custom_field_defs
    ADD CONSTRAINT uk_custom_field_defs UNIQUE (entity_type, field_key);
ALTER TABLE ONLY custom_field_values
    ADD CONSTRAINT uk_custom_field_values UNIQUE (entity_type, entity_id, field_key);
ALTER TABLE ONLY mall_item_mappings
    ADD CONSTRAINT uk_mall_item_mappings UNIQUE (mall, mall_product_code);
ALTER TABLE ONLY my_items
    ADD CONSTRAINT uk_my_items_owner_item UNIQUE (owner_id, item_id);
CREATE INDEX idx_chat_messages_room_id ON chat_messages USING btree (room_id, id);
CREATE INDEX idx_chat_messages_sender ON chat_messages USING btree (sender_id);
CREATE INDEX idx_chat_room_members_room ON chat_room_members USING btree (room_id);
CREATE INDEX idx_chat_room_members_user ON chat_room_members USING btree (user_id);
CREATE INDEX idx_chat_rooms_created_by ON chat_rooms USING btree (created_by_id);
CREATE INDEX idx_custom_field_values_entity ON custom_field_values USING btree (entity_type, entity_id);
CREATE INDEX idx_evidence_doc_date ON evidence_attachments USING btree (doc_date);
CREATE INDEX idx_evidence_file ON evidence_attachments USING btree (file_id);
CREATE INDEX idx_evidence_target ON evidence_attachments USING btree (entity_type, entity_id);
CREATE INDEX idx_mall_accounts_partner_id ON mall_accounts USING btree (partner_id);
CREATE INDEX idx_mall_item_mappings_item_id ON mall_item_mappings USING btree (item_id);
CREATE INDEX idx_medical_device_reports_file ON medical_device_reports USING btree (file_id);
CREATE INDEX idx_my_items_item ON my_items USING btree (item_id);
CREATE INDEX idx_short_messages_partner ON short_messages USING btree (partner_id);
CREATE INDEX idx_short_messages_recipient ON short_messages USING btree (recipient_id);
CREATE INDEX idx_short_messages_sender ON short_messages USING btree (sender_id);
ALTER TABLE ONLY chat_messages
    ADD CONSTRAINT chat_messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES chat_rooms(id);
ALTER TABLE ONLY chat_messages
    ADD CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users(id);
ALTER TABLE ONLY chat_room_members
    ADD CONSTRAINT chat_room_members_room_id_fkey FOREIGN KEY (room_id) REFERENCES chat_rooms(id);
ALTER TABLE ONLY chat_room_members
    ADD CONSTRAINT chat_room_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY chat_rooms
    ADD CONSTRAINT chat_rooms_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES users(id);
ALTER TABLE ONLY evidence_attachments
    ADD CONSTRAINT evidence_attachments_file_id_fkey FOREIGN KEY (file_id) REFERENCES stored_files(id);
ALTER TABLE ONLY mall_accounts
    ADD CONSTRAINT mall_accounts_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES business_partners(id);
ALTER TABLE ONLY mall_item_mappings
    ADD CONSTRAINT mall_item_mappings_item_id_fkey FOREIGN KEY (item_id) REFERENCES items(id);
ALTER TABLE ONLY medical_device_reports
    ADD CONSTRAINT medical_device_reports_file_id_fkey FOREIGN KEY (file_id) REFERENCES stored_files(id);
ALTER TABLE ONLY my_items
    ADD CONSTRAINT my_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES items(id);
ALTER TABLE ONLY my_items
    ADD CONSTRAINT my_items_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id);
ALTER TABLE ONLY short_messages
    ADD CONSTRAINT short_messages_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES business_partners(id);
ALTER TABLE ONLY short_messages
    ADD CONSTRAINT short_messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES users(id);
ALTER TABLE ONLY short_messages
    ADD CONSTRAINT short_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users(id);
ALTER TABLE ONLY stored_file_data
    ADD CONSTRAINT stored_file_data_id_fkey FOREIGN KEY (id) REFERENCES stored_files(id);

-- ── 2. 빠진 컬럼 ───────────────────────────────────────────────
ALTER TABLE approval_documents ADD COLUMN category character varying(50);
ALTER TABLE approval_documents ADD COLUMN print_format character varying(50);
ALTER TABLE approval_documents ADD COLUMN label_text character varying(100);
ALTER TABLE approval_documents ADD COLUMN attachment_id bigint;
ALTER TABLE drive_documents ADD COLUMN file_id bigint;
ALTER TABLE items ADD COLUMN udi_di character varying(50);
ALTER TABLE items ADD COLUMN management_item_id bigint;
ALTER TABLE mails ADD COLUMN spam boolean DEFAULT false NOT NULL;
ALTER TABLE mails ADD COLUMN spam_reason character varying(200);
ALTER TABLE mall_orders ADD COLUMN mall_product_code character varying(100);
ALTER TABLE purchase_lines ADD COLUMN lot_no character varying(60);
ALTER TABLE purchase_lines ADD COLUMN extra_cost numeric(18,2);
ALTER TABLE purchase_lines ADD COLUMN source_order_id bigint;
ALTER TABLE purchase_order_lines ADD COLUMN remark character varying(200);
ALTER TABLE purchase_order_lines ADD COLUMN partner_id bigint;
ALTER TABLE purchase_orders ADD COLUMN employee_id bigint;
ALTER TABLE purchase_orders ADD COLUMN warehouse_id bigint;
ALTER TABLE purchase_orders ADD COLUMN currency character varying(10) DEFAULT 'KRW'::character varying NOT NULL;
ALTER TABLE purchases ADD COLUMN vat_by_slip boolean DEFAULT false NOT NULL;
ALTER TABLE sales ADD COLUMN vat_by_slip boolean DEFAULT false NOT NULL;
ALTER TABLE sales_lines ADD COLUMN lot_no character varying(60);
ALTER TABLE sales_lines ADD COLUMN extra_cost numeric(18,2);
ALTER TABLE sales_lines ADD COLUMN source_order_id bigint;
ALTER TABLE schedule_events ADD COLUMN location character varying(200);
ALTER TABLE schedule_events ADD COLUMN attendees character varying(500);

-- ── 3. 위 컬럼의 FK·인덱스 ─────────────────────────────────────
ALTER TABLE approval_documents ADD CONSTRAINT fk_approval_documents_attachment FOREIGN KEY (attachment_id) REFERENCES stored_files(id);
ALTER TABLE drive_documents ADD CONSTRAINT drive_documents_file_id_fkey FOREIGN KEY (file_id) REFERENCES stored_files(id);
ALTER TABLE items ADD CONSTRAINT fk_items_management_item FOREIGN KEY (management_item_id) REFERENCES management_items(id);
ALTER TABLE purchase_lines ADD CONSTRAINT fk_purchase_lines_source_order FOREIGN KEY (source_order_id) REFERENCES purchase_orders(id);
ALTER TABLE purchase_order_lines ADD CONSTRAINT fk_pol_partner FOREIGN KEY (partner_id) REFERENCES business_partners(id);
ALTER TABLE purchase_orders ADD CONSTRAINT fk_po_employee FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE purchase_orders ADD CONSTRAINT fk_po_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id);
ALTER TABLE sales_lines ADD CONSTRAINT fk_sales_lines_source_order FOREIGN KEY (source_order_id) REFERENCES sales_orders(id);
CREATE INDEX idx_approval_documents_attachment ON approval_documents USING btree (attachment_id);
CREATE INDEX idx_drive_documents_file ON drive_documents USING btree (file_id);
CREATE INDEX idx_items_management_item ON items USING btree (management_item_id);
CREATE INDEX idx_po_employee ON purchase_orders USING btree (employee_id);
CREATE INDEX idx_po_warehouse ON purchase_orders USING btree (warehouse_id);
CREATE INDEX idx_pol_partner ON purchase_order_lines USING btree (partner_id);
CREATE INDEX idx_purchase_lines_source_order ON purchase_lines USING btree (source_order_id);
CREATE INDEX idx_sales_lines_source_order ON sales_lines USING btree (source_order_id);

-- ── 4. V132(본사)와 같은 변경 — 일정관리 목록의 종료시간 ────────
ALTER TABLE schedule_events ADD COLUMN end_time varchar(10);
