-- 새로 만든 회사에 기안서 양식이 하나도 없던 것.
--
-- 본사(public)의 양식 22종은 V13__approval_backbone.sql 이 심는데, 그 INSERT 가
-- `INSERT INTO public.approval_form_templates` 로 **스키마를 박아 넣고** 있었다.
-- 테넌트 baseline 은 표만 만들고 행은 넣지 않는다. 그래서 회사를 새로 만들면
-- 기안서작성의 양식 목록이 비어 결재를 아예 시작할 수 없었다 — co_0002 가 실제로 0건이었다.
--
-- TenantSeeder 는 역할·권한·관리자·계정과목·회사정보까지만 심는다. 양식은 스키마와 함께
-- 가는 자료라 여기(마이그레이션)에 둔다. 본사가 앞으로 양식을 고치면 이 파일이 아니라
-- 양쪽 마이그레이션을 같이 더해야 한다 — CLAUDE.md 7.4 와 같은 규칙이다.
--
-- 내용은 본사의 현재 상태(V163 까지 반영된 것)와 글자 단위로 같다.

INSERT INTO approval_form_templates (code, name, sort_order, field_schema) VALUES
 ('LEAVE', '휴가신청서', 0, '[{"key": "periodFrom", "row": 1, "type": "datetime", "label": "신청일자(시작)", "required": true, "rowLabel": "신청일자"}, {"key": "periodTo", "row": 1, "sep": "~", "type": "datetime", "label": "신청일자(종료)", "required": true}, {"key": "detail", "type": "textarea", "label": "신청내용"}, {"key": "reason", "type": "textarea", "label": "신청사유", "required": true}]'::jsonb),
 ('BIZ_TRIP', '국내출장신청서', 1, '[{"key": "place", "type": "text", "label": "출장지", "required": true}, {"key": "traveler", "type": "text", "label": "출장자", "required": true}, {"key": "periodFrom", "row": 3, "type": "datetime", "label": "출장기간(시작)", "required": true, "rowLabel": "출장기간"}, {"key": "periodTo", "row": 3, "sep": "~", "type": "datetime", "label": "출장기간(종료)", "required": true}, {"key": "purpose", "type": "textarea", "label": "출장목적", "required": true}, {"key": "schedule", "type": "textarea", "label": "상세 출장 일정"}, {"key": "travelExpenses", "type": "table", "label": "여비산정", "columns": [{"key": "kind", "type": "text", "label": "구분"}, {"key": "amount", "type": "number", "label": "금액"}], "totalOf": "amount", "totalLabel": "여비 총계", "defaultRows": [{"kind": "숙박비"}, {"kind": "교통비"}, {"kind": "현지교통비"}, {"kind": "식비"}]}]'::jsonb),
 ('TRIP_REPORT', '출장복명서', 2, '[{"key": "place", "type": "text", "label": "출장지", "required": true}, {"key": "traveler", "type": "text", "label": "출장자", "required": true}, {"key": "periodFrom", "row": 3, "type": "datetime", "label": "출장기간(시작)", "required": true, "rowLabel": "출장기간"}, {"key": "periodTo", "row": 3, "sep": "~", "type": "datetime", "label": "출장기간(종료)", "required": true}, {"key": "result", "type": "textarea", "label": "출장결과", "required": true}]'::jsonb),
 ('BIZ_TRIP_PROXY', '국내출장신청서_타인기안', 3, '[{"key": "place", "type": "text", "label": "출장지", "required": true}, {"key": "traveler", "type": "text", "label": "출장자", "required": true}, {"key": "periodFrom", "row": 3, "type": "datetime", "label": "출장기간(시작)", "required": true, "rowLabel": "출장기간"}, {"key": "periodTo", "row": 3, "sep": "~", "type": "datetime", "label": "출장기간(종료)", "required": true}, {"key": "purpose", "type": "textarea", "label": "출장목적", "required": true}]'::jsonb),
 ('PURCHASE_REQ', '구매요청서', 4, '[{"key": "requestDate", "type": "date", "label": "구매일자", "required": true}, {"key": "vendor", "type": "text", "label": "구매처"}, {"key": "items", "type": "table", "label": "품목", "columns": [{"key": "name", "type": "text", "label": "품목"}, {"key": "qty", "type": "number", "label": "수량"}, {"key": "unit", "type": "text", "label": "단위"}, {"key": "supplyAmount", "type": "number", "label": "공급가액"}], "totalOf": "supplyAmount", "totalLabel": "합계"}, {"key": "reason", "type": "textarea", "label": "구매사유 및 기타사항", "required": true}]'::jsonb),
 ('INSPECTION', '검수확인서', 5, '[{"key": "purchaseDate", "type": "date", "label": "구매일자", "required": true}, {"key": "inspectDate", "type": "date", "label": "검수일자", "required": true}, {"key": "vendor", "type": "text", "label": "구매처"}, {"key": "items", "type": "table", "label": "품목", "columns": [{"key": "name", "type": "text", "label": "품목"}, {"key": "qty", "type": "number", "label": "수량"}, {"key": "unit", "type": "text", "label": "단위"}, {"key": "supplyAmount", "type": "number", "label": "공급가액"}], "totalOf": "supplyAmount", "totalLabel": "합계"}, {"key": "reason", "type": "textarea", "label": "구매사유 및 기타사항", "required": true}, {"key": "attachNote", "type": "textarea", "label": "첨부 서류"}]'::jsonb),
 ('TECH_DOC', '기술문서', 6, '[{"key": "effectiveDate", "type": "date", "label": "시행일자", "required": true}, {"key": "coopDept", "type": "text", "label": "협조부서"}, {"key": "agreement", "type": "text", "label": "합의"}]'::jsonb),
 ('OFFICIAL_LETTER', '공 문', 7, '[]'::jsonb),
 ('INTERNAL_GENERAL', '내부일반문서', 8, '[{"key": "effectiveDate", "type": "date", "label": "시행 일자", "required": true}, {"key": "workStartedAt", "type": "date", "label": "업무 발생 시점"}, {"key": "workFinishedAt", "type": "date", "label": "업무 완료 시점"}]'::jsonb),
 ('CONGRAT_MONEY', '경조금신청서', 9, '[{"key": "eventType", "type": "text", "label": "경조구분", "required": true}, {"key": "eventDate", "type": "date", "label": "경조일자", "required": true}, {"key": "amount", "type": "number", "label": "신청금액", "required": true}, {"key": "reason", "type": "textarea", "label": "사유"}]'::jsonb),
 ('CONGRAT_FLOWER', '경조화환신청서', 10, '[{"key": "eventType", "type": "text", "label": "경조구분", "required": true}, {"key": "eventDate", "type": "date", "label": "경조일자", "required": true}, {"key": "deliverTo", "type": "text", "label": "배송지", "required": true}]'::jsonb),
 ('MEDICAL_SUPPORT', '진료비지원신청서', 11, '[{"key": "treatDate", "type": "date", "label": "진료일자", "required": true}, {"key": "hospital", "type": "text", "label": "병원명"}, {"key": "amount", "type": "number", "label": "신청금액", "required": true}]'::jsonb),
 ('ABSENCE_REASON', '결근사유서', 12, '[{"key": "absenceDate", "type": "date", "label": "결근일자", "required": true}, {"key": "reason", "type": "textarea", "label": "결근사유", "required": true}]'::jsonb),
 ('PAYMENT_RESOLUTION', '지급결의서', 13, '[{"key": "payDate", "type": "date", "label": "지급일자", "required": true}, {"key": "payee", "type": "text", "label": "지급처", "required": true}, {"key": "amount", "type": "number", "label": "지급금액", "required": true}, {"key": "reason", "type": "textarea", "label": "지급사유", "required": true}]'::jsonb),
 ('PAYROLL_RESOLUTION', '급여 지급결의서', 14, '[{"key": "payMonth", "type": "text", "label": "근무 월", "required": true}, {"key": "payDate", "type": "date", "label": "지급예정일", "required": true}, {"key": "headcount", "type": "number", "label": "지급인원(명)"}, {"key": "payAmount", "type": "number", "label": "지급금액(원)"}, {"key": "payDetail", "type": "table", "label": "지급상세", "columns": [{"key": "kind", "type": "text", "label": "항목명"}, {"key": "taxable", "type": "number", "label": "과세금액"}, {"key": "nonTaxable", "type": "number", "label": "비과세금액"}], "totalOf": "taxable", "totalLabel": "과세 소계", "defaultRows": [{"kind": "기본급"}, {"kind": "상여금"}, {"kind": "야간근로수당"}, {"kind": "연장근로수당"}, {"kind": "연차수당"}, {"kind": "휴일근로수당"}, {"kind": "명절·휴가수당"}, {"kind": "식비보조"}, {"kind": "차량 비과세"}, {"kind": "보육수당"}]}, {"key": "deductDetail", "type": "table", "label": "공제상세", "columns": [{"key": "kind", "type": "text", "label": "항목명"}, {"key": "amount", "type": "number", "label": "금액"}], "totalOf": "amount", "totalLabel": "공제 합계", "defaultRows": [{"kind": "건강보험"}, {"kind": "고용보험"}, {"kind": "국민연금"}, {"kind": "근로소득세"}, {"kind": "근로지방소득세"}, {"kind": "농특세"}, {"kind": "연말정산소득세"}, {"kind": "연말정산지방소득세"}, {"kind": "장기요양보험"}, {"kind": "정산농특세"}, {"kind": "학자금상환"}, {"kind": "과학기술인공제회"}]}]'::jsonb),
 ('HR_ANNOUNCEMENT', '인사발령공고', 15, '[{"key": "effectiveDate", "type": "date", "label": "발령일자", "required": true}, {"key": "kind", "type": "text", "label": "발령내용"}, {"key": "targets", "type": "table", "label": "발령자", "columns": [{"key": "empNo", "type": "text", "label": "사번"}, {"key": "name", "type": "text", "label": "성명"}, {"key": "kindName", "type": "text", "label": "발령구분명"}, {"key": "fromRank", "type": "text", "label": "이전 직위/직급"}, {"key": "toRank", "type": "text", "label": "발령 직위/직급"}, {"key": "fromDept", "type": "text", "label": "이전 부서"}, {"key": "toDept", "type": "text", "label": "발령 부서"}]}]'::jsonb),
 ('VEHICLE_REPAIR', '차량수리비지출품의서', 16, '[{"key": "vehicleNo", "type": "text", "label": "차량번호", "required": true}, {"key": "repairDate", "type": "date", "label": "수리일자", "required": true}, {"key": "amount", "type": "number", "label": "수리비", "required": true}, {"key": "reason", "type": "textarea", "label": "수리사유"}]'::jsonb),
 ('INCIDENT_REPORT', '사고경위서', 17, '[{"key": "occurredAt", "type": "datetime", "label": "발생일시", "required": true}, {"key": "place", "type": "text", "label": "발생장소"}, {"key": "detail", "type": "textarea", "label": "경위", "required": true}]'::jsonb),
 ('PERSONAL_EXPENSE', '개인경비 사용내역서', 18, '[{"key": "items", "type": "table", "label": "사용내역", "columns": [{"key": "cardNo", "type": "text", "label": "카드번호"}, {"key": "useDate", "type": "date", "label": "사용날짜"}, {"key": "useTime", "type": "text", "label": "시간"}, {"key": "vendor", "type": "text", "label": "사용처(전표상 상호)"}, {"key": "purpose", "type": "text", "label": "사용내역(상세하게 기재)"}, {"key": "amount", "type": "number", "label": "사용금액"}, {"key": "note", "type": "text", "label": "비고"}], "totalOf": "amount", "totalLabel": "합계"}]'::jsonb),
 ('OVERSEAS_TRIP', '해외출장신청', 19, '[{"key": "country", "type": "text", "label": "출장국가", "required": true}, {"key": "traveler", "type": "text", "label": "출장자", "required": true}, {"key": "periodFrom", "row": 3, "type": "datetime", "label": "출장기간(시작)", "required": true, "rowLabel": "출장기간"}, {"key": "periodTo", "row": 3, "sep": "~", "type": "datetime", "label": "출장기간(종료)", "required": true}, {"key": "purpose", "type": "textarea", "label": "출장목적", "required": true}]'::jsonb),
 ('EXPENSE', '지출결의서', 20, '[]'::jsonb),
 ('GENERAL', '일반기안', 21, '[]'::jsonb);
