-- 사용자별 북마크(즐겨찾기).
--
-- 원본은 상단에 북마크바가 있고 [즐겨찾기]로 지금 화면을 담거나 뺀다. 옆의 [기본그룹]은
-- 그 북마크 묶음을 고르는 자리다. 사람마다 매일 여는 화면이 달라서 그렇게 돼 있다.
--
-- 우리 북마크바는 코드에 박힌 6개였다. 아무도 바꿀 수 없으니 자기 화면을 담을 수 없고,
-- 담을 수 없으니 쓰지 않게 된다.
--
-- 사용자별이라 auth 에 둔다. 회사 공통 설정(preferences)에 넣으면 한 사람이 고친 것이
-- 온 회사에 적용된다.

CREATE TABLE user_bookmarks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    label       varchar(100) NOT NULL,
    path        varchar(200) NOT NULL,
    sort_order  integer      NOT NULL DEFAULT 0,
    created_at  timestamp,
    updated_at  timestamp,
    CONSTRAINT uk_user_bookmarks_user_path UNIQUE (user_id, path)
);

-- PostgreSQL 은 FOREIGN KEY 를 만들어도 참조하는 쪽 컬럼에 인덱스를 안 만든다.
-- 없으면 그 사용자의 북마크를 뽑을 때마다 표를 통째로 훑는다.
CREATE INDEX idx_user_bookmarks_user ON user_bookmarks (user_id);
