-- 공용품 사용내역. 원본 공용품관리(E070204)는 공용품 마스터가 아니라
-- "누가 언제 어떤 공용품을 빌려 쓰고 반납했는가"를 기간으로 보여주는 화면이다.
CREATE TABLE supply_usages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    supply_item_id bigint NOT NULL,
    user_id bigint NOT NULL,
    use_date date NOT NULL,
    start_time varchar(10),
    end_time varchar(10),
    all_day boolean DEFAULT false NOT NULL,
    title varchar(200) NOT NULL,
    remark varchar(500),
    label_text varchar(100),
    return_status varchar(20) NOT NULL,
    CONSTRAINT supply_usages_supply_item_id_fkey FOREIGN KEY (supply_item_id) REFERENCES supply_items(id),
    CONSTRAINT supply_usages_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_supply_usages_return_status
        CHECK (return_status IN ('NOT_RETURNED', 'RETURNED', 'UNSPECIFIED'))
);

-- FK 컬럼 인덱스는 PostgreSQL 이 자동으로 만들어 주지 않는다(CLAUDE.md 7.1).
CREATE INDEX idx_supply_usages_supply_item ON supply_usages (supply_item_id);
CREATE INDEX idx_supply_usages_user ON supply_usages (user_id);
-- 목록이 항상 기간으로 훑는다.
CREATE INDEX idx_supply_usages_use_date ON supply_usages (use_date);
