-- 매출계획(sales_plans): 품목별 월 매출 목표(수량·금액).
-- 실적은 저장하지 않고 판매(sales) 집계로 대조한다(매출계획비교표).
-- 이카운트 계획관리 E040624~E040640 대응.
CREATE TABLE sales_plans (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    item_id     bigint         NOT NULL REFERENCES items (id),
    plan_year   integer        NOT NULL,
    plan_month  integer        NOT NULL,
    plan_qty    numeric(18, 2) NOT NULL DEFAULT 0,
    plan_amount numeric(18, 2) NOT NULL DEFAULT 0,
    remark      varchar(300),
    created_by  varchar(50)
);

-- FK 컬럼 인덱스(자식 조회·부모 삭제 시 순차스캔 방지)
CREATE INDEX idx_sales_plans_item_id ON sales_plans (item_id);
-- 연·월 단위 조회가 잦으므로 복합 인덱스
CREATE INDEX idx_sales_plans_year_month ON sales_plans (plan_year, plan_month);
