-- 품질검사요청(quality_inspection_requests): 검사 전 '요청'을 관리한다.
-- 요청(REQUESTED) → 검사완료(INSPECTED)/취소(CANCELED). 미검사현황 = status REQUESTED.
-- 이카운트 품질관리 C000692·E040628~E040631 대응.
CREATE TABLE quality_inspection_requests (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    request_no   varchar(30)    NOT NULL UNIQUE,
    request_date date           NOT NULL,
    type         varchar(20)    NOT NULL,
    item_id      bigint         NOT NULL REFERENCES items (id),
    lot_no       varchar(50),
    request_qty  numeric(18, 2) NOT NULL DEFAULT 0,
    due_date     date,
    status       varchar(20)    NOT NULL DEFAULT 'REQUESTED',
    requester    varchar(50),
    remark       varchar(300)
);

-- FK 컬럼 인덱스(자식 조회·부모 삭제 시 순차스캔 방지)
CREATE INDEX idx_qir_item_id ON quality_inspection_requests (item_id);
-- 미검사현황 등 상태 필터 조회가 잦다
CREATE INDEX idx_qir_status ON quality_inspection_requests (status);
