-- 프로젝트계획(project_plans): 프로젝트별 연간 계획 매출·원가.
-- 실적은 저장하지 않고 판매·구매·비용 전표를 프로젝트로 집계(ProjectProfitService)해 대조한다.
-- 이카운트 계획관리 C000653·E040636·E040637 대응.
CREATE TABLE project_plans (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    project_id   bigint         NOT NULL REFERENCES projects (id),
    plan_year    integer        NOT NULL,
    plan_revenue numeric(18, 2) NOT NULL DEFAULT 0,
    plan_cost    numeric(18, 2) NOT NULL DEFAULT 0,
    remark       varchar(300),
    created_by   varchar(50)
);

-- FK 컬럼 인덱스(자식 조회·부모 삭제 시 순차스캔 방지)
CREATE INDEX idx_project_plans_project_id ON project_plans (project_id);
-- 연 단위 조회가 잦다
CREATE INDEX idx_project_plans_year ON project_plans (plan_year);
