-- 로트 입출고 이력(lot_transactions): 로트 생성(입고)·소모(출고)·조정을 기록해
-- 로트 수불부/내역조회의 근거를 남긴다. 이카운트 시리얼/로트 E040618·E040620·E040634·E040639 대응.
CREATE TABLE lot_transactions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    lot_id          bigint         NOT NULL REFERENCES lots (id),
    tx_date         date           NOT NULL,
    type            varchar(20)    NOT NULL,
    quantity_change numeric(18, 2) NOT NULL,
    balance_after   numeric(18, 2) NOT NULL,
    note            varchar(300),
    created_by      varchar(50)
);

-- FK 컬럼 인덱스(로트별 이력 조회·부모 삭제 시 순차스캔 방지)
CREATE INDEX idx_lot_transactions_lot_id ON lot_transactions (lot_id);

-- 기존 로트의 초기 입고를 이력으로 백필(이력이 로트 생성 이전부터 있던 것처럼 보이게)
INSERT INTO lot_transactions (created_at, tx_date, type, quantity_change, balance_after, note, lot_id)
SELECT now(), inbound_date, 'INBOUND', inbound_qty, inbound_qty, '초기 입고(백필)', id
FROM lots;

-- 이미 소모된 분(현재고 < 입고량)은 출고 이력으로 백필해 balance_after 를 현재고와 맞춘다
INSERT INTO lot_transactions (created_at, tx_date, type, quantity_change, balance_after, note, lot_id)
SELECT now(), inbound_date, 'OUTBOUND', -(inbound_qty - stock_qty), stock_qty, '기소모(백필)', id
FROM lots
WHERE inbound_qty > stock_qty;
