-- 단계별재고조정(staged_stock_adjustments): 실사수량을 요청 → 승인(반영)/반려 단계로 처리.
-- 반영 시 일반 재고조정(stock_adjustments, ADJUST)을 생성해 실제 재고에 반영한다.
-- 이카운트 E040604 단계별재고조정·E040650 재고조정진행단계 대응.
CREATE TABLE staged_stock_adjustments (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    adjust_no    varchar(30)    NOT NULL UNIQUE,
    request_date date           NOT NULL,
    item_id      bigint         NOT NULL REFERENCES items (id),
    warehouse_id bigint         NOT NULL REFERENCES warehouses (id),
    book_qty     numeric(18, 2) NOT NULL DEFAULT 0,
    actual_qty   numeric(18, 2) NOT NULL DEFAULT 0,
    reason       varchar(300),
    status       varchar(20)    NOT NULL DEFAULT 'REQUESTED',
    requester    varchar(50),
    handler      varchar(50)
);

-- FK 컬럼 인덱스(자식 조회·부모 삭제 시 순차스캔 방지)
CREATE INDEX idx_ssa_item_id ON staged_stock_adjustments (item_id);
CREATE INDEX idx_ssa_warehouse_id ON staged_stock_adjustments (warehouse_id);
-- 진행단계(상태) 필터 조회가 잦다
CREATE INDEX idx_ssa_status ON staged_stock_adjustments (status);
