-- A/S 소모부품(as_parts): A/S 수리에 나간 부품을 기록. 등록 시 창고 재고를 차감(OUTBOUND)한다.
-- 이카운트 E040641 A/S소모현황 대응.
CREATE TABLE as_parts (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    as_request_id  bigint         NOT NULL REFERENCES as_requests (id),
    item_id        bigint         NOT NULL REFERENCES items (id),
    warehouse_id   bigint         NOT NULL REFERENCES warehouses (id),
    quantity       numeric(18, 2) NOT NULL,
    unit_price     numeric(18, 2),
    remark         varchar(300),
    created_by     varchar(50)
);

-- FK 컬럼 인덱스(자식 조회·부모 삭제 시 순차스캔 방지)
CREATE INDEX idx_as_parts_as_request_id ON as_parts (as_request_id);
CREATE INDEX idx_as_parts_item_id ON as_parts (item_id);
CREATE INDEX idx_as_parts_warehouse_id ON as_parts (warehouse_id);
