-- 특별단가(special_prices, E040124): 표준단가(items.unit_price)를 덮어쓰는 예외 단가.
-- 적용범위는 거래처별(partner_id) 또는 특별단가그룹별(price_group) 중 하나.
-- trade_type 은 @Enumerated(STRING) — CHECK 제약을 두지 않는다(값 추가 시 마이그레이션 부담·validate 미검증).
CREATE TABLE special_prices (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    trade_type  varchar(20)    NOT NULL,
    item_id     bigint         NOT NULL REFERENCES items (id),
    partner_id  bigint         REFERENCES business_partners (id),
    price_group varchar(50),
    unit_price  numeric(18, 2) NOT NULL DEFAULT 0,
    active      boolean        NOT NULL DEFAULT true,
    remark      varchar(300),
    created_by  varchar(50)
);

-- FK 컬럼 인덱스(자식 조회·부모 삭제 시 순차스캔 방지)
CREATE INDEX idx_special_prices_item_id ON special_prices (item_id);
CREATE INDEX idx_special_prices_partner_id ON special_prices (partner_id);
-- resolve 조회(구분·품목·활성)에 쓰는 복합 인덱스
CREATE INDEX idx_special_prices_lookup ON special_prices (trade_type, item_id, active);
