-- 카드사(card_issuers, E010109) · 결제대행사(payment_agencies, E010114) 기초등록 마스터.
-- 고립 CRUD 마스터(코드·명·사용여부). 다른 테이블을 참조하지 않으므로 FK 없음.
CREATE TABLE card_issuers (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    code       varchar(50)  NOT NULL UNIQUE,
    name       varchar(100) NOT NULL,
    fee_rate   numeric(6, 3) DEFAULT 0,
    remark     varchar(200),
    active     boolean      NOT NULL DEFAULT true
);

CREATE TABLE payment_agencies (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    code       varchar(50)  NOT NULL UNIQUE,
    name       varchar(100) NOT NULL,
    ceo_name   varchar(50),
    phone      varchar(30),
    email      varchar(100),
    remark     varchar(200),
    active     boolean      NOT NULL DEFAULT true
);
