-- 쇼핑몰 품목코드연결(E041004): (쇼핑몰, 몰품목코드) → 우리 품목 매핑.
-- 주문 수집 시 품목 미지정이면 이 매핑으로 자동 연결한다.
CREATE TABLE mall_item_mappings (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        timestamp(6),
    updated_at        timestamp(6),
    mall              varchar(50)  NOT NULL,
    mall_product_code varchar(100) NOT NULL,
    mall_product_name varchar(200),
    item_id           bigint       NOT NULL REFERENCES items (id),
    active            boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_mall_item_mappings UNIQUE (mall, mall_product_code)
);
CREATE INDEX idx_mall_item_mappings_item_id ON mall_item_mappings (item_id);

-- 몰 주문에 몰품목코드 보관(자동연결 키)
ALTER TABLE mall_orders ADD COLUMN mall_product_code varchar(100);
