-- 쇼핑몰 등록(C000664): 우리가 판매하는 쇼핑몰/통합관리솔루션 계정 마스터.
-- 주문 수집·품목코드연결의 '쇼핑몰' 선택지 + 판매전환 기본 거래처(partner).
-- type 은 @Enumerated(STRING) — CHECK 제약을 두지 않는다(값 추가 부담·validate 미검증).
CREATE TABLE mall_accounts (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    code       varchar(50)  NOT NULL UNIQUE,
    name       varchar(100) NOT NULL,
    type       varchar(20)  NOT NULL,
    partner_id bigint       REFERENCES business_partners (id),
    seller_id  varchar(100),
    memo       varchar(300),
    active     boolean      NOT NULL DEFAULT true
);
CREATE INDEX idx_mall_accounts_partner_id ON mall_accounts (partner_id);
