-- 사용자정의 필드 엔진(Self-Customizing). 판매입력 II 등 '추가 형식필드'를 전표 모델 변경 없이 붙인다.
-- 범용 EAV: 정의(custom_field_defs) + 값(custom_field_values). 값은 특정 모듈 엔티티를 FK 로 묶지 않는다.
-- field_type 은 @Enumerated(STRING) — CHECK 제약 두지 않음.
CREATE TABLE custom_field_defs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    entity_type varchar(40)  NOT NULL,
    field_key   varchar(50)  NOT NULL,
    label       varchar(100) NOT NULL,
    field_type  varchar(20)  NOT NULL,
    options     varchar(500),
    required    boolean      NOT NULL DEFAULT false,
    sort_order  integer      NOT NULL DEFAULT 0,
    active      boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_custom_field_defs UNIQUE (entity_type, field_key)
);

CREATE TABLE custom_field_values (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    entity_type varchar(40)   NOT NULL,
    entity_id   bigint        NOT NULL,
    field_key   varchar(50)   NOT NULL,
    value       varchar(1000),
    CONSTRAINT uk_custom_field_values UNIQUE (entity_type, entity_id, field_key)
);
-- 전표별 값 조회가 잦으므로 복합 인덱스
CREATE INDEX idx_custom_field_values_entity ON custom_field_values (entity_type, entity_id);
