-- 수집데이터 소스 등록(E100000): 하드코딩돼 있던 수집 소스를 테이블로 옮겨 동적 등록 가능하게 함.
-- 소스 = 우리 API 목록 GET 엔드포인트. 수집 실행은 그 엔드포인트를 호출해 행수 집계.
CREATE TABLE collect_sources (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    name       varchar(100) NOT NULL,
    category   varchar(40)  NOT NULL,
    endpoint   varchar(200) NOT NULL,
    paged      boolean      NOT NULL DEFAULT false,
    sort_order integer      NOT NULL DEFAULT 0,
    active     boolean      NOT NULL DEFAULT true
);

-- 기존 DataCollectPage 하드코딩 9종 시드(기존 동작 보존)
INSERT INTO collect_sources (name, category, endpoint, paged, sort_order, active) VALUES
    ('품목 마스터',        '기준정보', '/items',                              false, 1, true),
    ('거래처 마스터',      '기준정보', '/partners',                           false, 2, true),
    ('창고 마스터',        '기준정보', '/warehouses',                         false, 3, true),
    ('현재고 (품목x창고)', '재고',     '/stock',                              false, 4, true),
    ('재고 수불 이력',     '재고',     '/stock/transactions?page=0&size=1',   true,  5, true),
    ('판매 전표',          '영업',     '/sales',                              false, 6, true),
    ('구매 전표',          '구매',     '/purchases',                          false, 7, true),
    ('작업지시',           '생산',     '/work-orders',                        false, 8, true),
    ('생산실적',           '생산',     '/productions',                        false, 9, true);
