-- 쪽지(E010851 쪽지수발신내역 / C000663 커뮤니케이션센터).
-- 사람이 보내는 단문 + 시스템 자동알림(전자결재 완료·반려 등)을 같은 테이블에 둔다.
-- sender_id 가 NULL 이면 시스템 자동알림.
CREATE TABLE short_messages (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    sender_id    bigint      REFERENCES users (id),
    recipient_id bigint      NOT NULL REFERENCES users (id),
    partner_id   bigint      REFERENCES business_partners (id),
    content      text        NOT NULL,
    sent_at      timestamp(6) NOT NULL,
    read_at      timestamp(6),
    archived     boolean     NOT NULL DEFAULT false,
    link_source  varchar(40),
    link_ref     varchar(100),
    link_path    varchar(200)
);

-- FK 컬럼 인덱스(CLAUDE.md §7.1). 받은쪽지함 조회가 recipient 기준이라 특히 필요.
CREATE INDEX idx_short_messages_sender    ON short_messages (sender_id);
CREATE INDEX idx_short_messages_recipient ON short_messages (recipient_id);
CREATE INDEX idx_short_messages_partner   ON short_messages (partner_id);
