-- 파일 저장 인프라. 업로드 바이트를 DB(bytea)에 둔다.
-- 회사별 스키마 멀티테넌시라 DB 저장이 테넌트 격리·백업 일관성을 그대로 물려받는다.
-- 메타와 바이트를 나눈 이유: 목록 조회가 실수로 파일 전체를 끌어오지 못하게 하려고.
CREATE TABLE stored_files (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    name         varchar(260) NOT NULL,
    content_type varchar(120),
    size_bytes   bigint       NOT NULL,
    uploader     varchar(50)
);

CREATE TABLE stored_file_data (
    id   bigint PRIMARY KEY REFERENCES stored_files (id),
    data bytea  NOT NULL
);

-- ECDrive 문서에 실제 파일을 연결(기존 행은 메타데이터만 있는 상태로 남는다)
ALTER TABLE drive_documents ADD COLUMN file_id bigint REFERENCES stored_files (id);
CREATE INDEX idx_drive_documents_file ON drive_documents (file_id);
