-- 증빙센터(E040730). 전표(판매·구매·비용)에 붙는 증빙.
-- 대상은 entity_type + entity_id 로 FK 없이 가리킨다(세 모듈에 동시에 묶이지 않게 — 사용자정의필드와 같은 방식).
CREATE TABLE evidence_attachments (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    entity_type   varchar(30) NOT NULL,
    entity_id     bigint      NOT NULL,
    doc_no        varchar(50),
    doc_date      date,
    evidence_date date,
    method        varchar(20) NOT NULL,
    worker        varchar(50),
    note          varchar(300),
    file_id       bigint REFERENCES stored_files (id),
    CONSTRAINT ck_evidence_method CHECK (method IN ('TAX_INVOICE','CARD','CASH_RECEIPT','STATEMENT','ETC'))
);

-- 전표 상세 패널이 (종류,전표id)로 찾고, 증빙센터는 전표일자로 훑는다
CREATE INDEX idx_evidence_target ON evidence_attachments (entity_type, entity_id);
CREATE INDEX idx_evidence_doc_date ON evidence_attachments (doc_date);
CREATE INDEX idx_evidence_file ON evidence_attachments (file_id);
