-- 의료기기공급내역보고(E040231).
-- 품목 UDI-DI: 값이 있는 품목만 보고 대상이다(별도 플래그를 두지 않는다 — 코드가 없으면 보고할 수 없으므로).
ALTER TABLE items ADD COLUMN udi_di varchar(50);

-- 보고파일 산출 이력(=원본의 송신이력). 대외 전송 채널이 붙으면 여기에 전송상태·접수번호를 더한다.
CREATE TABLE medical_device_reports (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    report_month varchar(7)  NOT NULL,
    period_from date         NOT NULL,
    period_to   date         NOT NULL,
    line_count  integer      NOT NULL,
    total_qty   numeric(18,2) NOT NULL DEFAULT 0,
    file_id     bigint REFERENCES stored_files (id),
    created_by  varchar(50)
);

CREATE INDEX idx_medical_device_reports_file ON medical_device_reports (file_id);
