-- 스팸 메일함(E077005). 외부 메일서버 연동은 없고, 공용메일 수신 등록이 곧 외부 유입 지점이라
-- 그 자리에서 규칙과 대조해 스팸으로 가른다.
--
-- mails.status enum 에 SPAM 을 더하지 않고 boolean 을 쓴 이유: status 에는 CHECK 제약이 걸려 있어
-- 값 추가가 제약 교체를 부르고, 스팸 여부는 처리상태와 직교하는 별개 축이다(스팸이면서 미읽음일 수 있다).
ALTER TABLE mails ADD COLUMN spam boolean NOT NULL DEFAULT false;
ALTER TABLE mails ADD COLUMN spam_reason varchar(200);

CREATE TABLE spam_rules (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    kind       varchar(20)  NOT NULL,
    pattern    varchar(200) NOT NULL,
    active     boolean      NOT NULL DEFAULT true,
    note       varchar(200),
    CONSTRAINT ck_spam_rules_kind CHECK (kind IN ('FROM_ADDRESS','SUBJECT','BODY'))
);
