-- 사내 메신저(앱바 💬). 쪽지(short_messages)와 달리 "대화방"이 1급 개념이다.
-- 쪽지는 한 건씩 받는 사람에게 꽂히는 알림이고, 메신저는 같은 방에 쌓이는 대화 흐름이다.
-- 그래서 테이블을 합치지 않는다 — 읽음 처리 단위가 메시지 vs 방으로 다르다.

CREATE TABLE chat_rooms (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    -- 그룹방 이름. 1:1 방은 상대 이름을 보여주므로 NULL.
    name            varchar(100),
    direct          boolean      NOT NULL DEFAULT false,
    -- 1:1 방 중복 생성 방지 키. 두 사용자 id 를 정렬해 'min:max' 로 만든다. 그룹방은 NULL
    -- (PostgreSQL 은 UNIQUE 컬럼의 NULL 중복을 허용하므로 그룹방은 제약을 타지 않는다).
    direct_key      varchar(40)  UNIQUE,
    created_by_id   bigint       REFERENCES users (id),
    -- 방 목록 정렬용. 마지막 메시지 시각을 비정규화해 둔다(목록마다 max(sent_at) 를 스캔하지 않으려고).
    last_message_at timestamp(6)
);

CREATE TABLE chat_room_members (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    room_id      bigint       NOT NULL REFERENCES chat_rooms (id),
    user_id      bigint       NOT NULL REFERENCES users (id),
    joined_at    timestamp(6) NOT NULL,
    -- 이 시각 이후 도착한 남의 메시지가 '안 읽음'. NULL 이면 한 번도 안 읽은 것.
    last_read_at timestamp(6),
    CONSTRAINT uk_chat_room_members UNIQUE (room_id, user_id)
);

CREATE TABLE chat_messages (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6),
    room_id    bigint       NOT NULL REFERENCES chat_rooms (id),
    -- NULL 이면 시스템 안내('OOO 님이 참여했습니다'). 사람 메시지와 같은 흐름에 섞여야 읽힌다.
    sender_id  bigint       REFERENCES users (id),
    content    text         NOT NULL,
    sent_at    timestamp(6) NOT NULL
);

-- FK 컬럼 인덱스(CLAUDE.md §7.1).
CREATE INDEX idx_chat_rooms_created_by     ON chat_rooms (created_by_id);
CREATE INDEX idx_chat_room_members_room    ON chat_room_members (room_id);
CREATE INDEX idx_chat_room_members_user    ON chat_room_members (user_id);
CREATE INDEX idx_chat_messages_sender      ON chat_messages (sender_id);
-- 대화 열기·폴링(방 안에서 id 오름차순)이 가장 잦은 조회라 복합 인덱스로 둔다.
CREATE INDEX idx_chat_messages_room_id     ON chat_messages (room_id, id);
