-- My품목 — 사용자별 자주 쓰는 품목 묶음.
-- 이카운트 전표 입력 툴바의 [My품목 ▾](원본 버튼 id `group12myProdLoadsubmain`).
--
-- 이 테이블은 users 와 items 를 둘 다 참조한다. 모듈 의존 규칙(CLAUDE.md 4.1)상 그게 가능한 모듈은
-- groupware 뿐이라 엔티티를 거기에 뒀다 — inventory·auth 는 아무 모듈도 참조하지 않는 기반층이고,
-- trade 는 auth 를 모른다. 화면은 재고 I 에 있지만 엔티티가 사는 곳은 참조 방향이 정한다.
--
-- FK 컬럼 인덱스는 직접 만든다(CLAUDE.md 7.1). owner_id 는 (owner_id,item_id) 유니크가
-- 선행열로 커버하므로 따로 만들지 않는다.

CREATE TABLE my_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    owner_id    bigint  NOT NULL REFERENCES users (id),
    item_id     bigint  NOT NULL REFERENCES items (id),
    default_qty integer NOT NULL DEFAULT 1,
    sort_order  integer NOT NULL DEFAULT 0,
    CONSTRAINT uk_my_items_owner_item UNIQUE (owner_id, item_id)
);

CREATE INDEX idx_my_items_item ON my_items (item_id);
