-- V12: 사용자 정의 그룹 마스터 (품목그룹 / 거래처그룹) 신설
--
-- 배경: 품목·거래처의 '구분'은 enum(ItemCategory, PartnerType)으로 고정돼 있다.
--       이 둘은 바꿀 수 없다 — PartnerType 은 canBuy()/canSell() 로 매입·매출 가능
--       여부를 강제하고(PurchaseService, SalesOrderService, SalesService, ShipmentService),
--       ItemCategory 는 원자재/반제품/제품 같은 제조업 표준 구분이다.
--
--       사용자가 화면에서 자유롭게 추가·수정하는 건 고정 구분이 아니라 그 옆에 붙는
--       '그룹'이다. 그래서 enum 을 테이블로 바꾸는 대신 그룹 마스터를 새로 만들고
--       nullable FK 로 연결한다. 순수 추가라 기존 데이터·로직은 그대로 둔다.
--
-- 삭제 정책: 그룹은 참조되는 쪽이므로 FK 는 RESTRICT(기본값)로 둔다.
--            쓰던 그룹을 지우려 하면 실패하고, active=false 소프트 삭제를 쓴다.

CREATE TABLE public.item_groups (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code       character varying(50)  NOT NULL,
    name       character varying(100) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    active     boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_item_groups_code UNIQUE (code)
);

CREATE TABLE public.partner_groups (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code       character varying(50)  NOT NULL,
    name       character varying(100) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    active     boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_partner_groups_code UNIQUE (code)
);

-- nullable: 그룹 미지정 품목/거래처를 허용한다(기존 행 전부가 여기 해당).
ALTER TABLE public.items ADD COLUMN item_group_id bigint;
ALTER TABLE public.items ADD CONSTRAINT fk_items_item_group_id
    FOREIGN KEY (item_group_id) REFERENCES public.item_groups(id);
CREATE INDEX idx_items_item_group_id ON public.items (item_group_id);

ALTER TABLE public.business_partners ADD COLUMN partner_group_id bigint;
ALTER TABLE public.business_partners ADD CONSTRAINT fk_business_partners_partner_group_id
    FOREIGN KEY (partner_group_id) REFERENCES public.partner_groups(id);
CREATE INDEX idx_business_partners_partner_group_id ON public.business_partners (partner_group_id);
