-- 설문조사를 실제 설문으로 만든다.
--
-- 지금까지 surveys 는 제목·기간과 '대상 인원수·응답 수를 손으로 적는 정수'뿐이었다.
-- 질문도 응답도 없어서 /surveys/{id}/respond 는 그 숫자를 +1 할 뿐이었고,
-- "누가 무엇을 답했는지"는 어디에도 없었다. 원본 설문조사입력(E070256)에 맞춰
-- 문항·대상·응답·답을 실제로 저장한다.

-- ── 1. surveys 확장 ────────────────────────────────────────────
-- 상태 CHECK 는 값이 늘면 같이 고쳐야 한다. validate 는 이걸 못 잡고,
-- 새 값을 insert 할 때 23514 로만 터진다.
ALTER TABLE surveys DROP CONSTRAINT surveys_status_check;
ALTER TABLE surveys ADD CONSTRAINT surveys_status_check
    CHECK (status IN ('DRAFT', 'OPEN', 'CLOSED', 'UNSENT'));

ALTER TABLE surveys ADD COLUMN post_no integer;
ALTER TABLE surveys ADD COLUMN end_at timestamp(6) without time zone;
ALTER TABLE surveys ADD COLUMN target_scope varchar(20);
ALTER TABLE surveys ADD COLUMN anonymous boolean DEFAULT false NOT NULL;
ALTER TABLE surveys ADD COLUMN result_visibility varchar(20);
ALTER TABLE surveys ADD COLUMN header_text varchar(1000);

-- 기존 3건 백필. 게시글번호는 등록 순서(id)를 그대로 쓰고,
-- 종료일은 그날 끝(23:59:59)으로 옮긴다 — 날짜만 있던 값을 시각까지 있는 값으로 바꾸는 것이라
-- 그날 하루는 응답할 수 있어야 한다.
UPDATE surveys SET post_no = id WHERE post_no IS NULL;
UPDATE surveys SET end_at = end_date + time '23:59:59' WHERE end_at IS NULL AND end_date IS NOT NULL;
UPDATE surveys SET target_scope = 'INTERNAL' WHERE target_scope IS NULL;
UPDATE surveys SET result_visibility = 'ALL' WHERE result_visibility IS NULL;

ALTER TABLE surveys ALTER COLUMN post_no SET NOT NULL;
ALTER TABLE surveys ALTER COLUMN target_scope SET NOT NULL;
ALTER TABLE surveys ALTER COLUMN result_visibility SET NOT NULL;
ALTER TABLE surveys ADD CONSTRAINT ck_surveys_target_scope CHECK (target_scope IN ('INTERNAL', 'EXTERNAL'));
ALTER TABLE surveys ADD CONSTRAINT ck_surveys_result_visibility
    CHECK (result_visibility IN ('ALL', 'PARTIAL', 'NONE'));

-- 손으로 적던 숫자는 이제 세어서 낸다. 두 곳에 적으면 반드시 어긋난다.
ALTER TABLE surveys DROP COLUMN target;
ALTER TABLE surveys DROP COLUMN responses;
ALTER TABLE surveys DROP COLUMN start_date;
ALTER TABLE surveys DROP COLUMN end_date;

-- ── 2. 문항 ────────────────────────────────────────────────────
CREATE TABLE survey_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    survey_id bigint NOT NULL,
    seq integer NOT NULL,
    type varchar(20) NOT NULL,
    content varchar(500) NOT NULL,
    option1 varchar(200),
    option2 varchar(200),
    option3 varchar(200),
    option4 varchar(200),
    option5 varchar(200),
    required boolean DEFAULT false NOT NULL,
    CONSTRAINT survey_questions_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES surveys(id),
    CONSTRAINT ck_survey_questions_type CHECK (type IN (
        'SINGLE', 'MULTI', 'SINGLE_ETC', 'MULTI_ETC',
        'SHORT_TEXT', 'LONG_TEXT', 'RANK', 'DATE', 'SCALE'))
);
CREATE INDEX idx_survey_questions_survey ON survey_questions (survey_id);

-- ── 3. 설문대상 ────────────────────────────────────────────────
CREATE TABLE survey_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    survey_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT survey_targets_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES surveys(id),
    CONSTRAINT survey_targets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_survey_targets UNIQUE (survey_id, user_id)
);
CREATE INDEX idx_survey_targets_survey ON survey_targets (survey_id);
CREATE INDEX idx_survey_targets_user ON survey_targets (user_id);

-- ── 4. 응답 ────────────────────────────────────────────────────
-- 익명 설문이면 respondent_id 를 비운 채로 저장한다. 넣어 두고 화면에서만 가리는 것은 익명이 아니다.
-- 대신 respondent_key(로그인ID 해시)로 같은 사람의 두 번째 응답만 막는다.
CREATE TABLE survey_responses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    survey_id bigint NOT NULL,
    respondent_id bigint,
    respondent_key varchar(64),
    submitted_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT survey_responses_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES surveys(id),
    CONSTRAINT survey_responses_respondent_id_fkey FOREIGN KEY (respondent_id) REFERENCES users(id),
    CONSTRAINT uk_survey_responses_once UNIQUE (survey_id, respondent_key)
);
CREATE INDEX idx_survey_responses_survey ON survey_responses (survey_id);
CREATE INDEX idx_survey_responses_respondent ON survey_responses (respondent_id);

CREATE TABLE survey_answers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    response_id bigint NOT NULL,
    question_id bigint NOT NULL,
    value text,
    CONSTRAINT survey_answers_response_id_fkey FOREIGN KEY (response_id) REFERENCES survey_responses(id),
    CONSTRAINT survey_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES survey_questions(id)
);
CREATE INDEX idx_survey_answers_response ON survey_answers (response_id);
CREATE INDEX idx_survey_answers_question ON survey_answers (question_id);
