-- V13: 전자결재 백본 — 양식 마스터 / 폼 데이터 / 기안번호 / 수신참조·공유자 / ERP전표 연결
--
-- 배경: 기안서가 formType enum 6종과 content 문자열 하나로만 돼 있어서
--       (1) 사용자가 양식을 늘릴 수 없고
--       (2) 출장지·여비산정·구매사유 같은 양식별 항목을 구조적으로 담지 못하며
--       (3) 이카운트 원본에 있는 'ERP전표(건)' / '연결전표'를 표현할 방법이 없다.
--
-- ApprovalFormType 은 분기 로직이 전혀 없다(코드 전역 검색으로 확인). 그래서 이 enum 은
-- 코드 마스터로 전환해도 안전한 유일한 케이스다. PartnerType·SettlementType 처럼
-- 로직을 지고 있는 enum 은 그대로 둔다.
--
-- form_type 컬럼은 이 마이그레이션에서 지우지 않는다. 백필 결과를 확인한 뒤 V14 에서 떨군다.

-- ── 1. 양식 마스터 (이카운트 '공통양식등록') ──────────────────────────
CREATE TABLE public.approval_form_templates (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone,
    code         character varying(50)  NOT NULL,
    name         character varying(100) NOT NULL,
    sort_order   integer NOT NULL DEFAULT 0,
    active       boolean NOT NULL DEFAULT true,
    -- 양식별 입력 항목 정의. 프론트가 이걸 읽어 폼을 그린다. 빈 배열이면 자유서식(리치텍스트)만.
    field_schema jsonb   NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT uk_approval_form_templates_code UNIQUE (code)
);

-- 이카운트 기안서작성 화면의 양식 20종. sort_order 는 원본 '정렬순서'를 따른다.
INSERT INTO public.approval_form_templates (code, name, sort_order, field_schema) VALUES
 ('LEAVE',            '휴가신청서',              0,
  '[{"key":"periodFrom","label":"신청일자(시작)","type":"datetime","required":true},
    {"key":"periodTo","label":"신청일자(종료)","type":"datetime","required":true},
    {"key":"detail","label":"신청내용","type":"textarea"},
    {"key":"reason","label":"신청사유","type":"textarea","required":true}]'::jsonb),

 ('BIZ_TRIP',         '국내출장신청서',          1,
  '[{"key":"place","label":"출장지","type":"text","required":true},
    {"key":"traveler","label":"출장자","type":"text","required":true},
    {"key":"periodFrom","label":"출장기간(시작)","type":"datetime","required":true},
    {"key":"periodTo","label":"출장기간(종료)","type":"datetime","required":true},
    {"key":"purpose","label":"출장목적","type":"textarea","required":true},
    {"key":"schedule","label":"상세 출장 일정","type":"textarea"},
    {"key":"travelExpenses","label":"여비산정","type":"table",
     "columns":[{"key":"kind","label":"구분","type":"text"},{"key":"amount","label":"금액","type":"number"}],
     "defaultRows":[{"kind":"숙박비"},{"kind":"교통비"},{"kind":"현지교통비"},{"kind":"식비"}],
     "totalOf":"amount","totalLabel":"여비 총계"}]'::jsonb),

 ('TRIP_REPORT',      '출장복명서',              2,
  '[{"key":"place","label":"출장지","type":"text","required":true},
    {"key":"traveler","label":"출장자","type":"text","required":true},
    {"key":"periodFrom","label":"출장기간(시작)","type":"datetime","required":true},
    {"key":"periodTo","label":"출장기간(종료)","type":"datetime","required":true},
    {"key":"result","label":"출장결과","type":"textarea","required":true}]'::jsonb),

 ('BIZ_TRIP_PROXY',   '국내출장신청서_타인기안',  3,
  '[{"key":"place","label":"출장지","type":"text","required":true},
    {"key":"traveler","label":"출장자","type":"text","required":true},
    {"key":"periodFrom","label":"출장기간(시작)","type":"datetime","required":true},
    {"key":"periodTo","label":"출장기간(종료)","type":"datetime","required":true},
    {"key":"purpose","label":"출장목적","type":"textarea","required":true}]'::jsonb),

 ('PURCHASE_REQ',     '구매요청서',              4,
  '[{"key":"requestDate","label":"구매일자","type":"date","required":true},
    {"key":"vendor","label":"구매처","type":"text"},
    {"key":"items","label":"품목","type":"table",
     "columns":[{"key":"name","label":"품목","type":"text"},{"key":"qty","label":"수량","type":"number"},
                {"key":"unit","label":"단위","type":"text"},{"key":"supplyAmount","label":"공급가액","type":"number"}],
     "totalOf":"supplyAmount","totalLabel":"합계"},
    {"key":"reason","label":"구매사유 및 기타사항","type":"textarea","required":true}]'::jsonb),

 ('INSPECTION',       '검수확인서',              5,
  '[{"key":"purchaseDate","label":"구매일자","type":"date","required":true},
    {"key":"inspectDate","label":"검수일자","type":"date","required":true},
    {"key":"vendor","label":"구매처","type":"text"},
    {"key":"items","label":"품목","type":"table",
     "columns":[{"key":"name","label":"품목","type":"text"},{"key":"qty","label":"수량","type":"number"},
                {"key":"unit","label":"단위","type":"text"},{"key":"supplyAmount","label":"공급가액","type":"number"}],
     "totalOf":"supplyAmount","totalLabel":"합계"},
    {"key":"reason","label":"구매사유 및 기타사항","type":"textarea","required":true},
    {"key":"attachNote","label":"첨부 서류","type":"textarea"}]'::jsonb),

 ('TECH_DOC',         '기술문서',                6,  '[]'::jsonb),
 ('OFFICIAL_LETTER',  '공 문',                   7,  '[]'::jsonb),
 ('INTERNAL_GENERAL', '내부일반문서',            8,  '[]'::jsonb),

 ('CONGRAT_MONEY',    '경조금신청서',            9,
  '[{"key":"eventType","label":"경조구분","type":"text","required":true},
    {"key":"eventDate","label":"경조일자","type":"date","required":true},
    {"key":"amount","label":"신청금액","type":"number","required":true},
    {"key":"reason","label":"사유","type":"textarea"}]'::jsonb),

 ('CONGRAT_FLOWER',   '경조화환신청서',          10,
  '[{"key":"eventType","label":"경조구분","type":"text","required":true},
    {"key":"eventDate","label":"경조일자","type":"date","required":true},
    {"key":"deliverTo","label":"배송지","type":"text","required":true}]'::jsonb),

 ('MEDICAL_SUPPORT',  '진료비지원신청서',        11,
  '[{"key":"treatDate","label":"진료일자","type":"date","required":true},
    {"key":"hospital","label":"병원명","type":"text"},
    {"key":"amount","label":"신청금액","type":"number","required":true}]'::jsonb),

 ('ABSENCE_REASON',   '결근사유서',              12,
  '[{"key":"absenceDate","label":"결근일자","type":"date","required":true},
    {"key":"reason","label":"결근사유","type":"textarea","required":true}]'::jsonb),

 ('PAYMENT_RESOLUTION','지급결의서',             13,
  '[{"key":"payDate","label":"지급일자","type":"date","required":true},
    {"key":"payee","label":"지급처","type":"text","required":true},
    {"key":"amount","label":"지급금액","type":"number","required":true},
    {"key":"reason","label":"지급사유","type":"textarea","required":true}]'::jsonb),

 ('PAYROLL_RESOLUTION','급여 지급결의서',        14,  '[]'::jsonb),
 ('HR_ANNOUNCEMENT',  '인사발령공고',            15,  '[]'::jsonb),

 ('VEHICLE_REPAIR',   '차량수리비지출품의서',    16,
  '[{"key":"vehicleNo","label":"차량번호","type":"text","required":true},
    {"key":"repairDate","label":"수리일자","type":"date","required":true},
    {"key":"amount","label":"수리비","type":"number","required":true},
    {"key":"reason","label":"수리사유","type":"textarea"}]'::jsonb),

 ('INCIDENT_REPORT',  '사고경위서',              17,
  '[{"key":"occurredAt","label":"발생일시","type":"datetime","required":true},
    {"key":"place","label":"발생장소","type":"text"},
    {"key":"detail","label":"경위","type":"textarea","required":true}]'::jsonb),

 ('PERSONAL_EXPENSE', '개인경비 사용내역서',     18,
  '[{"key":"items","label":"사용내역","type":"table",
     "columns":[{"key":"useDate","label":"일자","type":"date"},{"key":"purpose","label":"용도","type":"text"},
                {"key":"amount","label":"금액","type":"number"}],
     "totalOf":"amount","totalLabel":"합계"}]'::jsonb),

 ('OVERSEAS_TRIP',    '해외출장신청',            19,
  '[{"key":"country","label":"출장국가","type":"text","required":true},
    {"key":"traveler","label":"출장자","type":"text","required":true},
    {"key":"periodFrom","label":"출장기간(시작)","type":"datetime","required":true},
    {"key":"periodTo","label":"출장기간(종료)","type":"datetime","required":true},
    {"key":"purpose","label":"출장목적","type":"textarea","required":true}]'::jsonb),

 -- 기존 enum 잔여분. 이미 쓰인 기안서가 있으므로 지우지 않는다.
 ('EXPENSE',          '지출결의서',              20,  '[]'::jsonb),
 ('GENERAL',          '일반기안',                21,  '[]'::jsonb);

-- ── 2. 기안서 확장 ────────────────────────────────────────────────────
ALTER TABLE public.approval_documents ADD COLUMN form_template_id bigint;
ALTER TABLE public.approval_documents ADD COLUMN draft_no   character varying(30);
ALTER TABLE public.approval_documents ADD COLUMN form_data  jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE public.approval_documents ADD COLUMN department character varying(100);
ALTER TABLE public.approval_documents ADD COLUMN project_id bigint;
ALTER TABLE public.approval_documents ADD COLUMN deleted    boolean NOT NULL DEFAULT false;
ALTER TABLE public.approval_documents ADD COLUMN deleted_at timestamp(6) without time zone;

-- form_type(enum 문자열) -> 양식 마스터 FK 백필. 코드가 그대로 일치한다.
UPDATE public.approval_documents d
   SET form_template_id = t.id
  FROM public.approval_form_templates t
 WHERE t.code = d.form_type
   AND d.form_template_id IS NULL;

-- 기안No. 백필: 기안일자별 일련번호 (이카운트 표기 '2026/07/10-2')
WITH numbered AS (
    SELECT id,
           to_char(draft_date, 'YYYY/MM/DD') || '-' ||
           row_number() OVER (PARTITION BY draft_date ORDER BY id) AS dno
      FROM public.approval_documents
     WHERE draft_no IS NULL
)
UPDATE public.approval_documents d
   SET draft_no = n.dno
  FROM numbered n
 WHERE d.id = n.id;

-- 백필이 끝났으므로 이제 필수로 굳힌다.
ALTER TABLE public.approval_documents ALTER COLUMN form_template_id SET NOT NULL;
ALTER TABLE public.approval_documents ALTER COLUMN draft_no SET NOT NULL;

ALTER TABLE public.approval_documents
    ADD CONSTRAINT uk_approval_documents_draft_no UNIQUE (draft_no);
ALTER TABLE public.approval_documents
    ADD CONSTRAINT fk_approval_documents_form_template_id
    FOREIGN KEY (form_template_id) REFERENCES public.approval_form_templates(id);
ALTER TABLE public.approval_documents
    ADD CONSTRAINT fk_approval_documents_project_id
    FOREIGN KEY (project_id) REFERENCES public.projects(id);

CREATE INDEX idx_approval_documents_form_template_id ON public.approval_documents (form_template_id);
CREATE INDEX idx_approval_documents_project_id       ON public.approval_documents (project_id);

-- ── 3. 수신참조 / 공유자 ──────────────────────────────────────────────
-- 결재자는 approval_lines(순차 결재)에 있다. 이 테이블은 결재권이 없는 참여자만 담는다.
CREATE TABLE public.approval_participants (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL,
    user_id     bigint NOT NULL,
    role        character varying(20) NOT NULL,
    CONSTRAINT fk_approval_participants_document_id FOREIGN KEY (document_id)
        REFERENCES public.approval_documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_approval_participants_user_id FOREIGN KEY (user_id)
        REFERENCES public.users(id),
    CONSTRAINT ck_approval_participants_role CHECK (role IN ('REFERENCE', 'SHARE')),
    CONSTRAINT uk_approval_participants UNIQUE (document_id, user_id, role)
);
CREATE INDEX idx_approval_participants_document_id ON public.approval_participants (document_id);
CREATE INDEX idx_approval_participants_user_id     ON public.approval_participants (user_id);

-- ── 4. 기안서 ↔ ERP 전표 연결 ─────────────────────────────────────────
-- 이카운트 '검수확인서' 하단에 구매전표가 통째로 붙고, 목록엔 'ERP전표(건)'가 뜬다.
--
-- 전표 종류별로 컬럼을 따로 두고 CHECK 로 '정확히 하나'를 강제한다.
-- voucher_type + voucher_id 같은 다형 참조는 FK 를 걸 수 없어 고아 행을 막지 못한다.
CREATE TABLE public.approval_document_vouchers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    document_id bigint NOT NULL,
    sales_id    bigint,
    purchase_id bigint,
    expense_id  bigint,
    CONSTRAINT fk_adv_document_id FOREIGN KEY (document_id)
        REFERENCES public.approval_documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_adv_sales_id    FOREIGN KEY (sales_id)    REFERENCES public.sales(id),
    CONSTRAINT fk_adv_purchase_id FOREIGN KEY (purchase_id) REFERENCES public.purchases(id),
    CONSTRAINT fk_adv_expense_id  FOREIGN KEY (expense_id)  REFERENCES public.expenses(id),
    CONSTRAINT ck_adv_exactly_one_voucher
        CHECK (num_nonnulls(sales_id, purchase_id, expense_id) = 1)
);
CREATE INDEX idx_adv_document_id ON public.approval_document_vouchers (document_id);
CREATE INDEX idx_adv_sales_id    ON public.approval_document_vouchers (sales_id);
CREATE INDEX idx_adv_purchase_id ON public.approval_document_vouchers (purchase_id);
CREATE INDEX idx_adv_expense_id  ON public.approval_document_vouchers (expense_id);

-- 같은 전표를 같은 기안서에 두 번 붙이지 못하게 한다(부분 유니크 — NULL 은 서로 충돌하지 않으므로 필요).
CREATE UNIQUE INDEX uk_adv_doc_sales    ON public.approval_document_vouchers (document_id, sales_id)    WHERE sales_id    IS NOT NULL;
CREATE UNIQUE INDEX uk_adv_doc_purchase ON public.approval_document_vouchers (document_id, purchase_id) WHERE purchase_id IS NOT NULL;
CREATE UNIQUE INDEX uk_adv_doc_expense  ON public.approval_document_vouchers (document_id, expense_id)  WHERE expense_id  IS NOT NULL;
