-- V17: 회계전표(분개) 계층 — 복식부기 General Ledger
--
-- 배경: 지금까지 판매/구매의 '회계반영'은 sales.accounting_reflected 플래그만 세울 뿐
--       실제 분개(차변/대변) 전표를 만들지 않았다. 그래서 계정별원장·분개장·
--       재무상태표·손익계산서를 뽑을 원천 데이터가 없었다.
--
-- journal_entries(전표 헤더) 1 : N journal_lines(분개 명세).
-- 전표당 차변합 = 대변합(대차평형)은 애플리케이션에서 강제한다(DB CHECK로는 집계 제약이 어려움).

-- 자동분개에 필요한 부가세 계정 2종 추가 (기존 시드에 없음).
INSERT INTO public.accounts (created_at, updated_at, code, name, division, detail_category, active) VALUES
 (now(), now(), '255', '부가세예수금', 'LIABILITY', '유동부채', true),
 (now(), now(), '135', '부가세대급금', 'ASSET',     '유동자산', true),
 (now(), now(), '253', '미지급금',     'LIABILITY', '유동부채', true)
ON CONFLICT (code) DO NOTHING;

CREATE TABLE public.journal_entries (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    doc_no      character varying(30)  NOT NULL,
    entry_date  date NOT NULL,
    description character varying(300),
    partner_id  bigint,
    -- 이 전표가 어느 업무전표에서 생성됐는지. MANUAL 은 직접 입력.
    source_type character varying(20) NOT NULL,
    source_id   bigint,
    created_by  character varying(50),
    CONSTRAINT uk_journal_entries_doc_no UNIQUE (doc_no),
    CONSTRAINT fk_journal_entries_partner_id FOREIGN KEY (partner_id)
        REFERENCES public.business_partners(id),
    CONSTRAINT ck_journal_entries_source_type
        CHECK (source_type IN ('SALES', 'PURCHASE', 'EXPENSE', 'MANUAL'))
);
CREATE INDEX idx_journal_entries_entry_date ON public.journal_entries (entry_date);
CREATE INDEX idx_journal_entries_partner_id ON public.journal_entries (partner_id);

-- 업무전표 1건은 회계전표 1건만 만든다(중복반영 방지). MANUAL(source_id NULL)은 대상 아님.
CREATE UNIQUE INDEX uk_journal_entries_source
    ON public.journal_entries (source_type, source_id)
    WHERE source_id IS NOT NULL;

CREATE TABLE public.journal_lines (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id    bigint NOT NULL,
    account_id  bigint NOT NULL,
    -- 한 라인은 차변 또는 대변 한쪽만 채운다. 반대쪽은 0.
    debit       numeric(18,2) NOT NULL DEFAULT 0,
    credit      numeric(18,2) NOT NULL DEFAULT 0,
    description character varying(300),
    line_no     integer NOT NULL DEFAULT 1,
    CONSTRAINT fk_journal_lines_entry_id FOREIGN KEY (entry_id)
        REFERENCES public.journal_entries(id) ON DELETE CASCADE,
    CONSTRAINT fk_journal_lines_account_id FOREIGN KEY (account_id)
        REFERENCES public.accounts(id),
    -- 음수 금지, 그리고 차변·대변 동시 기입 금지(정확히 한쪽만 > 0, 또는 둘 다 0인 조정라인 허용 안 함).
    CONSTRAINT ck_journal_lines_nonneg CHECK (debit >= 0 AND credit >= 0),
    CONSTRAINT ck_journal_lines_one_side CHECK (
        (debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)
    )
);
CREATE INDEX idx_journal_lines_entry_id   ON public.journal_lines (entry_id);
CREATE INDEX idx_journal_lines_account_id ON public.journal_lines (account_id);
