-- V18: 전자(세금)계산서
--
-- 판매전표 → 매출 세금계산서, 구매전표 → 매입 세금계산서를 발행한다.
-- 진행단계: 작성(DRAFT) → 발행(ISSUED) → 전송(SENT) → 승인(APPROVED).
--
-- 공급가액/세액은 발행 시점에 원본 전표에서 복사한다(원본이 바뀌어도 발행분은 고정).
-- 한 업무전표당 세금계산서 1건만 발행(sales_id/purchase_id 부분 유니크).

CREATE TABLE public.tax_invoices (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6) without time zone,
    updated_at     timestamp(6) without time zone,
    invoice_no     character varying(30)  NOT NULL,
    invoice_type   character varying(20)  NOT NULL,
    status         character varying(20)  NOT NULL DEFAULT 'DRAFT',
    issue_date     date NOT NULL,
    partner_id     bigint NOT NULL,
    supply_amount  numeric(18,2) NOT NULL DEFAULT 0,
    vat_amount     numeric(18,2) NOT NULL DEFAULT 0,
    total_amount   numeric(18,2) NOT NULL DEFAULT 0,
    -- 근거 업무전표. 종류에 따라 둘 중 하나만 채워진다.
    sales_id       bigint,
    purchase_id    bigint,
    remark         character varying(300),
    created_by     character varying(50),
    CONSTRAINT uk_tax_invoices_invoice_no UNIQUE (invoice_no),
    CONSTRAINT fk_tax_invoices_partner_id  FOREIGN KEY (partner_id)  REFERENCES public.business_partners(id),
    CONSTRAINT fk_tax_invoices_sales_id    FOREIGN KEY (sales_id)    REFERENCES public.sales(id),
    CONSTRAINT fk_tax_invoices_purchase_id FOREIGN KEY (purchase_id) REFERENCES public.purchases(id),
    CONSTRAINT ck_tax_invoices_type   CHECK (invoice_type IN ('SALES', 'PURCHASE')),
    CONSTRAINT ck_tax_invoices_status CHECK (status IN ('DRAFT', 'ISSUED', 'SENT', 'APPROVED')),
    -- 종류와 근거전표 일치: 매출이면 sales_id, 매입이면 purchase_id (정확히 하나).
    CONSTRAINT ck_tax_invoices_source CHECK (
        (invoice_type = 'SALES'    AND sales_id IS NOT NULL AND purchase_id IS NULL) OR
        (invoice_type = 'PURCHASE' AND purchase_id IS NOT NULL AND sales_id IS NULL)
    )
);
CREATE INDEX idx_tax_invoices_issue_date  ON public.tax_invoices (issue_date);
CREATE INDEX idx_tax_invoices_partner_id  ON public.tax_invoices (partner_id);
CREATE INDEX idx_tax_invoices_status      ON public.tax_invoices (status);

CREATE UNIQUE INDEX uk_tax_invoices_sales    ON public.tax_invoices (sales_id)    WHERE sales_id    IS NOT NULL;
CREATE UNIQUE INDEX uk_tax_invoices_purchase ON public.tax_invoices (purchase_id) WHERE purchase_id IS NOT NULL;
