-- V19: 급여관리 — 급여명세(payslip) + 수당/공제 라인, 4대보험 자동공제
--
-- 사원(employees)에 기본급을 두고, 사원+귀속월 단위로 급여명세를 만든다.
-- 실지급액 = 기본급 + 수당합 − 공제합. 공제는 4대보험을 자동 계산하고 수동 항목을 더한다.

ALTER TABLE public.employees ADD COLUMN base_salary numeric(18,2) NOT NULL DEFAULT 0;

-- 기존 시드 사원(V4)에 데모 기본급 부여. 코드 매칭이라 신규 DB에서는 대상이 없어 무해.
UPDATE public.employees SET base_salary = 3200000 WHERE code = 'EMP-0001';
UPDATE public.employees SET base_salary = 2900000 WHERE code = 'EMP-0002';
UPDATE public.employees SET base_salary = 3500000 WHERE code = 'EMP-0003';
UPDATE public.employees SET base_salary = 2700000 WHERE code = 'EMP-0004';

CREATE TABLE public.payslips (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6) without time zone,
    updated_at       timestamp(6) without time zone,
    employee_id      bigint NOT NULL,
    -- 귀속월 'YYYY-MM'
    pay_month        character varying(7) NOT NULL,
    base_salary      numeric(18,2) NOT NULL DEFAULT 0,
    allowance_total  numeric(18,2) NOT NULL DEFAULT 0,
    deduction_total  numeric(18,2) NOT NULL DEFAULT 0,
    net_pay          numeric(18,2) NOT NULL DEFAULT 0,
    -- 작성(DRAFT) → 확정(CONFIRMED)
    status           character varying(20) NOT NULL DEFAULT 'DRAFT',
    remark           character varying(300),
    created_by       character varying(50),
    CONSTRAINT fk_payslips_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees(id),
    CONSTRAINT ck_payslips_status CHECK (status IN ('DRAFT', 'CONFIRMED')),
    -- 사원당 같은 귀속월 급여명세는 1건만.
    CONSTRAINT uk_payslips_employee_month UNIQUE (employee_id, pay_month)
);
CREATE INDEX idx_payslips_employee_id ON public.payslips (employee_id);
CREATE INDEX idx_payslips_pay_month   ON public.payslips (pay_month);

CREATE TABLE public.payslip_lines (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payslip_id  bigint NOT NULL,
    -- ALLOWANCE(수당) / DEDUCTION(공제)
    kind        character varying(20) NOT NULL,
    name        character varying(100) NOT NULL,
    amount      numeric(18,2) NOT NULL DEFAULT 0,
    -- 4대보험 등 자동계산 항목이면 true (사용자가 지우지 못하게 화면에서 구분)
    auto        boolean NOT NULL DEFAULT false,
    line_no     integer NOT NULL DEFAULT 1,
    CONSTRAINT fk_payslip_lines_payslip_id FOREIGN KEY (payslip_id)
        REFERENCES public.payslips(id) ON DELETE CASCADE,
    CONSTRAINT ck_payslip_lines_kind CHECK (kind IN ('ALLOWANCE', 'DEDUCTION')),
    CONSTRAINT ck_payslip_lines_amount CHECK (amount >= 0)
);
CREATE INDEX idx_payslip_lines_payslip_id ON public.payslip_lines (payslip_id);
