-- V1__baseline_schema.sql
-- 2026-07-10 기준 운영 중이던 erp 스키마를 pg_dump -s 로 그대로 캡처한 베이스라인.
-- 기존 DB에는 flyway.baseline-on-migrate=true 로 인해 '적용됨' 표시만 되고 실행되지 않음.
-- 새 DB(빈 스키마)에서만 실제로 실행되어 전체 스키마를 구성함.
-- 이 파일은 절대 수정하지 말 것. 스키마 변경은 V2, V3... 새 파일로 추가.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14




--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    code character varying(20) NOT NULL,
    detail_category character varying(50),
    division character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    CONSTRAINT accounts_division_check CHECK (((division)::text = ANY ((ARRAY['ASSET'::character varying, 'LIABILITY'::character varying, 'EQUITY'::character varying, 'REVENUE'::character varying, 'EXPENSE'::character varying])::text[])))
);


--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: approval_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.approval_documents (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content oid NOT NULL,
    current_step integer NOT NULL,
    doc_no character varying(30) NOT NULL,
    draft_date date NOT NULL,
    form_type character varying(20) NOT NULL,
    reference character varying(300),
    status character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    drafter_id bigint NOT NULL,
    CONSTRAINT approval_documents_form_type_check CHECK (((form_type)::text = ANY ((ARRAY['LEAVE'::character varying, 'BIZ_TRIP'::character varying, 'TRIP_REPORT'::character varying, 'EXPENSE'::character varying, 'PURCHASE_REQ'::character varying, 'GENERAL'::character varying])::text[]))),
    CONSTRAINT approval_documents_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFTING'::character varying, 'IN_PROGRESS'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: approval_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.approval_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: approval_lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.approval_lines (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    acted_at timestamp(6) without time zone,
    comment character varying(300),
    status character varying(20) NOT NULL,
    step_order integer NOT NULL,
    approver_id bigint NOT NULL,
    document_id bigint NOT NULL,
    CONSTRAINT approval_lines_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: approval_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.approval_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: as_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.as_requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    as_no character varying(30) NOT NULL,
    charge character varying(50),
    created_by character varying(50),
    done_date date,
    receipt_date date NOT NULL,
    repair_note character varying(500),
    status character varying(20) NOT NULL,
    symptom character varying(500),
    item_id bigint NOT NULL,
    partner_id bigint NOT NULL,
    CONSTRAINT as_requests_status_check CHECK (((status)::text = ANY ((ARRAY['RECEIVED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: as_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.as_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.as_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendances (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    clock_in time(6) without time zone,
    clock_out time(6) without time zone,
    note character varying(200),
    work_date date NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: attendances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: board_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_posts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    author character varying(50),
    category character varying(30),
    content text,
    title character varying(200) NOT NULL,
    views integer NOT NULL
);


--
-- Name: board_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bom_lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bom_lines (
    id bigint NOT NULL,
    quantity numeric(18,4) NOT NULL,
    bom_id bigint NOT NULL,
    component_id bigint NOT NULL
);


--
-- Name: bom_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bom_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bom_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: boms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boms (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    remark character varying(300),
    product_id bigint NOT NULL
);


--
-- Name: boms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.boms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_partners; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_partners (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    address character varying(300),
    biz_item character varying(100),
    biz_reg_no character varying(20),
    biz_type character varying(100),
    ceo_name character varying(50),
    code character varying(50) NOT NULL,
    manager character varying(50),
    name character varying(200) NOT NULL,
    phone character varying(50),
    type character varying(20) NOT NULL,
    purchase_price_group character varying(50),
    sales_price_group character varying(50),
    CONSTRAINT business_partners_type_check CHECK (((type)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'SUPPLIER'::character varying, 'BOTH'::character varying])::text[])))
);


--
-- Name: business_partners_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.business_partners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_partners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_info (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address character varying(300),
    address_detail character varying(200),
    biz_item character varying(100),
    biz_reg_no character varying(20),
    biz_type character varying(100),
    ceo character varying(50),
    corp_reg_no character varying(20),
    email character varying(100),
    fax character varying(30),
    name character varying(200) NOT NULL,
    tel character varying(30),
    zipcode character varying(10)
);


--
-- Name: company_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crm_activities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.crm_activities (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    activity character varying(500),
    activity_date date NOT NULL,
    charge character varying(50),
    contact_name character varying(50),
    next_action character varying(300),
    stage character varying(20) NOT NULL,
    partner_id bigint NOT NULL,
    CONSTRAINT crm_activities_stage_check CHECK (((stage)::text = ANY ((ARRAY['LEAD'::character varying, 'CONSULTING'::character varying, 'QUOTE'::character varying, 'CONTRACT'::character varying, 'LOST'::character varying])::text[])))
);


--
-- Name: crm_activities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.crm_activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crm_activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: drive_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drive_documents (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    drive character varying(20) NOT NULL,
    important boolean NOT NULL,
    name character varying(200) NOT NULL,
    size_bytes bigint NOT NULL,
    trashed boolean NOT NULL,
    uploader character varying(50),
    category character varying(50),
    file_version character varying(30)
);


--
-- Name: drive_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.drive_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drive_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expenses (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(18,2) NOT NULL,
    content character varying(300),
    created_by character varying(50),
    department character varying(50),
    expense_date date NOT NULL,
    partner_name character varying(200),
    payment_method character varying(30),
    account_id bigint NOT NULL
);


--
-- Name: expenses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_costs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_costs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    actual_labor numeric(18,2) NOT NULL,
    actual_material numeric(18,2) NOT NULL,
    actual_overhead numeric(18,2) NOT NULL,
    labor_cost numeric(18,2) NOT NULL,
    material_cost numeric(18,2) NOT NULL,
    overhead_cost numeric(18,2) NOT NULL,
    period character varying(10) NOT NULL,
    item_id bigint NOT NULL
);


--
-- Name: item_costs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.item_costs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_costs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    barcode character varying(100),
    category character varying(30) NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    safety_stock numeric(18,2) NOT NULL,
    spec character varying(200),
    unit character varying(20) NOT NULL,
    unit_price numeric(18,2) NOT NULL,
    CONSTRAINT items_category_check CHECK (((category)::text = ANY ((ARRAY['RAW_MATERIAL'::character varying, 'SUB_MATERIAL'::character varying, 'SEMI_FINISHED'::character varying, 'FINISHED'::character varying, 'MERCHANDISE'::character varying])::text[])))
);


--
-- Name: items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lots (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    expire_date date,
    held boolean NOT NULL,
    inbound_date date NOT NULL,
    inbound_qty numeric(18,2) NOT NULL,
    lot_no character varying(50) NOT NULL,
    stock_qty numeric(18,2) NOT NULL,
    item_id bigint NOT NULL,
    warehouse_id bigint
);


--
-- Name: lots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: management_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.management_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    description character varying(200),
    name character varying(100) NOT NULL
);


--
-- Name: management_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.management_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.management_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: material_issues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.material_issues (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    issue_date date NOT NULL,
    note character varying(300),
    qty numeric(18,2) NOT NULL,
    item_id bigint NOT NULL,
    warehouse_id bigint,
    work_order_id bigint
);


--
-- Name: material_issues_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.material_issues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.material_issues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notices (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    author character varying(50),
    category character varying(30),
    content character varying(4000),
    pinned boolean NOT NULL,
    title character varying(200) NOT NULL,
    views integer NOT NULL
);


--
-- Name: notices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_stages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_stages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: order_stages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_stages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_stages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_types (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    description character varying(200),
    name character varying(100) NOT NULL
);


--
-- Name: order_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: preference; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.preference (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    approval_required boolean DEFAULT false NOT NULL,
    auto_doc_no boolean DEFAULT true NOT NULL,
    currency character varying(10) DEFAULT 'KRW'::character varying NOT NULL,
    decimals integer DEFAULT 0 NOT NULL,
    fiscal_start character varying(2) DEFAULT '01'::character varying NOT NULL,
    lot_use boolean DEFAULT true NOT NULL,
    negative_stock boolean DEFAULT false NOT NULL,
    price_hide boolean DEFAULT true NOT NULL
);


--
-- Name: preference_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.preference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.preference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: price_order_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.price_order_settings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    apply_order integer NOT NULL,
    category character varying(20) NOT NULL,
    function_name character varying(100) NOT NULL
);


--
-- Name: price_order_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.price_order_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_order_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: production_materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.production_materials (
    id bigint NOT NULL,
    quantity numeric(18,4) NOT NULL,
    component_id bigint NOT NULL,
    production_id bigint NOT NULL
);


--
-- Name: production_materials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.production_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: production_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.production_plans (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    demand_qty numeric(18,2) NOT NULL,
    plan_qty numeric(18,2) NOT NULL,
    plan_week character varying(20) NOT NULL,
    remark character varying(300),
    status character varying(20) NOT NULL,
    work_order_no character varying(30),
    product_id bigint NOT NULL,
    work_order_id bigint,
    CONSTRAINT production_plans_status_check CHECK (((status)::text = ANY ((ARRAY['REVIEW'::character varying, 'CONFIRMED'::character varying, 'ORDERED'::character varying])::text[])))
);


--
-- Name: production_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.production_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: production_processes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.production_processes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    cost_per_hr numeric(15,2) NOT NULL,
    name character varying(100) NOT NULL,
    std_time_min integer NOT NULL,
    workcenter character varying(100)
);


--
-- Name: production_processes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.production_processes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_processes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: production_resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.production_resources (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    capacity numeric(15,2) NOT NULL,
    code character varying(50) NOT NULL,
    cost_per_hr numeric(15,2) NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(20) NOT NULL,
    unit character varying(20)
);


--
-- Name: production_resources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.production_resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    prod_no character varying(30) NOT NULL,
    produced_qty numeric(18,2) NOT NULL,
    production_date date NOT NULL,
    product_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    work_order_id bigint NOT NULL
);


--
-- Name: productions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(30) NOT NULL,
    created_by character varying(50),
    end_date date,
    manager character varying(50),
    name character varying(200) NOT NULL,
    progress integer NOT NULL,
    remark character varying(500),
    start_date date NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT projects_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNING'::character varying, 'IN_PROGRESS'::character varying, 'ON_HOLD'::character varying, 'DONE'::character varying])::text[])))
);


--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_lines (
    id bigint NOT NULL,
    quantity numeric(18,2) NOT NULL,
    supply_amount numeric(18,2) NOT NULL,
    unit_price numeric(18,2) NOT NULL,
    vat_amount numeric(18,2) NOT NULL,
    item_id bigint NOT NULL,
    purchase_id bigint NOT NULL
);


--
-- Name: purchase_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchase_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchases (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    doc_no character varying(30) NOT NULL,
    purchase_date date NOT NULL,
    remark character varying(500),
    supply_amount numeric(18,2) NOT NULL,
    total_amount numeric(18,2) NOT NULL,
    vat_amount numeric(18,2) NOT NULL,
    partner_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    accounting_reflected boolean DEFAULT false NOT NULL
);


--
-- Name: purchases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quality_inspections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quality_inspections (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    defect_qty numeric(18,2) NOT NULL,
    inspected_qty numeric(18,2) NOT NULL,
    inspection_date date NOT NULL,
    inspection_no character varying(30) NOT NULL,
    inspector character varying(50),
    lot_no character varying(50),
    remark character varying(300),
    result character varying(20) NOT NULL,
    type character varying(20) NOT NULL,
    item_id bigint NOT NULL,
    lot_id bigint,
    CONSTRAINT quality_inspections_result_check CHECK (((result)::text = ANY ((ARRAY['PASS'::character varying, 'CONDITIONAL'::character varying, 'FAIL'::character varying])::text[]))),
    CONSTRAINT quality_inspections_type_check CHECK (((type)::text = ANY ((ARRAY['INCOMING'::character varying, 'PROCESS'::character varying, 'SHIPMENT'::character varying])::text[])))
);


--
-- Name: quality_inspections_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quality_inspections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quality_inspections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    description character varying(255),
    display_name character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    doc_no character varying(30) NOT NULL,
    remark character varying(500),
    sale_date date NOT NULL,
    supply_amount numeric(18,2) NOT NULL,
    total_amount numeric(18,2) NOT NULL,
    vat_amount numeric(18,2) NOT NULL,
    partner_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    accounting_reflected boolean DEFAULT false NOT NULL
);


--
-- Name: sales_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_lines (
    id bigint NOT NULL,
    quantity numeric(18,2) NOT NULL,
    supply_amount numeric(18,2) NOT NULL,
    unit_price numeric(18,2) NOT NULL,
    vat_amount numeric(18,2) NOT NULL,
    item_id bigint NOT NULL,
    sales_id bigint NOT NULL
);


--
-- Name: sales_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_order_lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_order_lines (
    id bigint NOT NULL,
    quantity numeric(18,2) NOT NULL,
    supply_amount numeric(18,2) NOT NULL,
    unit_price numeric(18,2) NOT NULL,
    vat_amount numeric(18,2) NOT NULL,
    item_id bigint NOT NULL,
    sales_order_id bigint NOT NULL,
    shipped_qty numeric(18,2) DEFAULT 0 NOT NULL
);


--
-- Name: sales_order_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_order_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    due_date date,
    order_date date NOT NULL,
    order_no character varying(30) NOT NULL,
    remark character varying(500),
    status character varying(20) NOT NULL,
    supply_amount numeric(18,2) NOT NULL,
    total_amount numeric(18,2) NOT NULL,
    vat_amount numeric(18,2) NOT NULL,
    partner_id bigint NOT NULL,
    CONSTRAINT sales_orders_status_check CHECK (((status)::text = ANY ((ARRAY['RECEIVED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: sales_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category character varying(30),
    created_by character varying(50),
    event_date date NOT NULL,
    owner character varying(50),
    remark character varying(500),
    start_time character varying(10),
    title character varying(200) NOT NULL
);


--
-- Name: schedule_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: security_policy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.security_policy (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    ip_restrict boolean DEFAULT false NOT NULL,
    login_fail_limit integer DEFAULT 5 NOT NULL,
    pw_cycle_days integer DEFAULT 90 NOT NULL,
    pw_length integer DEFAULT 8 NOT NULL,
    session_timeout integer DEFAULT 30 NOT NULL,
    two_factor boolean DEFAULT false NOT NULL
);


--
-- Name: security_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.security_policy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.security_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlements (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(18,2) NOT NULL,
    created_by character varying(50),
    doc_no character varying(30) NOT NULL,
    method character varying(30),
    note character varying(500),
    settle_date date NOT NULL,
    type character varying(20) NOT NULL,
    partner_id bigint NOT NULL,
    CONSTRAINT settlements_type_check CHECK (((type)::text = ANY ((ARRAY['RECEIPT'::character varying, 'PAYMENT'::character varying])::text[])))
);


--
-- Name: settlements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipment_lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipment_lines (
    id bigint NOT NULL,
    amount numeric(18,2) NOT NULL,
    quantity numeric(18,2) NOT NULL,
    unit_price numeric(18,2) NOT NULL,
    item_id bigint NOT NULL,
    shipment_id bigint NOT NULL,
    order_line_id bigint
);


--
-- Name: shipment_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipment_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipment_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    remark character varying(500),
    ship_date date NOT NULL,
    ship_no character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(18,2) NOT NULL,
    total_quantity numeric(18,2) NOT NULL,
    partner_id bigint NOT NULL,
    sales_order_id bigint,
    CONSTRAINT shipments_status_check CHECK (((status)::text = ANY ((ARRAY['READY'::character varying, 'SHIPPED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: shipments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_lots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_lots (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    expiry_date date,
    inbound_date date NOT NULL,
    inbound_qty numeric(18,2) NOT NULL,
    lot_no character varying(40) NOT NULL,
    note character varying(300),
    status character varying(20) NOT NULL,
    stock_qty numeric(18,2) NOT NULL,
    item_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    CONSTRAINT stock_lots_status_check CHECK (((status)::text = ANY ((ARRAY['IN_STOCK'::character varying, 'SHIPPED'::character varying, 'HOLD'::character varying])::text[])))
);


--
-- Name: stock_lots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_lots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_lots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    balance_after numeric(18,2) NOT NULL,
    created_by character varying(50),
    note character varying(500),
    quantity_change numeric(18,2) NOT NULL,
    transaction_date date NOT NULL,
    type character varying(20) NOT NULL,
    unit_price numeric(18,2),
    item_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    CONSTRAINT stock_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['INBOUND'::character varying, 'OUTBOUND'::character varying, 'ADJUST'::character varying])::text[])))
);


--
-- Name: stock_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_transfers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_transfers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    quantity numeric(18,2) NOT NULL,
    reason character varying(300),
    transfer_date date NOT NULL,
    transfer_no character varying(30) NOT NULL,
    from_warehouse_id bigint NOT NULL,
    item_id bigint NOT NULL,
    to_warehouse_id bigint NOT NULL
);


--
-- Name: stock_transfers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_transfers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_transfers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stocks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    quantity numeric(18,2) NOT NULL,
    item_id bigint NOT NULL,
    warehouse_id bigint NOT NULL
);


--
-- Name: stocks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supply_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supply_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category character varying(50),
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    note character varying(300),
    stock_qty numeric(15,2) NOT NULL,
    unit character varying(20)
);


--
-- Name: supply_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.supply_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supply_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: surveys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.surveys (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    end_date date,
    responses integer NOT NULL,
    start_date date,
    status character varying(20) NOT NULL,
    target integer NOT NULL,
    title character varying(200) NOT NULL,
    CONSTRAINT surveys_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: surveys_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.surveys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.surveys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    department character varying(50),
    email character varying(100),
    enabled boolean NOT NULL,
    name character varying(50) NOT NULL,
    password character varying(100) NOT NULL,
    username character varying(50) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vacation_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vacation_requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    days numeric(5,1) NOT NULL,
    end_date date NOT NULL,
    reason character varying(200),
    start_date date NOT NULL,
    status character varying(10) NOT NULL,
    type character varying(20) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: vacation_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vacation_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vacation_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.warehouses (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    code character varying(50) NOT NULL,
    location character varying(200),
    name character varying(100) NOT NULL
);


--
-- Name: warehouses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.warehouses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_journals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_journals (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content oid NOT NULL,
    department character varying(50),
    partner_name character varying(100),
    report_date date NOT NULL,
    title character varying(200) NOT NULL,
    author_id bigint NOT NULL
);


--
-- Name: work_journals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_journals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_journals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(50),
    due_date date,
    order_date date NOT NULL,
    order_no character varying(30) NOT NULL,
    planned_qty numeric(18,2) NOT NULL,
    produced_qty numeric(18,2) NOT NULL,
    remark character varying(300),
    status character varying(20) NOT NULL,
    product_id bigint NOT NULL,
    warehouse_id bigint NOT NULL,
    CONSTRAINT work_orders_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: work_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_posts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content oid NOT NULL,
    forward_to character varying(200),
    post_date date NOT NULL,
    post_no integer NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    writer character varying(50) NOT NULL,
    CONSTRAINT work_posts_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'DONE'::character varying])::text[])))
);


--
-- Name: work_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_results (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    defect_qty numeric(18,2) NOT NULL,
    good_qty numeric(18,2) NOT NULL,
    note character varying(300),
    process character varying(100) NOT NULL,
    work_date date NOT NULL,
    work_time_min integer NOT NULL,
    worker character varying(50),
    work_order_id bigint,
    process_id bigint
);


--
-- Name: work_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: approval_documents approval_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.approval_documents
    ADD CONSTRAINT approval_documents_pkey PRIMARY KEY (id);


--
-- Name: approval_lines approval_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.approval_lines
    ADD CONSTRAINT approval_lines_pkey PRIMARY KEY (id);


--
-- Name: as_requests as_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.as_requests
    ADD CONSTRAINT as_requests_pkey PRIMARY KEY (id);


--
-- Name: attendances attendances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendances
    ADD CONSTRAINT attendances_pkey PRIMARY KEY (id);


--
-- Name: board_posts board_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_posts
    ADD CONSTRAINT board_posts_pkey PRIMARY KEY (id);


--
-- Name: bom_lines bom_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bom_lines
    ADD CONSTRAINT bom_lines_pkey PRIMARY KEY (id);


--
-- Name: boms boms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boms
    ADD CONSTRAINT boms_pkey PRIMARY KEY (id);


--
-- Name: business_partners business_partners_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_partners
    ADD CONSTRAINT business_partners_pkey PRIMARY KEY (id);


--
-- Name: company_info company_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_info
    ADD CONSTRAINT company_info_pkey PRIMARY KEY (id);


--
-- Name: crm_activities crm_activities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crm_activities
    ADD CONSTRAINT crm_activities_pkey PRIMARY KEY (id);


--
-- Name: drive_documents drive_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drive_documents
    ADD CONSTRAINT drive_documents_pkey PRIMARY KEY (id);


--
-- Name: expenses expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);


--
-- Name: item_costs item_costs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_costs
    ADD CONSTRAINT item_costs_pkey PRIMARY KEY (id);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


--
-- Name: lots lots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lots
    ADD CONSTRAINT lots_pkey PRIMARY KEY (id);


--
-- Name: management_items management_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.management_items
    ADD CONSTRAINT management_items_pkey PRIMARY KEY (id);


--
-- Name: material_issues material_issues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT material_issues_pkey PRIMARY KEY (id);


--
-- Name: notices notices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notices
    ADD CONSTRAINT notices_pkey PRIMARY KEY (id);


--
-- Name: order_stages order_stages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_stages
    ADD CONSTRAINT order_stages_pkey PRIMARY KEY (id);


--
-- Name: order_types order_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_types
    ADD CONSTRAINT order_types_pkey PRIMARY KEY (id);


--
-- Name: preference preference_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preference
    ADD CONSTRAINT preference_pkey PRIMARY KEY (id);


--
-- Name: price_order_settings price_order_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.price_order_settings
    ADD CONSTRAINT price_order_settings_pkey PRIMARY KEY (id);


--
-- Name: production_materials production_materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_materials
    ADD CONSTRAINT production_materials_pkey PRIMARY KEY (id);


--
-- Name: production_plans production_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_plans
    ADD CONSTRAINT production_plans_pkey PRIMARY KEY (id);


--
-- Name: production_processes production_processes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_processes
    ADD CONSTRAINT production_processes_pkey PRIMARY KEY (id);


--
-- Name: production_resources production_resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_resources
    ADD CONSTRAINT production_resources_pkey PRIMARY KEY (id);


--
-- Name: productions productions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions
    ADD CONSTRAINT productions_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: purchase_lines purchase_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_lines
    ADD CONSTRAINT purchase_lines_pkey PRIMARY KEY (id);


--
-- Name: purchases purchases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_pkey PRIMARY KEY (id);


--
-- Name: quality_inspections quality_inspections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_inspections
    ADD CONSTRAINT quality_inspections_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sales_lines sales_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_lines
    ADD CONSTRAINT sales_lines_pkey PRIMARY KEY (id);


--
-- Name: sales_order_lines sales_order_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_order_lines
    ADD CONSTRAINT sales_order_lines_pkey PRIMARY KEY (id);


--
-- Name: sales_orders sales_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_orders
    ADD CONSTRAINT sales_orders_pkey PRIMARY KEY (id);


--
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (id);


--
-- Name: schedule_events schedule_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_events
    ADD CONSTRAINT schedule_events_pkey PRIMARY KEY (id);


--
-- Name: security_policy security_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.security_policy
    ADD CONSTRAINT security_policy_pkey PRIMARY KEY (id);


--
-- Name: settlements settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_pkey PRIMARY KEY (id);


--
-- Name: shipment_lines shipment_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_lines
    ADD CONSTRAINT shipment_lines_pkey PRIMARY KEY (id);


--
-- Name: shipments shipments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT shipments_pkey PRIMARY KEY (id);


--
-- Name: stock_lots stock_lots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_lots
    ADD CONSTRAINT stock_lots_pkey PRIMARY KEY (id);


--
-- Name: stock_transactions stock_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transactions
    ADD CONSTRAINT stock_transactions_pkey PRIMARY KEY (id);


--
-- Name: stock_transfers stock_transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT stock_transfers_pkey PRIMARY KEY (id);


--
-- Name: stocks stocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stocks
    ADD CONSTRAINT stocks_pkey PRIMARY KEY (id);


--
-- Name: supply_items supply_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_items
    ADD CONSTRAINT supply_items_pkey PRIMARY KEY (id);


--
-- Name: surveys surveys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.surveys
    ADD CONSTRAINT surveys_pkey PRIMARY KEY (id);


--
-- Name: lots uk193fo5mmxkinvcntwj26ptorw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lots
    ADD CONSTRAINT uk193fo5mmxkinvcntwj26ptorw UNIQUE (lot_no);


--
-- Name: order_types uk3txtgoccj49o6ufyrm1ppf8lt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_types
    ADD CONSTRAINT uk3txtgoccj49o6ufyrm1ppf8lt UNIQUE (code);


--
-- Name: quality_inspections uk5s1sfad1bkw6b908k9ogw07tk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_inspections
    ADD CONSTRAINT uk5s1sfad1bkw6b908k9ogw07tk UNIQUE (inspection_no);


--
-- Name: warehouses uk6herdbg4x5wp6gkor8epv73oc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT uk6herdbg4x5wp6gkor8epv73oc UNIQUE (code);


--
-- Name: shipments uk6ncbhxkd826htson176wgwmn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT uk6ncbhxkd826htson176wgwmn UNIQUE (ship_no);


--
-- Name: management_items uk7kw720oyqjqgb10txj4y8hrfh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.management_items
    ADD CONSTRAINT uk7kw720oyqjqgb10txj4y8hrfh UNIQUE (code);


--
-- Name: items uk9obt5anl2008e5xmt7r1cuwf2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT uk9obt5anl2008e5xmt7r1cuwf2 UNIQUE (code);


--
-- Name: attendances uk_attendance_user_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendances
    ADD CONSTRAINT uk_attendance_user_date UNIQUE (user_id, work_date);


--
-- Name: item_costs uk_item_cost_item_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_costs
    ADD CONSTRAINT uk_item_cost_item_period UNIQUE (item_id, period);


--
-- Name: price_order_settings uk_price_order_cat_fn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.price_order_settings
    ADD CONSTRAINT uk_price_order_cat_fn UNIQUE (category, function_name);


--
-- Name: stocks uk_stock_item_warehouse; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stocks
    ADD CONSTRAINT uk_stock_item_warehouse UNIQUE (item_id, warehouse_id);


--
-- Name: productions ukappdu5d6w6ix2ragqkhgdxumr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions
    ADD CONSTRAINT ukappdu5d6w6ix2ragqkhgdxumr UNIQUE (prod_no);


--
-- Name: sales_orders ukb2jla71nqwpayyxw8mfdpba7l; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_orders
    ADD CONSTRAINT ukb2jla71nqwpayyxw8mfdpba7l UNIQUE (order_no);


--
-- Name: projects ukclujw4wu21d33ssgde022aymk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT ukclujw4wu21d33ssgde022aymk UNIQUE (code);


--
-- Name: approval_documents ukctaooocqqjxcn5rplbtlwcioc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.approval_documents
    ADD CONSTRAINT ukctaooocqqjxcn5rplbtlwcioc UNIQUE (doc_no);


--
-- Name: stock_transfers ukds2ppmw92ulvs2emeulb9ijiy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT ukds2ppmw92ulvs2emeulb9ijiy UNIQUE (transfer_no);


--
-- Name: business_partners ukhcfem16q9637ob97oevk6ssy1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_partners
    ADD CONSTRAINT ukhcfem16q9637ob97oevk6ssy1 UNIQUE (code);


--
-- Name: production_processes uki5r39v9j5c6qdglek6rfmy3us; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_processes
    ADD CONSTRAINT uki5r39v9j5c6qdglek6rfmy3us UNIQUE (code);


--
-- Name: stock_lots ukkvcbf28g0so7klycc8949tce7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_lots
    ADD CONSTRAINT ukkvcbf28g0so7klycc8949tce7 UNIQUE (lot_no);


--
-- Name: as_requests ukmmqq7r6a9tj3s9qy25p88j54e; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.as_requests
    ADD CONSTRAINT ukmmqq7r6a9tj3s9qy25p88j54e UNIQUE (as_no);


--
-- Name: order_stages uko55d0f5nt0411kxoad212b84q; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_stages
    ADD CONSTRAINT uko55d0f5nt0411kxoad212b84q UNIQUE (code);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: accounts ukp2jd4db8821l8voctujboa9oh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT ukp2jd4db8821l8voctujboa9oh UNIQUE (code);


--
-- Name: sales ukpaa94en9qoj1yjbc1hkv9gwjr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT ukpaa94en9qoj1yjbc1hkv9gwjr UNIQUE (doc_no);


--
-- Name: production_resources ukqurym5vvhi1ucfdv8ttnsv59e; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_resources
    ADD CONSTRAINT ukqurym5vvhi1ucfdv8ttnsv59e UNIQUE (code);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: purchases ukr75c9vbskspyihafrrif246dt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT ukr75c9vbskspyihafrrif246dt UNIQUE (doc_no);


--
-- Name: settlements ukrcni13u7q2y9l7iftiq0uw2as; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT ukrcni13u7q2y9l7iftiq0uw2as UNIQUE (doc_no);


--
-- Name: supply_items uks3ad1rgn68rpmkchy92h2fafd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supply_items
    ADD CONSTRAINT uks3ad1rgn68rpmkchy92h2fafd UNIQUE (code);


--
-- Name: work_orders ukskpy6yy9qmln30vbmgwvfvhjj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_orders
    ADD CONSTRAINT ukskpy6yy9qmln30vbmgwvfvhjj UNIQUE (order_no);


--
-- Name: boms uksqyw1w2qecwb6u6glwom2xtix; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boms
    ADD CONSTRAINT uksqyw1w2qecwb6u6glwom2xtix UNIQUE (product_id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vacation_requests vacation_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vacation_requests
    ADD CONSTRAINT vacation_requests_pkey PRIMARY KEY (id);


--
-- Name: warehouses warehouses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT warehouses_pkey PRIMARY KEY (id);


--
-- Name: work_journals work_journals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_journals
    ADD CONSTRAINT work_journals_pkey PRIMARY KEY (id);


--
-- Name: work_orders work_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_orders
    ADD CONSTRAINT work_orders_pkey PRIMARY KEY (id);


--
-- Name: work_posts work_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_posts
    ADD CONSTRAINT work_posts_pkey PRIMARY KEY (id);


--
-- Name: work_results work_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_results
    ADD CONSTRAINT work_results_pkey PRIMARY KEY (id);


--
-- Name: lots fk19c819or9vx21l3igbg098vd2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lots
    ADD CONSTRAINT fk19c819or9vx21l3igbg098vd2 FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: stock_transfers fk1a7ck2ceraf7yvx8oyalg6qcl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT fk1a7ck2ceraf7yvx8oyalg6qcl FOREIGN KEY (from_warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: material_issues fk1cp2fpm926cw5u0wwxx83abde; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT fk1cp2fpm926cw5u0wwxx83abde FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: stock_lots fk1rjnjssfl2bu5p3p6jcq77762; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_lots
    ADD CONSTRAINT fk1rjnjssfl2bu5p3p6jcq77762 FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: productions fk27f57ikxrn6ge3vrpn3t4huve; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions
    ADD CONSTRAINT fk27f57ikxrn6ge3vrpn3t4huve FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: sales fk29jrcla39okwm8x58vvw1apgi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fk29jrcla39okwm8x58vvw1apgi FOREIGN KEY (partner_id) REFERENCES public.business_partners(id);


--
-- Name: quality_inspections fk3fb4blp0mv2qt7f1plyc3i4ko; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_inspections
    ADD CONSTRAINT fk3fb4blp0mv2qt7f1plyc3i4ko FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: sales_orders fk40fqivw6c00exfd77nbipvrwt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_orders
    ADD CONSTRAINT fk40fqivw6c00exfd77nbipvrwt FOREIGN KEY (partner_id) REFERENCES public.business_partners(id);


--
-- Name: stock_lots fk5agpdq0jrptdkbvenr5cqsmri; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_lots
    ADD CONSTRAINT fk5agpdq0jrptdkbvenr5cqsmri FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: purchase_lines fk6g7pnc6oq338s465fh8ym425w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_lines
    ADD CONSTRAINT fk6g7pnc6oq338s465fh8ym425w FOREIGN KEY (purchase_id) REFERENCES public.purchases(id);


--
-- Name: stock_transactions fk7fugsbc704m7063vy0q3851ma; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transactions
    ADD CONSTRAINT fk7fugsbc704m7063vy0q3851ma FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: bom_lines fk7ylnsr161otgvnj8wtj80am4a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bom_lines
    ADD CONSTRAINT fk7ylnsr161otgvnj8wtj80am4a FOREIGN KEY (bom_id) REFERENCES public.boms(id);


--
-- Name: vacation_requests fk8llp5g8rr5yow78xeutr4xkmi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vacation_requests
    ADD CONSTRAINT fk8llp5g8rr5yow78xeutr4xkmi FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: attendances fk8o39cn3ghqwhccyrrqdesttr8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendances
    ADD CONSTRAINT fk8o39cn3ghqwhccyrrqdesttr8 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: work_journals fk9o9a5y7fcxa8crl3fgbtls2sq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_journals
    ADD CONSTRAINT fk9o9a5y7fcxa8crl3fgbtls2sq FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: as_requests fkaak7tk9dlh4a2kqyaq6st56se; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.as_requests
    ADD CONSTRAINT fkaak7tk9dlh4a2kqyaq6st56se FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: shipment_lines fkccremitli1lado3t1jmjqgekw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_lines
    ADD CONSTRAINT fkccremitli1lado3t1jmjqgekw FOREIGN KEY (order_line_id) REFERENCES public.sales_order_lines(id);


--
-- Name: stock_transactions fkcr6bbr62ww46o63wgnlw2e8mm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transactions
    ADD CONSTRAINT fkcr6bbr62ww46o63wgnlw2e8mm FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: work_results fkct8xtqlpp32nqv70wsiq7bxcd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_results
    ADD CONSTRAINT fkct8xtqlpp32nqv70wsiq7bxcd FOREIGN KEY (process_id) REFERENCES public.production_processes(id);


--
-- Name: stock_transfers fkd4ah1vrc1kdhg31qig9p8tv0y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT fkd4ah1vrc1kdhg31qig9p8tv0y FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: purchases fkdrigh2vcwq17ifewt5pfd4tw8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT fkdrigh2vcwq17ifewt5pfd4tw8 FOREIGN KEY (partner_id) REFERENCES public.business_partners(id);


--
-- Name: settlements fke1ta4q8yukwb4ntgulvvcb323; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT fke1ta4q8yukwb4ntgulvvcb323 FOREIGN KEY (partner_id) REFERENCES public.business_partners(id);


--
-- Name: shipments fke6lvrfx7xcd5lwxs3ewq042e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT fke6lvrfx7xcd5lwxs3ewq042e FOREIGN KEY (partner_id) REFERENCES public.business_partners(id);


--
-- Name: approval_lines fkf4nt5is331ydehbbjpjd5odt7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.approval_lines
    ADD CONSTRAINT fkf4nt5is331ydehbbjpjd5odt7 FOREIGN KEY (approver_id) REFERENCES public.users(id);


--
-- Name: production_materials fkfb6s495gwnmbeh9suidrt92ra; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_materials
    ADD CONSTRAINT fkfb6s495gwnmbeh9suidrt92ra FOREIGN KEY (production_id) REFERENCES public.productions(id);


--
-- Name: boms fkfosp3uuana5dwbhni8sbswh9l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boms
    ADD CONSTRAINT fkfosp3uuana5dwbhni8sbswh9l FOREIGN KEY (product_id) REFERENCES public.items(id);


--
-- Name: bom_lines fkg3cj7alsyy8pqycw2uyig5sxo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bom_lines
    ADD CONSTRAINT fkg3cj7alsyy8pqycw2uyig5sxo FOREIGN KEY (component_id) REFERENCES public.items(id);


--
-- Name: production_plans fkgatak7dyfk9fgif08ivh83tdg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_plans
    ADD CONSTRAINT fkgatak7dyfk9fgif08ivh83tdg FOREIGN KEY (product_id) REFERENCES public.items(id);


--
-- Name: lots fkgjsli6smvf4owuejrx8fvd1n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lots
    ADD CONSTRAINT fkgjsli6smvf4owuejrx8fvd1n FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: sales fkhf9hp5u4um5na1qrld83f70l2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fkhf9hp5u4um5na1qrld83f70l2 FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: work_results fkholgo5tn15xa93l8e1jyj0kgq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_results
    ADD CONSTRAINT fkholgo5tn15xa93l8e1jyj0kgq FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id);


--
-- Name: work_orders fkhw9f1hopb9uau893m38eocul; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_orders
    ADD CONSTRAINT fkhw9f1hopb9uau893m38eocul FOREIGN KEY (product_id) REFERENCES public.items(id);


--
-- Name: production_plans fki1q8yhhy5e1m1j4rh68uvm637; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_plans
    ADD CONSTRAINT fki1q8yhhy5e1m1j4rh68uvm637 FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id);


--
-- Name: sales_order_lines fkii204k50cu9hp423ni6d430ny; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_order_lines
    ADD CONSTRAINT fkii204k50cu9hp423ni6d430ny FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: shipment_lines fkis8wn79b70g66a38lydvhke43; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_lines
    ADD CONSTRAINT fkis8wn79b70g66a38lydvhke43 FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: material_issues fkitesq7sf9se38wmjn5r2pn95x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT fkitesq7sf9se38wmjn5r2pn95x FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id);


--
-- Name: item_costs fkj6757tbu2vtv0yahp5yunktb1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_costs
    ADD CONSTRAINT fkj6757tbu2vtv0yahp5yunktb1 FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: stocks fkjftt43i266337pt7y8b291hpx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stocks
    ADD CONSTRAINT fkjftt43i266337pt7y8b291hpx FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: productions fkjrl85u2n491mgjvjj60bfub19; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions
    ADD CONSTRAINT fkjrl85u2n491mgjvjj60bfub19 FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id);


--
-- Name: stocks fkko9qvmybxt0opqoibsqrmivh8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stocks
    ADD CONSTRAINT fkko9qvmybxt0opqoibsqrmivh8 FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: sales_lines fkllw8orsust1ke1yc6887306sd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_lines
    ADD CONSTRAINT fkllw8orsust1ke1yc6887306sd FOREIGN KEY (sales_id) REFERENCES public.sales(id);


--
-- Name: approval_documents fkn0kcj8ssnsaqo3f3f96v5qtnt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.approval_documents
    ADD CONSTRAINT fkn0kcj8ssnsaqo3f3f96v5qtnt FOREIGN KEY (drafter_id) REFERENCES public.users(id);


--
-- Name: expenses fkn24s4d0wvf06dfuslsbcjy8po; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkn24s4d0wvf06dfuslsbcjy8po FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: shipment_lines fkn7b5cxc07ayy3mewq2qi4oxr7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_lines
    ADD CONSTRAINT fkn7b5cxc07ayy3mewq2qi4oxr7 FOREIGN KEY (shipment_id) REFERENCES public.shipments(id);


--
-- Name: purchase_lines fknc9hnpd6u32n2m6djxyygahn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_lines
    ADD CONSTRAINT fknc9hnpd6u32n2m6djxyygahn FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: shipments fknrwqf9e9ljjtln846ygc4drvs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT fknrwqf9e9ljjtln846ygc4drvs FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id);


--
-- Name: work_orders fko2nst4s2h3ll91h760iok30kw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_orders
    ADD CONSTRAINT fko2nst4s2h3ll91h760iok30kw FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: as_requests fko3uu7qk2l319ggp1jnl2s3fxn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.as_requests
    ADD CONSTRAINT fko3uu7qk2l319ggp1jnl2s3fxn FOREIGN KEY (partner_id) REFERENCES public.business_partners(id);


--
-- Name: purchases fko5ayqstf3r4ec39aykkavuscp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT fko5ayqstf3r4ec39aykkavuscp FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: sales_lines fkqgnva633uxrdpb07rtbfj0kd5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_lines
    ADD CONSTRAINT fkqgnva633uxrdpb07rtbfj0kd5 FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: approval_lines fkr8y4bmfkj0hiilxqyob2rd7oh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.approval_lines
    ADD CONSTRAINT fkr8y4bmfkj0hiilxqyob2rd7oh FOREIGN KEY (document_id) REFERENCES public.approval_documents(id);


--
-- Name: production_materials fkrivw6cwql3g19cejvgmhxomd3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_materials
    ADD CONSTRAINT fkrivw6cwql3g19cejvgmhxomd3 FOREIGN KEY (component_id) REFERENCES public.items(id);


--
-- Name: quality_inspections fkrje32wgvu3kydnbyt5dcy5c6t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quality_inspections
    ADD CONSTRAINT fkrje32wgvu3kydnbyt5dcy5c6t FOREIGN KEY (lot_id) REFERENCES public.lots(id);


--
-- Name: crm_activities fkrn9jj3p9jatxdy8hgkw3su79t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crm_activities
    ADD CONSTRAINT fkrn9jj3p9jatxdy8hgkw3su79t FOREIGN KEY (partner_id) REFERENCES public.business_partners(id);


--
-- Name: material_issues fkssp6nilqh9p16bcgcvrhiu9sc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_issues
    ADD CONSTRAINT fkssp6nilqh9p16bcgcvrhiu9sc FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: productions fktc8k3kow477rpd3wmg5rna66p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productions
    ADD CONSTRAINT fktc8k3kow477rpd3wmg5rna66p FOREIGN KEY (product_id) REFERENCES public.items(id);


--
-- Name: stock_transfers fktg575pm9p5bbyj3ki1ssffcpc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_transfers
    ADD CONSTRAINT fktg575pm9p5bbyj3ki1ssffcpc FOREIGN KEY (to_warehouse_id) REFERENCES public.warehouses(id);


--
-- Name: sales_order_lines fktgqomomuqhk8i92lc9hjr7j71; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_order_lines
    ADD CONSTRAINT fktgqomomuqhk8i92lc9hjr7j71 FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id);


--
-- PostgreSQL database dump complete
--


