-- V20: 견적서 — 영업 흐름의 시작점(견적 → 주문 → 판매 → 수금)
--
-- 견적서를 작성/발송하고, 고객이 수락하면 수주(sales_orders)로 전환한다.
-- 전환 시 sales_orders 를 생성하고 converted_order_id 로 연결한다.

CREATE TABLE public.quotations (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        timestamp(6) without time zone,
    updated_at        timestamp(6) without time zone,
    quote_no          character varying(30)  NOT NULL,
    quote_date        date NOT NULL,
    valid_until       date,
    partner_id        bigint NOT NULL,
    -- 작성(DRAFT) → 발송(SENT) → 수주전환(CONVERTED) / 취소(CANCELLED)
    status            character varying(20) NOT NULL DEFAULT 'DRAFT',
    supply_amount     numeric(18,2) NOT NULL DEFAULT 0,
    vat_amount        numeric(18,2) NOT NULL DEFAULT 0,
    total_amount      numeric(18,2) NOT NULL DEFAULT 0,
    -- 수주 전환 시 생성된 sales_orders.id
    converted_order_id bigint,
    remark            character varying(500),
    created_by        character varying(50),
    CONSTRAINT uk_quotations_quote_no UNIQUE (quote_no),
    CONSTRAINT fk_quotations_partner_id FOREIGN KEY (partner_id) REFERENCES public.business_partners(id),
    CONSTRAINT fk_quotations_converted_order_id FOREIGN KEY (converted_order_id) REFERENCES public.sales_orders(id),
    CONSTRAINT ck_quotations_status CHECK (status IN ('DRAFT', 'SENT', 'CONVERTED', 'CANCELLED'))
);
CREATE INDEX idx_quotations_quote_date ON public.quotations (quote_date);
CREATE INDEX idx_quotations_partner_id ON public.quotations (partner_id);
CREATE INDEX idx_quotations_status     ON public.quotations (status);
CREATE INDEX idx_quotations_converted_order_id ON public.quotations (converted_order_id);

CREATE TABLE public.quotation_lines (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id   bigint NOT NULL,
    item_id        bigint NOT NULL,
    quantity       numeric(18,2) NOT NULL,
    unit_price     numeric(18,2) NOT NULL,
    supply_amount  numeric(18,2) NOT NULL DEFAULT 0,
    vat_amount     numeric(18,2) NOT NULL DEFAULT 0,
    line_no        integer NOT NULL DEFAULT 1,
    CONSTRAINT fk_quotation_lines_quotation_id FOREIGN KEY (quotation_id)
        REFERENCES public.quotations(id) ON DELETE CASCADE,
    CONSTRAINT fk_quotation_lines_item_id FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE INDEX idx_quotation_lines_quotation_id ON public.quotation_lines (quotation_id);
CREATE INDEX idx_quotation_lines_item_id      ON public.quotation_lines (item_id);
