-- V21: 발주서 — 구매 흐름의 시작점(발주요청 → 발주계획 → 단가확정 → 발주확정 → 구매입고)
--
-- 발주 단계에서는 재고를 건드리지 않는다. 물품이 도착해 구매전표(purchases)로 전환될 때
-- 비로소 입고가 잡히고, converted_purchase_id 로 연결된다.
-- 발주번호는 PR- 접두어를 쓴다 (구매전표 doc_no 의 PO- 와 구분).

CREATE TABLE public.purchase_orders (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            timestamp(6) without time zone,
    updated_at            timestamp(6) without time zone,
    order_no              character varying(30) NOT NULL,
    order_date            date NOT NULL,
    due_date              date,
    partner_id            bigint NOT NULL,
    status                character varying(20) NOT NULL DEFAULT 'REQUESTED',
    supply_amount         numeric(18,2) NOT NULL DEFAULT 0,
    vat_amount            numeric(18,2) NOT NULL DEFAULT 0,
    total_amount          numeric(18,2) NOT NULL DEFAULT 0,
    taxable               boolean NOT NULL DEFAULT true,
    -- 입고 전환 시 생성된 purchases.id
    converted_purchase_id bigint,
    remark                character varying(500),
    created_by            character varying(50),
    CONSTRAINT uk_purchase_orders_order_no UNIQUE (order_no),
    CONSTRAINT fk_purchase_orders_partner_id FOREIGN KEY (partner_id) REFERENCES public.business_partners(id),
    CONSTRAINT fk_purchase_orders_converted_purchase_id FOREIGN KEY (converted_purchase_id) REFERENCES public.purchases(id),
    CONSTRAINT ck_purchase_orders_status CHECK (status IN ('REQUESTED', 'PLANNED', 'PRICED', 'ORDERED', 'RECEIVED', 'CANCELLED'))
);
CREATE INDEX idx_purchase_orders_order_date ON public.purchase_orders (order_date);
CREATE INDEX idx_purchase_orders_partner_id ON public.purchase_orders (partner_id);
CREATE INDEX idx_purchase_orders_status     ON public.purchase_orders (status);
CREATE INDEX idx_purchase_orders_converted_purchase_id ON public.purchase_orders (converted_purchase_id);

CREATE TABLE public.purchase_order_lines (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id bigint NOT NULL,
    item_id           bigint NOT NULL,
    quantity          numeric(18,2) NOT NULL,
    -- 발주요청 시점에는 단가 미정(0)일 수 있다. 단가확정 단계에서 채운다.
    unit_price        numeric(18,2) NOT NULL DEFAULT 0,
    supply_amount     numeric(18,2) NOT NULL DEFAULT 0,
    vat_amount        numeric(18,2) NOT NULL DEFAULT 0,
    line_no           integer NOT NULL DEFAULT 1,
    CONSTRAINT fk_purchase_order_lines_purchase_order_id FOREIGN KEY (purchase_order_id)
        REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_order_lines_item_id FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE INDEX idx_purchase_order_lines_purchase_order_id ON public.purchase_order_lines (purchase_order_id);
CREATE INDEX idx_purchase_order_lines_item_id           ON public.purchase_order_lines (item_id);
