-- V25: 기타이동 — 자가사용·불량처리·재고조정
--
-- 창고이동(stock_transfers)과 달리 재고가 한쪽으로만 움직인다.
--   자가사용/불량처리: 입력 수량만큼 차감 (quantity_change < 0)
--   재고조정        : 실사수량 - 현재고 만큼 증감 (quantity_change 부호 자유)
-- 실제 잔량 증감과 수불 이력은 stock / stock_transactions 가 담당하고,
-- 이 테이블은 "무슨 사유로 얼마를 움직였는지" 전표만 남긴다.
--
-- 번호 주의: V21~V24 는 진행 중인 구매 발주 작업이 쓸 수 있도록 비워 두었다.

CREATE TABLE public.stock_adjustments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp(6) without time zone,
    updated_at      timestamp(6) without time zone,
    adjust_no       character varying(30) NOT NULL,
    adjust_date     date NOT NULL,
    type            character varying(20) NOT NULL,
    item_id         bigint NOT NULL,
    warehouse_id    bigint NOT NULL,
    before_qty      numeric(18,2) NOT NULL,
    quantity_change numeric(18,2) NOT NULL,
    after_qty       numeric(18,2) NOT NULL,
    reason          character varying(300),
    created_by      character varying(50),
    CONSTRAINT uk_stock_adjustments_adjust_no UNIQUE (adjust_no),
    CONSTRAINT fk_stock_adjustments_item_id FOREIGN KEY (item_id) REFERENCES public.items(id),
    CONSTRAINT fk_stock_adjustments_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
    CONSTRAINT ck_stock_adjustments_type CHECK (type IN ('SELF_USE', 'DEFECT', 'ADJUST'))
);
CREATE INDEX idx_stock_adjustments_item_id      ON public.stock_adjustments (item_id);
CREATE INDEX idx_stock_adjustments_warehouse_id ON public.stock_adjustments (warehouse_id);
CREATE INDEX idx_stock_adjustments_adjust_date  ON public.stock_adjustments (adjust_date);
CREATE INDEX idx_stock_adjustments_type         ON public.stock_adjustments (type);
