-- 게시판 글을 누가 언제 읽었나(원본 공지사항 E200080 [조회] 'R' → '조회자 현황', 2026-10-03 실측).
--
-- 원본 [조회] 칸은 숫자가 아니라 'R' 링크이고, 누르면 '조회자 현황' 창이 뜬다 — 왼쪽 미조회자 이름,
-- 오른쪽 조회자 [이름][최초조회일시][최종조회일시]. 우리는 연 횟수(view_count) 하나만 세고 있었다.
-- 사람마다 한 줄, 처음 · 마지막으로 연 때를 둔다. 글을 지우면 같이 지운다.
CREATE TABLE work_post_reads (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       bigint NOT NULL REFERENCES work_posts (id) ON DELETE CASCADE,
    user_id       bigint NOT NULL REFERENCES users (id),
    first_read_at timestamp(6) without time zone NOT NULL,
    last_read_at  timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_work_post_reads_post_user UNIQUE (post_id, user_id)
);
CREATE INDEX idx_work_post_reads_user_id ON work_post_reads (user_id);
