-- 사원별휴가일수조회(원본 E020703): 휴가항목마다 사원의 이월 잔여일수 · 당해년 휴가일수.
CREATE TABLE public.vacation_grants (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacation_kind_id bigint       NOT NULL,
    employee_id      bigint       NOT NULL,
    carry_over_days  numeric(6,2) NOT NULL DEFAULT 0,
    current_days     numeric(6,2) NOT NULL DEFAULT 0,
    CONSTRAINT uk_vacation_grants_kind_employee UNIQUE (vacation_kind_id, employee_id),
    CONSTRAINT fk_vacation_grants_vacation_kind_id FOREIGN KEY (vacation_kind_id) REFERENCES public.vacation_kinds(id),
    CONSTRAINT fk_vacation_grants_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE INDEX idx_vacation_grants_vacation_kind_id ON public.vacation_grants (vacation_kind_id);
CREATE INDEX idx_vacation_grants_employee_id ON public.vacation_grants (employee_id);
