-- 출/퇴근반영기준(원본 E020725): 출퇴근 기록을 근태로 옮길 때의 규칙(반영방식 · 적용기준 · 최소시간 · 제외시간 셋).
CREATE TABLE public.commute_rules (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone,
    code         varchar(20)  NOT NULL,
    name         varchar(50)  NOT NULL,
    hour_unit    boolean      NOT NULL DEFAULT false,
    method       varchar(20)  NOT NULL,
    direct_basis boolean      NOT NULL DEFAULT false,
    min_hours    integer,
    min_minutes  integer,
    ex1_from     varchar(8),
    ex1_to       varchar(8),
    ex2_from     varchar(8),
    ex2_to       varchar(8),
    ex3_from     varchar(8),
    ex3_to       varchar(8),
    remark       varchar(500),
    active       boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_commute_rules_code UNIQUE (code),
    CONSTRAINT ck_commute_rules_method CHECK (method IN ('WORK_TIME', 'LATE', 'EARLY_LEAVE', 'FORMULA'))
);
