-- V26: 계좌/카드 (회계 I 4-5)
--
-- 계좌·카드 마스터를 두고, 계좌 입출금과 카드사용을 전표로 남긴다.
-- 두 전표 모두 저장과 동시에 복식부기 분개를 만든다:
--   계좌입금  차)예금계정 / 대)상대계정        계좌출금  차)상대계정 / 대)예금계정
--   카드사용  차)비용계정·부가세대급금 / 대)미지급금
-- 그래서 journal_entries.source_type 에 BANK·CARD 를 추가한다.

ALTER TABLE public.journal_entries DROP CONSTRAINT ck_journal_entries_source_type;
ALTER TABLE public.journal_entries ADD CONSTRAINT ck_journal_entries_source_type
    CHECK (source_type IN ('SALES', 'PURCHASE', 'EXPENSE', 'BANK', 'CARD', 'MANUAL'));

CREATE TABLE public.bank_accounts (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone,
    bank_name     character varying(50) NOT NULL,
    account_no    character varying(50) NOT NULL,
    holder        character varying(50),
    -- 이 계좌가 분개될 때 쓰는 계정과목(보통예금 103 등)
    gl_account_id bigint NOT NULL,
    balance       numeric(18,2) NOT NULL DEFAULT 0,
    active        boolean NOT NULL DEFAULT true,
    remark        character varying(200),
    CONSTRAINT uk_bank_accounts_account_no UNIQUE (account_no),
    CONSTRAINT fk_bank_accounts_gl_account_id FOREIGN KEY (gl_account_id) REFERENCES public.accounts(id)
);
CREATE INDEX idx_bank_accounts_gl_account_id ON public.bank_accounts (gl_account_id);

CREATE TABLE public.credit_cards (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            timestamp(6) without time zone,
    updated_at            timestamp(6) without time zone,
    card_name             character varying(50) NOT NULL,
    card_company          character varying(50) NOT NULL,
    card_no               character varying(30) NOT NULL,
    type                  character varying(20) NOT NULL,
    owner_name            character varying(50),
    -- 카드대금이 빠져나가는 계좌
    settlement_account_id bigint,
    settlement_day        integer,
    active                boolean NOT NULL DEFAULT true,
    remark                character varying(200),
    CONSTRAINT uk_credit_cards_card_no UNIQUE (card_no),
    CONSTRAINT fk_credit_cards_settlement_account_id FOREIGN KEY (settlement_account_id)
        REFERENCES public.bank_accounts(id),
    CONSTRAINT ck_credit_cards_type CHECK (type IN ('CORPORATE', 'PERSONAL'))
);
CREATE INDEX idx_credit_cards_settlement_account_id ON public.credit_cards (settlement_account_id);

CREATE TABLE public.bank_transactions (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        timestamp(6) without time zone,
    updated_at        timestamp(6) without time zone,
    txn_no            character varying(30) NOT NULL,
    txn_date          date NOT NULL,
    bank_account_id   bigint NOT NULL,
    deposit           boolean NOT NULL,
    amount            numeric(18,2) NOT NULL,
    counter_account_id bigint NOT NULL,
    partner_id        bigint,
    balance_after     numeric(18,2) NOT NULL,
    journal_entry_id  bigint,
    description       character varying(200),
    created_by        character varying(50),
    CONSTRAINT uk_bank_transactions_txn_no UNIQUE (txn_no),
    CONSTRAINT fk_bank_transactions_bank_account_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
    CONSTRAINT fk_bank_transactions_counter_account_id FOREIGN KEY (counter_account_id) REFERENCES public.accounts(id),
    CONSTRAINT fk_bank_transactions_partner_id FOREIGN KEY (partner_id) REFERENCES public.business_partners(id),
    CONSTRAINT fk_bank_transactions_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id)
);
CREATE INDEX idx_bank_transactions_bank_account_id    ON public.bank_transactions (bank_account_id);
CREATE INDEX idx_bank_transactions_counter_account_id ON public.bank_transactions (counter_account_id);
CREATE INDEX idx_bank_transactions_partner_id         ON public.bank_transactions (partner_id);
CREATE INDEX idx_bank_transactions_journal_entry_id   ON public.bank_transactions (journal_entry_id);
CREATE INDEX idx_bank_transactions_txn_date           ON public.bank_transactions (txn_date);

CREATE TABLE public.card_usages (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         timestamp(6) without time zone,
    updated_at         timestamp(6) without time zone,
    usage_no           character varying(30) NOT NULL,
    usage_date         date NOT NULL,
    card_id            bigint NOT NULL,
    merchant           character varying(100) NOT NULL,
    expense_account_id bigint NOT NULL,
    supply_amount      numeric(18,2) NOT NULL DEFAULT 0,
    vat_amount         numeric(18,2) NOT NULL DEFAULT 0,
    total_amount       numeric(18,2) NOT NULL DEFAULT 0,
    journal_entry_id   bigint,
    description        character varying(200),
    created_by         character varying(50),
    CONSTRAINT uk_card_usages_usage_no UNIQUE (usage_no),
    CONSTRAINT fk_card_usages_card_id FOREIGN KEY (card_id) REFERENCES public.credit_cards(id),
    CONSTRAINT fk_card_usages_expense_account_id FOREIGN KEY (expense_account_id) REFERENCES public.accounts(id),
    CONSTRAINT fk_card_usages_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id)
);
CREATE INDEX idx_card_usages_card_id            ON public.card_usages (card_id);
CREATE INDEX idx_card_usages_expense_account_id ON public.card_usages (expense_account_id);
CREATE INDEX idx_card_usages_journal_entry_id   ON public.card_usages (journal_entry_id);
CREATE INDEX idx_card_usages_usage_date         ON public.card_usages (usage_date);
