-- 출/퇴근기록부(사원)(원본 E020726): 사원 단위 출퇴근(로그인 계정과 무관). 사원 · 일자마다 한 줄.
CREATE TABLE public.employee_commutes (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone,
    employee_id  bigint       NOT NULL,
    work_date    date         NOT NULL,
    clock_in     timestamp(6) without time zone NOT NULL,
    clock_out    timestamp(6) without time zone,
    place        varchar(50),
    outside      boolean      NOT NULL DEFAULT false,
    morning_half boolean      NOT NULL DEFAULT false,
    reason       varchar(200),
    CONSTRAINT uk_employee_commutes_employee_date UNIQUE (employee_id, work_date),
    CONSTRAINT fk_employee_commutes_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE INDEX idx_employee_commutes_work_date ON public.employee_commutes (work_date);
