-- MyPage 나만의 업무 폴더.
--
-- 원본 MyPage 는 업무 폴더가 2단 메뉴다 — [나만의 업무 폴더] 와 업종 예시 넷. 폴더를 고르면 그 안에 담은
-- 화면들이 왼쪽 메뉴로 펼쳐지고 첫 화면이 열린다. 원본처럼 메뉴명도 고칠 수 있어 이름을 경로와 따로 든다.
-- 사람마다 매일 여는 화면이 달라서 사용자별(auth)이다 — 북마크(user_bookmarks)와 같은 까닭.

CREATE TABLE user_menu_folders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name        varchar(100) NOT NULL,
    sort_order  integer      NOT NULL DEFAULT 0,
    created_at  timestamp,
    updated_at  timestamp
);

CREATE TABLE user_menu_folder_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id   bigint       NOT NULL REFERENCES user_menu_folders (id) ON DELETE CASCADE,
    label       varchar(100) NOT NULL,
    path        varchar(200) NOT NULL,
    sort_order  integer      NOT NULL DEFAULT 0,
    created_at  timestamp,
    updated_at  timestamp,
    CONSTRAINT uk_user_menu_folder_items_folder_path UNIQUE (folder_id, path)
);

-- PostgreSQL 은 FOREIGN KEY 를 만들어도 참조하는 쪽 컬럼에 인덱스를 안 만든다.
CREATE INDEX idx_user_menu_folders_user ON user_menu_folders (user_id);
CREATE INDEX idx_user_menu_folder_items_folder ON user_menu_folder_items (folder_id);
