-- 근태그룹(원본 근태항목등록의 [근태그룹] 코드도움 · 근태그룹등록 창) — 근태그룹 코드 · 근태그룹 명.
-- 근태항목은 고른 근태그룹 명을 kind_group 에 담는다.
CREATE TABLE public.attendance_kind_groups (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    code        varchar(20)  NOT NULL,
    name        varchar(50)  NOT NULL,
    CONSTRAINT uk_attendance_kind_groups_code UNIQUE (code)
);
