-- 법인세Checklist(E030401)의 [메모등록].
--
-- 원본은 항목(1. 부가세신고서 내역 … 15. 감면세액 확인)마다 [메모등록]이 있고, 누르면 그 항목의 메모리스트
-- [날짜 · 제목 · 작성자] 가 뜬다. 메모는 날짜 · 제목 · 메모(셋 다 필수)이고, 기준연도마다 따로다(2026-10-04 실측).
CREATE TABLE corporate_tax_check_memos (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_year   integer      NOT NULL,
    section_no  integer      NOT NULL,
    memo_date   date         NOT NULL,
    title       varchar(200) NOT NULL,
    content     text         NOT NULL,
    writer      varchar(100),
    created_at  timestamp,
    updated_at  timestamp
);
CREATE INDEX idx_corporate_tax_check_memos_year_section ON corporate_tax_check_memos (base_year, section_no);
