-- V26: 부서(departments) 마스터 신설 + employees.department 문자열 → FK 전환
--
-- 배경: employees.department 가 varchar 자유입력이라 부서 단위 집계·조직도가 불가능했다.
--       (오타 한 글자면 다른 부서가 된다.) 부서를 마스터로 올리고 사원을 FK 로 붙인다.
--
-- parent_id 로 상위 부서를 가리켜 조직도 트리를 만든다. 최상위 부서는 parent_id 가 NULL.

CREATE TABLE public.departments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    code        varchar(50)  NOT NULL,
    name        varchar(100) NOT NULL,
    -- 상위 부서. 자기참조 → 조직도 트리
    parent_id   bigint,
    -- 같은 depth 안에서의 표시 순서
    sort_order  integer      NOT NULL DEFAULT 0,
    active      boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_departments_code UNIQUE (code),
    CONSTRAINT fk_departments_parent_id FOREIGN KEY (parent_id) REFERENCES public.departments(id)
);
CREATE INDEX idx_departments_parent_id ON public.departments (parent_id);

-- 기존 employees.department 에 들어있던 문자열을 부서 마스터로 승격한다.
-- 코드는 없으므로 이름으로부터 임시 코드(DEPT-0001…)를 붙인다.
INSERT INTO public.departments (code, name, sort_order, active)
SELECT 'DEPT-' || lpad((row_number() OVER (ORDER BY d.department))::text, 4, '0'),
       d.department, 0, true
FROM (SELECT DISTINCT department FROM public.employees WHERE department IS NOT NULL AND department <> '') d;

-- 사원 → 부서 FK. 미배치 사원이 있을 수 있으므로 nullable.
ALTER TABLE public.employees ADD COLUMN department_id bigint;
UPDATE public.employees e
SET department_id = d.id
FROM public.departments d
WHERE e.department = d.name;

ALTER TABLE public.employees
    ADD CONSTRAINT fk_employees_department_id FOREIGN KEY (department_id) REFERENCES public.departments(id);
CREATE INDEX idx_employees_department_id ON public.employees (department_id);

-- 문자열 부서는 더 이상 진실의 출처가 아니다. 두 개를 남기면 반드시 갈라진다.
ALTER TABLE public.employees DROP COLUMN department;
