-- V32: 인사관리 — 발령이력(employee_assignments) + 사원 퇴사일
--
-- 지금까지 사원의 부서·직위는 현재값만 있고 "언제 어떻게 바뀌었는지"가 없었다.
-- 발령을 이력으로 남기고, 발령이 사원의 현재 부서·직위·재직상태를 갱신한다.
-- (현재값은 employees, 변경 내역은 employee_assignments — 둘의 역할이 다르다.)

ALTER TABLE public.employees ADD COLUMN resign_date date;

CREATE TABLE public.employee_assignments (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone,
    employee_id   bigint NOT NULL,
    assign_date   date   NOT NULL,
    -- 입사(HIRE) / 전보(TRANSFER) / 승진(PROMOTION) / 퇴사(RESIGN) / 재입사(REHIRE)
    type          varchar(20) NOT NULL,
    -- 발령 후 부서·직위. 해당 발령에서 바뀌지 않으면 직전 값을 그대로 적는다.
    department_id bigint,
    job_title     varchar(100),
    remark        varchar(500),
    created_by    varchar(50),
    CONSTRAINT fk_employee_assignments_employee_id FOREIGN KEY (employee_id)
        REFERENCES public.employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_employee_assignments_department_id FOREIGN KEY (department_id)
        REFERENCES public.departments(id),
    CONSTRAINT ck_employee_assignments_type
        CHECK (type IN ('HIRE', 'TRANSFER', 'PROMOTION', 'RESIGN', 'REHIRE'))
);
CREATE INDEX idx_employee_assignments_employee_id   ON public.employee_assignments (employee_id);
CREATE INDEX idx_employee_assignments_department_id ON public.employee_assignments (department_id);
CREATE INDEX idx_employee_assignments_assign_date   ON public.employee_assignments (assign_date);

-- 기존 사원의 입사 사실을 이력의 출발점으로 남긴다. 입사일이 없으면 발령이력도 만들지 않는다
-- (없는 날짜를 지어내면 근속일수가 거짓말을 한다).
INSERT INTO public.employee_assignments (employee_id, assign_date, type, department_id, job_title, remark, created_by)
SELECT e.id, e.hire_date, 'HIRE', e.department_id, e.job_title, '기존 사원 입사 이력(마이그레이션 생성)', 'system'
FROM public.employees e
WHERE e.hire_date IS NOT NULL;
