-- V33: 고정자산 (회계 I 4-9)
--
-- 자산을 등록하고 매달 감가상각을 돌려 누계액을 쌓는다. 처분하면 장부에서 털어낸다.
--   감가상각  차)감가상각비 / 대)감가상각누계액
--   처분      차)감가상각누계액·현금(처분가)·처분손실 / 대)자산계정·처분이익
-- 그래서 journal_entries.source_type 에 DEPRECIATION·DISPOSAL 을 추가한다.

ALTER TABLE public.journal_entries DROP CONSTRAINT ck_journal_entries_source_type;
ALTER TABLE public.journal_entries ADD CONSTRAINT ck_journal_entries_source_type
    CHECK (source_type IN ('SALES', 'PURCHASE', 'EXPENSE', 'BANK', 'CARD',
                           'DEPRECIATION', 'DISPOSAL', 'MANUAL'));

CREATE TABLE public.fixed_assets (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                timestamp(6) without time zone,
    updated_at                timestamp(6) without time zone,
    asset_no                  character varying(30) NOT NULL,
    name                      character varying(100) NOT NULL,
    -- 이 자산이 올라가 있는 자산계정(기계장치 206·차량운반구 208·비품 212 등)
    asset_account_id          bigint NOT NULL,
    acquisition_date          date NOT NULL,
    acquisition_cost          numeric(18,2) NOT NULL,
    salvage_value             numeric(18,2) NOT NULL DEFAULT 0,
    useful_life_years         integer NOT NULL,
    method                    character varying(20) NOT NULL,
    -- 정률법 연 상각률(%). 정액법이면 NULL
    decline_rate              numeric(5,2),
    accumulated_depreciation  numeric(18,2) NOT NULL DEFAULT 0,
    status                    character varying(20) NOT NULL DEFAULT 'IN_USE',
    disposal_date             date,
    disposal_amount           numeric(18,2),
    remark                    character varying(200),
    created_by                character varying(50),
    CONSTRAINT uk_fixed_assets_asset_no UNIQUE (asset_no),
    CONSTRAINT fk_fixed_assets_asset_account_id FOREIGN KEY (asset_account_id) REFERENCES public.accounts(id),
    CONSTRAINT ck_fixed_assets_method CHECK (method IN ('STRAIGHT_LINE', 'DECLINING_BALANCE')),
    CONSTRAINT ck_fixed_assets_status CHECK (status IN ('IN_USE', 'DISPOSED'))
);
CREATE INDEX idx_fixed_assets_asset_account_id ON public.fixed_assets (asset_account_id);
CREATE INDEX idx_fixed_assets_status           ON public.fixed_assets (status);
CREATE INDEX idx_fixed_assets_acquisition_date ON public.fixed_assets (acquisition_date);

CREATE TABLE public.depreciations (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        timestamp(6) without time zone,
    updated_at        timestamp(6) without time zone,
    asset_id          bigint NOT NULL,
    period            character varying(7) NOT NULL,
    depreciation_date date NOT NULL,
    amount            numeric(18,2) NOT NULL,
    accumulated_after numeric(18,2) NOT NULL,
    book_value_after  numeric(18,2) NOT NULL,
    journal_entry_id  bigint,
    created_by        character varying(50),
    -- 같은 달을 두 번 돌려도 이중 상각되지 않게 DB 에서 막는다
    CONSTRAINT uk_depreciations_asset_period UNIQUE (asset_id, period),
    CONSTRAINT fk_depreciations_asset_id FOREIGN KEY (asset_id) REFERENCES public.fixed_assets(id),
    CONSTRAINT fk_depreciations_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id)
);
CREATE INDEX idx_depreciations_asset_id         ON public.depreciations (asset_id);
CREATE INDEX idx_depreciations_journal_entry_id ON public.depreciations (journal_entry_id);
CREATE INDEX idx_depreciations_period           ON public.depreciations (period);
