-- V34: 어음거래 — 받을어음(매출대금 수취) / 지급어음(매입대금 발행)
--
-- 수취·발행 시점에 채권/채무가 어음으로 대체되고, 만기에 결제되면 예금으로 정리된다.
-- 받을어음은 만기 전 은행 할인(매각) 또는 부도가 가능하다. 모든 처리는 분개를 남긴다.
--
--   받을어음 수취  차)받을어음   / 대)외상매출금
--   지급어음 발행  차)외상매입금 / 대)지급어음
--   받을어음 결제  차)예금       / 대)받을어음
--   지급어음 결제  차)지급어음   / 대)예금
--   받을어음 할인  차)예금·매출채권처분손실 / 대)받을어음
--   받을어음 부도  차)외상매출금 / 대)받을어음   (채권으로 환원)

-- 어음 분개에 필요한 계정 (기존 시드에 없음)
INSERT INTO public.accounts (created_at, updated_at, code, name, division, detail_category, active) VALUES
 (now(), now(), '110', '받을어음',         'ASSET',     '매출채권', true),
 (now(), now(), '252', '지급어음',         'LIABILITY', '매입채무', true),
 (now(), now(), '936', '매출채권처분손실', 'EXPENSE',   '영업외비용', true)
ON CONFLICT (code) DO NOTHING;

CREATE TABLE public.promissory_notes (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone,
    note_no      character varying(30) NOT NULL,
    -- RECEIVABLE(받을어음) / PAYABLE(지급어음)
    type         character varying(20) NOT NULL,
    partner_id   bigint NOT NULL,
    issue_date   date NOT NULL,
    due_date     date NOT NULL,
    amount       numeric(18,2) NOT NULL,
    -- HELD(보유) → SETTLED(결제완료) / DISCOUNTED(할인) / DISHONORED(부도)
    status       character varying(20) NOT NULL DEFAULT 'HELD',
    closed_date  date,
    discount_fee numeric(18,2),
    bank_name    character varying(100),
    remark       character varying(300),
    created_by   character varying(50),
    CONSTRAINT uk_promissory_notes_note_no UNIQUE (note_no),
    CONSTRAINT fk_promissory_notes_partner_id FOREIGN KEY (partner_id) REFERENCES public.business_partners(id),
    CONSTRAINT ck_promissory_notes_type CHECK (type IN ('RECEIVABLE', 'PAYABLE')),
    CONSTRAINT ck_promissory_notes_status CHECK (status IN ('HELD', 'SETTLED', 'DISCOUNTED', 'DISHONORED'))
);
CREATE INDEX idx_promissory_notes_partner_id ON public.promissory_notes (partner_id);
CREATE INDEX idx_promissory_notes_due_date   ON public.promissory_notes (due_date);
CREATE INDEX idx_promissory_notes_status     ON public.promissory_notes (status);
CREATE INDEX idx_promissory_notes_type       ON public.promissory_notes (type);
