-- V35: FastEntry 간편전표 — 지출결의서 · 입금보고서 · 가지급금정산서 (회계 I 4-2)
--
-- 라인(계정별 금액)과 결제수단만 입력하면 복식부기 분개를 자동으로 만든다.
--   지출결의서      차)비용라인들 / 대)결제수단(현금·예금·미지급금)
--   입금보고서      차)입금수단(현금·예금·외상매출금) / 대)수입라인들
--   가지급금정산서  차)사용비용(+반납액) / 대)가지급금(+추가지급액)
-- 그래서 journal_entries.source_type 에 VOUCHER 를 추가한다.

ALTER TABLE public.journal_entries DROP CONSTRAINT ck_journal_entries_source_type;
ALTER TABLE public.journal_entries ADD CONSTRAINT ck_journal_entries_source_type
    CHECK (source_type IN ('SALES', 'PURCHASE', 'EXPENSE', 'BANK', 'CARD', 'NOTE',
                           'DEPRECIATION', 'DISPOSAL', 'VOUCHER', 'MANUAL'));

-- 간편전표로 생긴 계좌 이동은 상대편이 여러 줄이라 단일 상대계정을 특정할 수 없다.
-- (분개를 보면 되므로 NULL 을 허용한다. 계좌입출금 화면에서 넣는 건 여전히 상대계정을 받는다.)
ALTER TABLE public.bank_transactions ALTER COLUMN counter_account_id DROP NOT NULL;

CREATE TABLE public.fast_vouchers (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6) without time zone,
    updated_at       timestamp(6) without time zone,
    voucher_no       character varying(30) NOT NULL,
    type             character varying(30) NOT NULL,
    voucher_date     date NOT NULL,
    method           character varying(20) NOT NULL,
    bank_account_id  bigint,
    partner_id       bigint,
    -- 가지급금정산서에서만: 먼저 지급했던 가지급금 총액
    advance_amount   numeric(18,2),
    total_amount     numeric(18,2) NOT NULL DEFAULT 0,
    journal_entry_id bigint,
    description      character varying(200),
    created_by       character varying(50),
    CONSTRAINT uk_fast_vouchers_voucher_no UNIQUE (voucher_no),
    CONSTRAINT fk_fast_vouchers_bank_account_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
    CONSTRAINT fk_fast_vouchers_partner_id FOREIGN KEY (partner_id) REFERENCES public.business_partners(id),
    CONSTRAINT fk_fast_vouchers_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
    CONSTRAINT ck_fast_vouchers_type CHECK (type IN ('EXPENSE_REPORT', 'DEPOSIT_REPORT', 'ADVANCE_SETTLEMENT')),
    CONSTRAINT ck_fast_vouchers_method CHECK (method IN ('CASH', 'BANK', 'CREDIT'))
);
CREATE INDEX idx_fast_vouchers_bank_account_id  ON public.fast_vouchers (bank_account_id);
CREATE INDEX idx_fast_vouchers_partner_id       ON public.fast_vouchers (partner_id);
CREATE INDEX idx_fast_vouchers_journal_entry_id ON public.fast_vouchers (journal_entry_id);
CREATE INDEX idx_fast_vouchers_voucher_date     ON public.fast_vouchers (voucher_date);
CREATE INDEX idx_fast_vouchers_type             ON public.fast_vouchers (type);

CREATE TABLE public.fast_voucher_lines (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id  bigint NOT NULL,
    account_id  bigint NOT NULL,
    amount      numeric(18,2) NOT NULL,
    description character varying(200),
    line_no     integer NOT NULL DEFAULT 1,
    CONSTRAINT fk_fast_voucher_lines_voucher_id FOREIGN KEY (voucher_id)
        REFERENCES public.fast_vouchers(id) ON DELETE CASCADE,
    CONSTRAINT fk_fast_voucher_lines_account_id FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE INDEX idx_fast_voucher_lines_voucher_id ON public.fast_voucher_lines (voucher_id);
CREATE INDEX idx_fast_voucher_lines_account_id ON public.fast_voucher_lines (account_id);
