-- V36: 전자근로계약 (employment_contracts)
--
-- 사원과 회사 사이의 근로계약을 작성 → 발송 → 서명 → (해지) 로 관리한다.
-- 서명이 끝난 계약은 근로조건의 확정 기록이므로 수정할 수 없다(재계약으로 새 계약을 만든다).
--
-- 계약기간: 정규직은 종료일(end_date)이 없다. 계약직·일용직은 종료일이 있어야 한다
-- (서비스에서 강제).

CREATE TABLE public.employment_contracts (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6) without time zone,
    updated_at     timestamp(6) without time zone,
    contract_no    varchar(30)  NOT NULL,
    employee_id    bigint       NOT NULL,
    -- 정규직(PERMANENT) / 계약직(FIXED_TERM) / 일용직(DAILY)
    type           varchar(20)  NOT NULL,
    -- 작성(DRAFT) → 발송(SENT) → 서명완료(SIGNED) / 해지(TERMINATED)
    status         varchar(20)  NOT NULL DEFAULT 'DRAFT',
    start_date     date         NOT NULL,
    end_date       date,
    -- 계약 시점의 근로조건. 사원 마스터가 나중에 바뀌어도 계약서의 조건은 그대로여야 한다.
    department_id  bigint,
    job_title      varchar(100),
    monthly_salary numeric(18,2) NOT NULL DEFAULT 0,
    weekly_hours   integer      NOT NULL DEFAULT 40,
    work_place     varchar(200),
    duty           varchar(200),
    -- 서명
    signed_at      timestamp(6) without time zone,
    signed_by      varchar(100),
    remark         varchar(500),
    created_by     varchar(50),
    CONSTRAINT uk_employment_contracts_contract_no UNIQUE (contract_no),
    CONSTRAINT fk_employment_contracts_employee_id FOREIGN KEY (employee_id)
        REFERENCES public.employees(id),
    CONSTRAINT fk_employment_contracts_department_id FOREIGN KEY (department_id)
        REFERENCES public.departments(id),
    CONSTRAINT ck_employment_contracts_type   CHECK (type IN ('PERMANENT', 'FIXED_TERM', 'DAILY')),
    CONSTRAINT ck_employment_contracts_status CHECK (status IN ('DRAFT', 'SENT', 'SIGNED', 'TERMINATED'))
);
CREATE INDEX idx_employment_contracts_employee_id   ON public.employment_contracts (employee_id);
CREATE INDEX idx_employment_contracts_department_id ON public.employment_contracts (department_id);
CREATE INDEX idx_employment_contracts_status        ON public.employment_contracts (status);
CREATE INDEX idx_employment_contracts_start_date    ON public.employment_contracts (start_date);
