-- V37: 비현금거래(대체전표) — 회계 I 4-7
--
-- 현금·예금이 한 푼도 움직이지 않는 거래를 차변계정 하나 · 대변계정 하나로 남긴다.
--   상계        차)외상매입금 / 대)외상매출금
--   대손처리    차)대손상각비 / 대)외상매출금
--   미지급 계상 차)비용계정   / 대)미지급금
--   계정대체    차/대변 모두 사용자가 지정
-- 현금성 계정이 끼면 서비스가 거절한다(그건 현금거래·계좌입출금 화면이 할 일이다).
-- 그래서 journal_entries.source_type 에 NONCASH 를 추가한다.

ALTER TABLE public.journal_entries DROP CONSTRAINT ck_journal_entries_source_type;
ALTER TABLE public.journal_entries ADD CONSTRAINT ck_journal_entries_source_type
    CHECK (source_type IN ('SALES', 'PURCHASE', 'EXPENSE', 'BANK', 'CARD', 'NOTE',
                           'DEPRECIATION', 'DISPOSAL', 'VOUCHER', 'NONCASH', 'MANUAL'));

CREATE TABLE public.non_cash_transactions (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        timestamp(6) without time zone,
    updated_at        timestamp(6) without time zone,
    txn_no            character varying(30) NOT NULL,
    type              character varying(20) NOT NULL,
    txn_date          date NOT NULL,
    debit_account_id  bigint NOT NULL,
    credit_account_id bigint NOT NULL,
    amount            numeric(18,2) NOT NULL,
    partner_id        bigint,
    journal_entry_id  bigint,
    description       character varying(200),
    created_by        character varying(50),
    CONSTRAINT uk_non_cash_transactions_txn_no UNIQUE (txn_no),
    CONSTRAINT fk_non_cash_transactions_debit_account_id FOREIGN KEY (debit_account_id) REFERENCES public.accounts(id),
    CONSTRAINT fk_non_cash_transactions_credit_account_id FOREIGN KEY (credit_account_id) REFERENCES public.accounts(id),
    CONSTRAINT fk_non_cash_transactions_partner_id FOREIGN KEY (partner_id) REFERENCES public.business_partners(id),
    CONSTRAINT fk_non_cash_transactions_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
    CONSTRAINT ck_non_cash_transactions_type CHECK (type IN ('OFFSET', 'BAD_DEBT', 'ACCRUAL', 'TRANSFER')),
    -- 차변과 대변이 같은 계정이면 분개가 아무것도 하지 않는다
    CONSTRAINT ck_non_cash_transactions_accounts CHECK (debit_account_id <> credit_account_id)
);
CREATE INDEX idx_non_cash_transactions_debit_account_id  ON public.non_cash_transactions (debit_account_id);
CREATE INDEX idx_non_cash_transactions_credit_account_id ON public.non_cash_transactions (credit_account_id);
CREATE INDEX idx_non_cash_transactions_partner_id        ON public.non_cash_transactions (partner_id);
CREATE INDEX idx_non_cash_transactions_journal_entry_id  ON public.non_cash_transactions (journal_entry_id);
CREATE INDEX idx_non_cash_transactions_txn_date          ON public.non_cash_transactions (txn_date);
CREATE INDEX idx_non_cash_transactions_type              ON public.non_cash_transactions (type);
