-- V38: 일용근로급여 (daily_work_records)
--
-- 일용직은 월급이 아니라 "출역한 날"마다 일당을 받는다. 그래서 급여명세(payslips)가 아니라
-- 근무일 단위 기록을 쌓고, 지급 시점에 일용근로소득세를 원천징수한다.
--
-- 일용근로소득세(소득세법 §47조의2, §59):
--   과세대상 = 일당 − 150,000 (일 15만원 근로소득공제)
--   산출세액 = 과세대상 × 6%
--   결정세액 = 산출세액 × (1 − 55% 근로소득세액공제) = 과세대상 × 2.7%
--   소액부징수: 결정세액이 1,000원 미만이면 징수하지 않는다 (일 단위 판정)
--   지방소득세 = 소득세의 10%
-- 세액은 등록 시점에 계산해 박아 둔다. 세율이 나중에 바뀌어도 과거 기록은 그대로여야 한다.

CREATE TABLE public.daily_work_records (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6) without time zone,
    updated_at       timestamp(6) without time zone,
    employee_id      bigint       NOT NULL,
    work_date        date         NOT NULL,
    work_hours       integer      NOT NULL DEFAULT 8,
    daily_wage       numeric(18,2) NOT NULL,
    income_tax       numeric(18,2) NOT NULL DEFAULT 0,
    local_income_tax numeric(18,2) NOT NULL DEFAULT 0,
    net_pay          numeric(18,2) NOT NULL DEFAULT 0,
    paid             boolean      NOT NULL DEFAULT false,
    paid_date        date,
    remark           varchar(500),
    created_by       varchar(50),
    -- 같은 사람의 같은 날을 두 번 등록하면 일당도 세금도 두 배가 된다.
    CONSTRAINT uk_daily_work_records_employee_date UNIQUE (employee_id, work_date),
    CONSTRAINT fk_daily_work_records_employee_id FOREIGN KEY (employee_id)
        REFERENCES public.employees(id)
);
CREATE INDEX idx_daily_work_records_employee_id ON public.daily_work_records (employee_id);
CREATE INDEX idx_daily_work_records_work_date   ON public.daily_work_records (work_date);
CREATE INDEX idx_daily_work_records_paid        ON public.daily_work_records (paid);
