-- V40: 회계 II — 예산관리 · 자금계획
--
-- 둘 다 '계획'만 저장한다. 실적은 저장하지 않는다.
--   예산 집행실적 = journal_lines 에서 그 달·그 계정의 금액 집계
--   자금 실적     = bank_transactions 에서 그 달의 입금·출금 집계
-- 실적을 복제해 두면 전표를 고칠 때마다 어긋나므로, 볼 때 계산한다.

CREATE TABLE public.budgets (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    -- 귀속월 (YYYY-MM)
    period      character varying(7) NOT NULL,
    account_id  bigint NOT NULL,
    amount      numeric(18,2) NOT NULL,
    remark      character varying(300),
    created_by  character varying(50),
    -- 같은 달 같은 계정에 예산을 두 번 편성할 수 없다
    CONSTRAINT uk_budgets_period_account UNIQUE (period, account_id),
    CONSTRAINT fk_budgets_account_id FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE INDEX idx_budgets_account_id ON public.budgets (account_id);
CREATE INDEX idx_budgets_period     ON public.budgets (period);

CREATE TABLE public.cash_plans (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    period      character varying(7) NOT NULL,
    -- INFLOW(수입) / OUTFLOW(지출)
    type        character varying(20) NOT NULL,
    category    character varying(100) NOT NULL,
    amount      numeric(18,2) NOT NULL,
    remark      character varying(300),
    created_by  character varying(50),
    CONSTRAINT ck_cash_plans_type CHECK (type IN ('INFLOW', 'OUTFLOW'))
);
CREATE INDEX idx_cash_plans_period ON public.cash_plans (period);
