-- V41: 기타원천세 (other_withholdings)
--
-- 근로소득 외의 지급에 붙는 원천징수다. 급여(payslips)와 달리 4대보험이 없고,
-- 소득구분별로 세율이 정해져 있다.
--
--   사업소득(BUSINESS): 프리랜서·용역. 소득세 3% + 지방소득세 0.3% = 3.3%
--   기타소득(OTHER)   : 강연료·원고료 등. 필요경비 60% 를 뺀 나머지에 20% + 지방세 → 실효 8.8%
--   이자소득(INTEREST): 14% + 지방세 1.4% = 15.4%
--   배당소득(DIVIDEND): 이자와 같은 15.4%
--
-- 세액은 등록 시점에 계산해 박아 둔다(세율이 바뀌어도 과거 지급은 그대로여야 한다).
-- 지급 대상은 거래처(business_partners) 또는 이름만 있는 개인 둘 다 가능하다.

CREATE TABLE public.other_withholdings (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6) without time zone,
    updated_at       timestamp(6) without time zone,
    doc_no           varchar(30)  NOT NULL,
    pay_date         date         NOT NULL,
    -- BUSINESS(사업소득) / OTHER(기타소득) / INTEREST(이자소득) / DIVIDEND(배당소득)
    income_type      varchar(20)  NOT NULL,
    -- 지급 대상: 거래처를 고르거나, 이름만 적는다(둘 중 하나는 반드시 있어야 한다 → 서비스에서 강제)
    partner_id       bigint,
    payee_name       varchar(100) NOT NULL,
    payee_reg_no     varchar(20),
    -- 금액
    gross_amount     numeric(18,2) NOT NULL,
    -- 기타소득의 필요경비(60%). 나머지 소득구분은 0
    expense_amount   numeric(18,2) NOT NULL DEFAULT 0,
    taxable_amount   numeric(18,2) NOT NULL DEFAULT 0,
    income_tax       numeric(18,2) NOT NULL DEFAULT 0,
    local_income_tax numeric(18,2) NOT NULL DEFAULT 0,
    net_amount       numeric(18,2) NOT NULL DEFAULT 0,
    description      varchar(200),
    created_by       varchar(50),
    CONSTRAINT uk_other_withholdings_doc_no UNIQUE (doc_no),
    CONSTRAINT fk_other_withholdings_partner_id FOREIGN KEY (partner_id)
        REFERENCES public.business_partners(id),
    CONSTRAINT ck_other_withholdings_income_type
        CHECK (income_type IN ('BUSINESS', 'OTHER', 'INTEREST', 'DIVIDEND'))
);
CREATE INDEX idx_other_withholdings_pay_date    ON public.other_withholdings (pay_date);
CREATE INDEX idx_other_withholdings_partner_id  ON public.other_withholdings (partner_id);
CREATE INDEX idx_other_withholdings_income_type ON public.other_withholdings (income_type);
