-- V42: 수표관리 (회계 II 5-3)
--
--   받은수표: 수취(보유) → 계좌 입금 또는 부도
--   발행수표: 당좌계좌에서 발행(그 순간 예금이 빠진다) → 은행 인출 확인 시 결제완료 표시
-- 분개:
--   수취  차)받을수표(104) / 대)외상매출금(108)
--   발행  차)외상매입금(251) / 대)발행계좌의 예금계정
--   입금  차)입금계좌의 예금계정 / 대)받을수표
--   부도  차)외상매출금 / 대)받을수표 (현금은 움직이지 않는다)
-- 한 수표가 전표를 여러 장 만들므로 source_id 는 최초 수취/발행에만 채운다
-- (uk_journal_entries_source 는 source_id IS NOT NULL 에만 걸린다).

ALTER TABLE public.journal_entries DROP CONSTRAINT ck_journal_entries_source_type;
ALTER TABLE public.journal_entries ADD CONSTRAINT ck_journal_entries_source_type
    CHECK (source_type IN ('SALES', 'PURCHASE', 'EXPENSE', 'BANK', 'CARD', 'NOTE',
                           'DEPRECIATION', 'DISPOSAL', 'VOUCHER', 'NONCASH', 'CHECK', 'MANUAL'));

CREATE TABLE public.bank_checks (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp(6) without time zone,
    updated_at      timestamp(6) without time zone,
    check_no        character varying(30) NOT NULL,
    type            character varying(20) NOT NULL,
    status          character varying(20) NOT NULL DEFAULT 'HELD',
    issue_date      date NOT NULL,
    amount          numeric(18,2) NOT NULL,
    bank_name       character varying(50),
    partner_id      bigint,
    -- 발행수표는 끊어 준 당좌계좌, 받은수표는 입금한 계좌(입금 전에는 NULL)
    bank_account_id bigint,
    settled_date    date,
    remark          character varying(200),
    created_by      character varying(50),
    CONSTRAINT uk_bank_checks_check_no UNIQUE (check_no),
    CONSTRAINT fk_bank_checks_partner_id FOREIGN KEY (partner_id) REFERENCES public.business_partners(id),
    CONSTRAINT fk_bank_checks_bank_account_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
    CONSTRAINT ck_bank_checks_type CHECK (type IN ('RECEIVED', 'ISSUED')),
    CONSTRAINT ck_bank_checks_status CHECK (status IN ('HELD', 'DEPOSITED', 'PAID', 'DISHONORED'))
);
CREATE INDEX idx_bank_checks_partner_id      ON public.bank_checks (partner_id);
CREATE INDEX idx_bank_checks_bank_account_id ON public.bank_checks (bank_account_id);
CREATE INDEX idx_bank_checks_issue_date      ON public.bank_checks (issue_date);
CREATE INDEX idx_bank_checks_status          ON public.bank_checks (status);
CREATE INDEX idx_bank_checks_type            ON public.bank_checks (type);
