-- V45: 그룹웨어 공용메일 — 사내메일 + 공용 메일함(담당자 배정·처리)
--
-- 외부 메일 서버 연동은 없다. 공용메일은 회사 대표 메일함으로 들어온 메일을 등록해 두고,
-- 담당자를 배정해 처리 상태를 추적한다. 나중에 IMAP 수신 훅이 붙으면 등록 API 자리에 들어온다.
--
--   INTERNAL(사내메일) : sender → recipient. 수신자가 읽으면 READ.
--   SHARED(공용메일)   : from_address 로 들어옴. 담당자 배정 시 IN_PROGRESS, 처리하면 HANDLED.

CREATE TABLE public.mails (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone,
    type         character varying(20) NOT NULL,
    -- 사내메일의 보낸 사람 (공용메일은 비어 있고 from_address 를 쓴다)
    sender_id    bigint,
    from_address character varying(200),
    -- 사내메일의 받는 사람 (공용메일은 특정 수신자가 없다)
    recipient_id bigint,
    subject      character varying(200) NOT NULL,
    body         text,
    sent_at      timestamp(6) without time zone NOT NULL,
    status       character varying(20) NOT NULL DEFAULT 'UNREAD',
    assignee_id  bigint,
    handled_at   timestamp(6) without time zone,
    handle_note  character varying(500),
    CONSTRAINT fk_mails_sender_id    FOREIGN KEY (sender_id)    REFERENCES public.users(id),
    CONSTRAINT fk_mails_recipient_id FOREIGN KEY (recipient_id) REFERENCES public.users(id),
    CONSTRAINT fk_mails_assignee_id  FOREIGN KEY (assignee_id)  REFERENCES public.users(id),
    CONSTRAINT ck_mails_type   CHECK (type IN ('INTERNAL', 'SHARED')),
    CONSTRAINT ck_mails_status CHECK (status IN ('UNREAD', 'READ', 'IN_PROGRESS', 'HANDLED'))
);
CREATE INDEX idx_mails_sender_id    ON public.mails (sender_id);
CREATE INDEX idx_mails_recipient_id ON public.mails (recipient_id);
CREATE INDEX idx_mails_assignee_id  ON public.mails (assignee_id);
CREATE INDEX idx_mails_type_status  ON public.mails (type, status);
CREATE INDEX idx_mails_sent_at      ON public.mails (sent_at);
