-- V4: 사원(employees) 마스터 신설
--
-- 배경: work_results.worker 가 varchar 자유입력이라 생산실적을 사람별로 집계할 수 없다.
--       작업자는 로그인 계정(users)이 필요 없으므로 users 로 등록하지 않고
--       별도 사원 마스터를 둔다.
--
-- 이 마이그레이션은 마스터만 만든다. work_results.worker → employee_id FK 전환은
-- 별도 마이그레이션에서 한다 (WorkResult 엔티티/시더 수정을 동반하므로).

CREATE TABLE employees (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,

    -- 사번 (예: EMP-0001)
    code        varchar(50)  NOT NULL UNIQUE,
    name        varchar(100) NOT NULL,
    department  varchar(100),
    job_title   varchar(100),
    hire_date   date,
    active      boolean      NOT NULL DEFAULT true
);

CREATE INDEX idx_employees_name ON employees (name);

-- ProductionActualInitializer 가 생산실적에 쓰는 데모 작업자 4명을 초기 사원으로 등록한다.
--
-- 주의: 이 4명이 현재 work_results 에 들어있는 것은 아니다. 해당 시더는
--       `workOrderRepository.count() > 0` 이면 즉시 return 하는데 work_orders 가
--       이미 채워져 있어 실적 시딩을 건너뛴다. 지금 work_results 의 worker 는
--       qa/qa.mjs 가 넣은 '검증' 뿐이다.
--       따라서 나중에 worker → employee_id 백필을 할 때 100% 매칭을 기대하지 말 것.
INSERT INTO employees (code, name, department, active) VALUES
    ('EMP-0001', '김철수', '생산', true),
    ('EMP-0002', '박민수', '생산', true),
    ('EMP-0003', '이영희', '생산', true),
    ('EMP-0004', '정수진', '생산', true);
