-- V43: 명함관리 (business_cards)
--
-- 거래처는 있는데 "그 회사의 누구와 이야기했는지"가 어디에도 없다. 담당자 이름·연락처가
-- 각자 휴대폰과 엑셀에 흩어져 있으면, 담당이 바뀌는 순간 연락처가 사라진다.
--
-- 명함은 거래처(business_partners)에 붙는 담당자 연락처 마스터다. 거래처가 없는 명함
-- (아직 거래 전인 잠재 고객, 협회 인맥 등)도 있으므로 partner_id 는 nullable.
-- owner_user_id 는 이 명함을 등록·보유한 우리 쪽 직원(누구의 인맥인지).

CREATE TABLE public.business_cards (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone,
    name          varchar(100) NOT NULL,
    partner_id    bigint,
    -- 거래처가 없는 명함은 회사명을 직접 적는다
    company_name  varchar(200),
    department    varchar(100),
    job_title     varchar(100),
    phone         varchar(30),
    mobile        varchar(30),
    email         varchar(200),
    address       varchar(300),
    -- 명함 보유자(우리 쪽 담당자)
    owner_user_id bigint,
    -- 쉼표로 구분한 태그 (예: "핵심,구매팀")
    tags          varchar(200),
    memo          varchar(1000),
    CONSTRAINT fk_business_cards_partner_id FOREIGN KEY (partner_id)
        REFERENCES public.business_partners(id),
    CONSTRAINT fk_business_cards_owner_user_id FOREIGN KEY (owner_user_id)
        REFERENCES public.users(id)
);
CREATE INDEX idx_business_cards_partner_id    ON public.business_cards (partner_id);
CREATE INDEX idx_business_cards_owner_user_id ON public.business_cards (owner_user_id);
CREATE INDEX idx_business_cards_name          ON public.business_cards (name);
