-- V51: 계약관리 · 전자계약 (회계 II 5-8 / 5-9)
--
-- 거래처와 맺는 계약을 작성 → 서명요청 → 전자서명 → (해지) 순으로 관리한다.
-- 전자서명은 서명자·서명일시·동의문구를 그대로 남기는 방식이다
-- (외부 공인인증기관 연동은 없다 — 사내 합의 기록으로 쓴다).
-- 근로계약(employment_contracts)과는 별개다.

CREATE TABLE public.business_contracts (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         timestamp(6) without time zone,
    updated_at         timestamp(6) without time zone,
    contract_no        character varying(30) NOT NULL,
    title              character varying(200) NOT NULL,
    type               character varying(20) NOT NULL,
    status             character varying(20) NOT NULL DEFAULT 'DRAFT',
    partner_id         bigint NOT NULL,
    start_date         date NOT NULL,
    end_date           date NOT NULL,
    amount             numeric(18,2) NOT NULL DEFAULT 0,
    payment_terms      character varying(200),
    content            text,
    sent_at            timestamp(6) without time zone,
    signer_name        character varying(50),
    signed_at          timestamp(6) without time zone,
    agreement          character varying(300),
    terminated_date    date,
    termination_reason character varying(200),
    created_by         character varying(50),
    CONSTRAINT uk_business_contracts_contract_no UNIQUE (contract_no),
    CONSTRAINT fk_business_contracts_partner_id FOREIGN KEY (partner_id) REFERENCES public.business_partners(id),
    CONSTRAINT ck_business_contracts_type CHECK (type IN ('SALES', 'PURCHASE', 'OTHER')),
    CONSTRAINT ck_business_contracts_status CHECK (status IN ('DRAFT', 'SENT', 'SIGNED', 'TERMINATED')),
    -- 종료일이 시작일보다 빠른 계약은 없다
    CONSTRAINT ck_business_contracts_period CHECK (end_date >= start_date)
);
CREATE INDEX idx_business_contracts_partner_id ON public.business_contracts (partner_id);
CREATE INDEX idx_business_contracts_status     ON public.business_contracts (status);
CREATE INDEX idx_business_contracts_type       ON public.business_contracts (type);
CREATE INDEX idx_business_contracts_end_date   ON public.business_contracts (end_date);
