-- V55: 법인세 (corporate_tax_returns, corporate_tax_adjustments)
--
-- 법인세는 회계상 당기순이익에서 바로 나오지 않는다. 세법과 회계가 다르게 보는 항목을
-- 더하고 빼는 세무조정을 거쳐야 과세표준이 나온다.
--
--   결산서상 당기순이익 (손익계산서에서 자동으로 가져온다)
--   (+) 익금산입·손금불산입   ← 접대비 한도초과, 벌과금 등
--   (−) 손금산입·익금불산입
--   = 각 사업연도 소득
--   (−) 이월결손금
--   = 과세표준
--   × 세율 (2억 이하 9% / 200억 이하 19% / 3,000억 이하 21% / 초과 24%)
--   = 산출세액
--   (−) 세액공제·감면  (+) 가산세  = 총부담세액
--   (−) 기납부세액(중간예납·원천납부)  = 차감납부할세액
--   지방소득세(법인분) = 산출세액의 10% — 별도 신고
--
-- 조정 금액은 신고 시점에 계산해 박아 둔다. 세율이 바뀌어도 과거 신고서는 그대로여야 한다.

CREATE TABLE public.corporate_tax_returns (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          timestamp(6) without time zone,
    updated_at          timestamp(6) without time zone,
    fiscal_year         integer      NOT NULL,
    period_from         date         NOT NULL,
    period_to           date         NOT NULL,
    -- 작성(DRAFT) → 확정(CONFIRMED). 확정된 신고서는 수정하지 않는다.
    status              varchar(20)  NOT NULL DEFAULT 'DRAFT',
    -- 손익계산서에서 가져온 결산서상 당기순이익
    net_income          numeric(18,2) NOT NULL DEFAULT 0,
    -- 세무조정 합계 (상세는 corporate_tax_adjustments)
    additions           numeric(18,2) NOT NULL DEFAULT 0,
    deductions          numeric(18,2) NOT NULL DEFAULT 0,
    -- 이월결손금 공제
    loss_carryforward   numeric(18,2) NOT NULL DEFAULT 0,
    tax_base            numeric(18,2) NOT NULL DEFAULT 0,
    calculated_tax      numeric(18,2) NOT NULL DEFAULT 0,
    tax_credit          numeric(18,2) NOT NULL DEFAULT 0,
    penalty_tax         numeric(18,2) NOT NULL DEFAULT 0,
    total_tax           numeric(18,2) NOT NULL DEFAULT 0,
    prepaid_tax         numeric(18,2) NOT NULL DEFAULT 0,
    payable_tax         numeric(18,2) NOT NULL DEFAULT 0,
    -- 법인지방소득세 = 산출세액의 10%
    local_income_tax    numeric(18,2) NOT NULL DEFAULT 0,
    remark              varchar(500),
    created_by          varchar(50),
    -- 같은 사업연도 신고서를 두 개 만들면 어느 것이 진짜인지 알 수 없다.
    CONSTRAINT uk_corporate_tax_returns_fiscal_year UNIQUE (fiscal_year),
    CONSTRAINT ck_corporate_tax_returns_status CHECK (status IN ('DRAFT', 'CONFIRMED'))
);
CREATE INDEX idx_corporate_tax_returns_status ON public.corporate_tax_returns (status);

CREATE TABLE public.corporate_tax_adjustments (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id    bigint       NOT NULL,
    -- ADD: 익금산입·손금불산입 (소득을 늘린다) / DEDUCT: 손금산입·익금불산입 (줄인다)
    type         varchar(20)  NOT NULL,
    name         varchar(200) NOT NULL,
    amount       numeric(18,2) NOT NULL,
    remark       varchar(500),
    CONSTRAINT fk_corporate_tax_adjustments_return_id FOREIGN KEY (return_id)
        REFERENCES public.corporate_tax_returns(id) ON DELETE CASCADE,
    CONSTRAINT ck_corporate_tax_adjustments_type CHECK (type IN ('ADD', 'DEDUCT'))
);
CREATE INDEX idx_corporate_tax_adjustments_return_id ON public.corporate_tax_adjustments (return_id);
