-- V56: 회계 II 수입비용 — 수입등록 (비용등록의 대칭)
--
-- 매출 전표를 거치지 않는 수익(이자수익·잡이익·임대수입 등)을 잡는다.
-- 등록하면 바로 분개가 생긴다. 차변은 회수 수단이 정하고, 대변은 고른 수익 계정이다.
--
--   현금    차)현금(101)     / 대)수익계정
--   계좌    차)예금계정      / 대)수익계정   (계좌 잔액도 함께 오른다)
--   외상    차)외상매출금(108) / 대)수익계정

-- 수입에 흔히 쓰는 영업외수익 계정 (기존 시드에 없음)
INSERT INTO public.accounts (created_at, updated_at, code, name, division, detail_category, active) VALUES
 (now(), now(), '901', '이자수익',   'REVENUE', '영업외수익', true),
 (now(), now(), '904', '임대료수입', 'REVENUE', '영업외수익', true),
 (now(), now(), '930', '잡이익',     'REVENUE', '영업외수익', true)
ON CONFLICT (code) DO NOTHING;

CREATE TABLE public.incomes (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6) without time zone,
    updated_at       timestamp(6) without time zone,
    income_date      date NOT NULL,
    account_id       bigint NOT NULL,
    content          character varying(200) NOT NULL,
    partner_name     character varying(100),
    amount           numeric(18,2) NOT NULL,
    -- CASH(현금) / BANK(계좌입금) / CREDIT(외상)
    receipt_method   character varying(20) NOT NULL,
    bank_account_id  bigint,
    journal_entry_id bigint,
    department       character varying(100),
    created_by       character varying(50),
    CONSTRAINT fk_incomes_account_id       FOREIGN KEY (account_id)       REFERENCES public.accounts(id),
    CONSTRAINT fk_incomes_bank_account_id  FOREIGN KEY (bank_account_id)  REFERENCES public.bank_accounts(id),
    CONSTRAINT fk_incomes_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
    CONSTRAINT ck_incomes_receipt_method CHECK (receipt_method IN ('CASH', 'BANK', 'CREDIT'))
);
CREATE INDEX idx_incomes_account_id       ON public.incomes (account_id);
CREATE INDEX idx_incomes_bank_account_id  ON public.incomes (bank_account_id);
CREATE INDEX idx_incomes_journal_entry_id ON public.incomes (journal_entry_id);
CREATE INDEX idx_incomes_income_date      ON public.incomes (income_date);
