-- V60: WMS — 창고 로케이션(warehouse_locations)과 로케이션별 재고 배치(location_stocks)
--
-- 지금까지 WMS 화면은 창고·재고·로트를 조합해 로케이션을 "파생"해서 보여줬을 뿐,
-- 실제로 어느 선반에 무엇이 있는지는 아무 데도 없었다.
--
-- 설계 원칙: 창고 단위 재고(stocks)가 진실의 출처다. 로케이션 배치는 그 재고를
-- 창고 안에서 어디에 두었는지 쪼갠 것이다. 따라서
--
--   같은 (품목, 창고)에 대해  Σ location_stocks.quantity  ≤  stocks.quantity
--
-- 가 항상 성립해야 한다(서비스에서 강제). 남는 차이는 "미배치 수량"이며, 입고했지만
-- 아직 선반에 올리지 않은 물량을 뜻한다. 이 규칙을 깨고 로케이션 재고를 별도 진실로
-- 두면 두 숫자가 반드시 갈라진다.

CREATE TABLE public.warehouse_locations (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6) without time zone,
    updated_at   timestamp(6) without time zone,
    warehouse_id bigint       NOT NULL,
    -- 로케이션 코드 (예: A-01-3). 창고 안에서 유일해야 한다.
    code         varchar(50)  NOT NULL,
    zone         varchar(50),
    rack         varchar(50),
    level        varchar(50),
    description  varchar(200),
    active       boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_warehouse_locations_warehouse_code UNIQUE (warehouse_id, code),
    CONSTRAINT fk_warehouse_locations_warehouse_id FOREIGN KEY (warehouse_id)
        REFERENCES public.warehouses(id)
);
CREATE INDEX idx_warehouse_locations_warehouse_id ON public.warehouse_locations (warehouse_id);

CREATE TABLE public.location_stocks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    location_id bigint       NOT NULL,
    item_id     bigint       NOT NULL,
    quantity    numeric(18,2) NOT NULL DEFAULT 0,
    -- 같은 로케이션에 같은 품목 행이 둘이면 수량이 갈라진다.
    CONSTRAINT uk_location_stocks_location_item UNIQUE (location_id, item_id),
    CONSTRAINT fk_location_stocks_location_id FOREIGN KEY (location_id)
        REFERENCES public.warehouse_locations(id),
    CONSTRAINT fk_location_stocks_item_id FOREIGN KEY (item_id)
        REFERENCES public.items(id),
    CONSTRAINT ck_location_stocks_quantity_non_negative CHECK (quantity >= 0)
);
CREATE INDEX idx_location_stocks_location_id ON public.location_stocks (location_id);
CREATE INDEX idx_location_stocks_item_id     ON public.location_stocks (item_id);
