-- V61: 외화 — 통화 마스터와 일자별 고시환율 (기초등록 2-1 / 4-1)
--
-- 원화(KRW)는 기준통화라 등록하지 않는다(서비스에서 거절).
-- rate 는 통화 unit 만큼에 대한 원화 금액이다: JPY 는 unit=100, rate=950 → 100엔 = 950원.
-- 환산은 "그날 고시가 없으면 직전 고시를 쓴다"(주말·휴일 고시 공백).

CREATE TABLE public.currencies (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code       character varying(3) NOT NULL,
    name       character varying(50) NOT NULL,
    symbol     character varying(5),
    unit       integer NOT NULL DEFAULT 1,
    active     boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_currencies_code UNIQUE (code),
    CONSTRAINT ck_currencies_unit CHECK (unit > 0)
);

CREATE TABLE public.exchange_rates (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    currency_id bigint NOT NULL,
    rate_date   date NOT NULL,
    rate        numeric(18,4) NOT NULL,
    created_by  character varying(50),
    -- 같은 통화의 같은 날 환율은 하나만 존재한다
    CONSTRAINT uk_exchange_rates_currency_date UNIQUE (currency_id, rate_date),
    CONSTRAINT fk_exchange_rates_currency_id FOREIGN KEY (currency_id) REFERENCES public.currencies(id),
    CONSTRAINT ck_exchange_rates_rate CHECK (rate > 0)
);
CREATE INDEX idx_exchange_rates_currency_id ON public.exchange_rates (currency_id);
CREATE INDEX idx_exchange_rates_rate_date   ON public.exchange_rates (rate_date);

-- 자주 쓰는 통화는 미리 넣어 둔다 (환율은 사용자가 고시일자별로 등록)
INSERT INTO public.currencies (code, name, symbol, unit, active) VALUES
    ('USD', '미국 달러', '$', 1, true),
    ('JPY', '일본 엔', '¥', 100, true),
    ('EUR', '유로', '€', 1, true),
    ('CNY', '중국 위안', '¥', 1, true);
