-- V65: 수출관리 — 수출 오더(Invoice) 실제 스키마
--
-- 지금까지 수출 화면은 판매 전표를 수출처럼 보여주는 프록시였고, 진행단계는 판매일로부터
-- 며칠 지났는지로 지어냈다. 실제 수출은 외화로 팔고, 통관·선적·입금이 각각 문서를 남긴다.
--
-- 금액은 외화가 원본이다. 원화는 인보이스 발행일의 고시환율로 환산해 함께 박아둔다.
-- 볼 때마다 환산하면 어제 본 금액과 오늘 본 금액이 달라져 세관·회계와 어긋난다.
--
--   오더 → 통관진행(수출신고번호) → 선적완료(B/L·선적일) → 입금완료(입금일)

CREATE TABLE public.export_orders (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6) without time zone,
    updated_at     timestamp(6) without time zone,
    invoice_no     character varying(30) NOT NULL,
    invoice_date   date NOT NULL,
    partner_id     bigint NOT NULL,
    currency_id    bigint NOT NULL,
    foreign_amount numeric(18,2) NOT NULL,
    -- 발행일에 적용한 고시환율과 그 결과 원화액 (사후 환율 변동에 흔들리지 않는다)
    applied_rate   numeric(18,4) NOT NULL,
    krw_amount     numeric(18,2) NOT NULL,
    incoterms      character varying(20),
    destination    character varying(100),
    status         character varying(20) NOT NULL DEFAULT 'ORDER',
    declaration_no character varying(50),
    bl_no          character varying(50),
    shipped_date   date,
    paid_date      date,
    remark         character varying(300),
    created_by     character varying(50),
    CONSTRAINT uk_export_orders_invoice_no UNIQUE (invoice_no),
    CONSTRAINT fk_export_orders_partner_id  FOREIGN KEY (partner_id)  REFERENCES public.business_partners(id),
    CONSTRAINT fk_export_orders_currency_id FOREIGN KEY (currency_id) REFERENCES public.currencies(id),
    CONSTRAINT ck_export_orders_status CHECK (status IN ('ORDER', 'CUSTOMS', 'SHIPPED', 'PAID'))
);
CREATE INDEX idx_export_orders_partner_id   ON public.export_orders (partner_id);
CREATE INDEX idx_export_orders_currency_id  ON public.export_orders (currency_id);
CREATE INDEX idx_export_orders_status       ON public.export_orders (status);
CREATE INDEX idx_export_orders_invoice_date ON public.export_orders (invoice_date);

CREATE TABLE public.export_order_lines (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_order_id bigint NOT NULL,
    item_id         bigint NOT NULL,
    quantity        numeric(18,2) NOT NULL,
    -- 단가·금액은 외화 기준
    unit_price      numeric(18,2) NOT NULL,
    amount          numeric(18,2) NOT NULL DEFAULT 0,
    line_no         integer NOT NULL DEFAULT 1,
    CONSTRAINT fk_export_order_lines_export_order_id FOREIGN KEY (export_order_id)
        REFERENCES public.export_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_export_order_lines_item_id FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE INDEX idx_export_order_lines_export_order_id ON public.export_order_lines (export_order_id);
CREATE INDEX idx_export_order_lines_item_id         ON public.export_order_lines (item_id);
