-- V66: 결재선 프리셋 (그룹웨어 8-2 '결재설정')
--
-- 기안할 때마다 결재자를 하나씩 고르지 않도록, 자주 쓰는 결재 순서를 미리 만들어 둔다.
-- form_template_id 가 비어 있으면 모든 양식에 쓰는 공통 결재선이다.
-- 공통양식(approval_form_templates)은 이미 V13 에 있고, 이번엔 관리 API/화면만 붙인다.

CREATE TABLE public.approval_line_presets (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6) without time zone,
    updated_at       timestamp(6) without time zone,
    name             character varying(100) NOT NULL,
    form_template_id bigint,
    active           boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_approval_line_presets_name UNIQUE (name),
    CONSTRAINT fk_approval_line_presets_form_template_id FOREIGN KEY (form_template_id)
        REFERENCES public.approval_form_templates(id)
);
CREATE INDEX idx_approval_line_presets_form_template_id ON public.approval_line_presets (form_template_id);

CREATE TABLE public.approval_line_preset_steps (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preset_id   bigint NOT NULL,
    approver_id bigint NOT NULL,
    step_order  integer NOT NULL,
    CONSTRAINT fk_approval_line_preset_steps_preset_id FOREIGN KEY (preset_id)
        REFERENCES public.approval_line_presets(id) ON DELETE CASCADE,
    CONSTRAINT fk_approval_line_preset_steps_approver_id FOREIGN KEY (approver_id) REFERENCES public.users(id),
    -- 한 결재선 안에서 같은 순번이 두 번 나오지 않는다
    CONSTRAINT uk_approval_line_preset_steps_order UNIQUE (preset_id, step_order)
);
CREATE INDEX idx_approval_line_preset_steps_preset_id   ON public.approval_line_preset_steps (preset_id);
CREATE INDEX idx_approval_line_preset_steps_approver_id ON public.approval_line_preset_steps (approver_id);
