-- V70: 쇼핑몰관리 (mall_orders)
--
-- 지금까지 쇼핑몰 화면은 판매전표를 "주문처럼" 보여줬을 뿐, 외부몰에서 들어온 주문이라는
-- 개념 자체가 없었다. 그래서 아직 판매로 확정되지 않은 주문(미확인·취소·품절)을 담을 곳이
-- 없었고, 몰 주문번호로 추적할 수도 없었다.
--
-- 흐름: 수집(RECEIVED) → 확인(CONFIRMED) → 판매전환(CONVERTED) / 취소(CANCELLED)
--   · 판매전환 시 판매전표(sales)를 만들고 sales_id 로 연결한다. 재고 차감·채권 계상은
--     판매전표가 한다(쇼핑몰이 재고를 직접 건드리지 않는다 — 진실의 출처는 하나여야 한다).
--   · 몰 주문번호는 몰 안에서 유일하다. (mall, mall_order_no) 유니크로 같은 주문을 두 번
--     수집하는 사고를 막는다.
--
-- 몰의 상품과 우리 품목은 다른 세계다. item_id 로 매핑해 두어야 판매전표를 만들 수 있고,
-- 매핑이 없으면 전환을 거부한다(무엇을 팔았는지 모르는 채로 재고를 깎을 수는 없다).

CREATE TABLE public.mall_orders (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone,
    -- 몰 이름 (예: 스마트스토어, 쿠팡, 자사몰)
    mall          varchar(50)  NOT NULL,
    mall_order_no varchar(50)  NOT NULL,
    order_date    date         NOT NULL,
    -- 수집(RECEIVED) → 확인(CONFIRMED) → 판매전환(CONVERTED) / 취소(CANCELLED)
    status        varchar(20)  NOT NULL DEFAULT 'RECEIVED',
    buyer_name    varchar(100) NOT NULL,
    buyer_phone   varchar(30),
    address       varchar(300),
    -- 몰이 보내준 상품명 원문. 매핑 전에도 무엇을 주문했는지 알아야 한다.
    product_name  varchar(200) NOT NULL,
    item_id       bigint,
    quantity      numeric(18,2) NOT NULL,
    unit_price    numeric(18,2) NOT NULL,
    total_amount  numeric(18,2) NOT NULL DEFAULT 0,
    -- 전환 시 생성된 판매전표
    sales_id      bigint,
    remark        varchar(500),
    created_by    varchar(50),
    CONSTRAINT uk_mall_orders_mall_order_no UNIQUE (mall, mall_order_no),
    CONSTRAINT fk_mall_orders_item_id  FOREIGN KEY (item_id)  REFERENCES public.items(id),
    CONSTRAINT fk_mall_orders_sales_id FOREIGN KEY (sales_id) REFERENCES public.sales(id),
    CONSTRAINT ck_mall_orders_status
        CHECK (status IN ('RECEIVED', 'CONFIRMED', 'CONVERTED', 'CANCELLED'))
);
CREATE INDEX idx_mall_orders_order_date ON public.mall_orders (order_date);
CREATE INDEX idx_mall_orders_status     ON public.mall_orders (status);
CREATE INDEX idx_mall_orders_item_id    ON public.mall_orders (item_id);
CREATE INDEX idx_mall_orders_sales_id   ON public.mall_orders (sales_id);
