-- V71: 인쇄용 결재라인(결재란) — 출력물 우측 상단의 담당/검토/승인 칸
--
-- 전자결재와 다르다. 전자결재는 시스템에서 실제로 결재를 받고, 이건 종이에 도장을 찍을
-- 빈 칸을 그려준다. 그래서 결재자 이름(signer_name)은 선택이다 — 비우면 빈 칸으로 인쇄된다.
--
-- 기본 결재란(is_default)은 하나만 유지한다. 목록 화면의 [인쇄]가 그것을 쓴다.

CREATE TABLE public.print_sign_lines (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name       character varying(100) NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    active     boolean NOT NULL DEFAULT true,
    remark     character varying(200),
    CONSTRAINT uk_print_sign_lines_name UNIQUE (name)
);
CREATE INDEX idx_print_sign_lines_is_default ON public.print_sign_lines (is_default);

CREATE TABLE public.print_sign_slots (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sign_line_id bigint NOT NULL,
    title        character varying(30) NOT NULL,
    -- 비워두면 빈 칸으로 인쇄된다 (도장을 찍을 자리)
    signer_name  character varying(50),
    slot_order   integer NOT NULL DEFAULT 1,
    CONSTRAINT fk_print_sign_slots_sign_line_id FOREIGN KEY (sign_line_id)
        REFERENCES public.print_sign_lines(id) ON DELETE CASCADE,
    CONSTRAINT uk_print_sign_slots_order UNIQUE (sign_line_id, slot_order)
);
CREATE INDEX idx_print_sign_slots_sign_line_id ON public.print_sign_slots (sign_line_id);

-- 기본 결재란 하나를 시드해 둔다 (담당 / 검토 / 승인, 이름은 비움)
INSERT INTO public.print_sign_lines (created_at, updated_at, name, is_default, active, remark)
VALUES (now(), now(), '기본 결재란', true, true, '출력물 우측 상단에 담당/검토/승인 칸을 찍는다');

INSERT INTO public.print_sign_slots (sign_line_id, title, signer_name, slot_order)
SELECT id, t.title, NULL, t.ord
FROM public.print_sign_lines,
     (VALUES ('담당', 1), ('검토', 2), ('승인', 3)) AS t(title, ord)
WHERE name = '기본 결재란';
