-- V76: 급여 수당/공제그룹 · 급여이체 (관리 6-1)
--
-- 수당·공제 항목을 마스터로 두고 그룹으로 묶는다. 급여계산 때 그룹을 고르면 그대로 명세 라인이 된다.
-- 핵심은 taxable 이다. 식대 같은 비과세 수당은 4대보험·소득세 계산 기준(과세소득)에서 빠진다.
--
-- 급여이체는 확정된 급여명세를 묶어 회사 계좌에서 실지급액을 내보내고 분개를 만든다:
--   차) 급여(801) 지급총액 / 대) 예수금(254) 공제합계 · 예금계정 실지급액

-- 기존 급여명세 라인은 전부 과세로 본다(그때까지 비과세 개념이 없었다).
ALTER TABLE public.payslip_lines ADD COLUMN taxable boolean NOT NULL DEFAULT true;

ALTER TABLE public.journal_entries DROP CONSTRAINT ck_journal_entries_source_type;
ALTER TABLE public.journal_entries ADD CONSTRAINT ck_journal_entries_source_type
    CHECK (source_type IN ('SALES', 'PURCHASE', 'EXPENSE', 'BANK', 'CARD', 'NOTE',
                           'DEPRECIATION', 'DISPOSAL', 'VOUCHER', 'NONCASH', 'CHECK',
                           'PAYROLL', 'MANUAL'));

CREATE TABLE public.pay_items (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     timestamp(6) without time zone,
    updated_at     timestamp(6) without time zone,
    code           character varying(30) NOT NULL,
    name           character varying(50) NOT NULL,
    kind           character varying(20) NOT NULL,
    -- 비과세 수당이면 false. 공제 항목에서는 쓰지 않는다.
    taxable        boolean NOT NULL DEFAULT true,
    default_amount numeric(18,2) NOT NULL DEFAULT 0,
    active         boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_pay_items_code UNIQUE (code),
    CONSTRAINT ck_pay_items_kind CHECK (kind IN ('ALLOWANCE', 'DEDUCTION'))
);

CREATE TABLE public.pay_groups (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name       character varying(50) NOT NULL,
    remark     character varying(200),
    active     boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_pay_groups_name UNIQUE (name)
);

CREATE TABLE public.pay_group_lines (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    bigint NOT NULL,
    pay_item_id bigint NOT NULL,
    -- 비우면 항목의 기본금액을 쓴다
    amount      numeric(18,2),
    CONSTRAINT uk_pay_group_lines_group_item UNIQUE (group_id, pay_item_id),
    CONSTRAINT fk_pay_group_lines_group_id FOREIGN KEY (group_id)
        REFERENCES public.pay_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_pay_group_lines_pay_item_id FOREIGN KEY (pay_item_id) REFERENCES public.pay_items(id)
);
CREATE INDEX idx_pay_group_lines_group_id    ON public.pay_group_lines (group_id);
CREATE INDEX idx_pay_group_lines_pay_item_id ON public.pay_group_lines (pay_item_id);

CREATE TABLE public.payroll_transfers (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6) without time zone,
    updated_at       timestamp(6) without time zone,
    transfer_no      character varying(30) NOT NULL,
    pay_month        character varying(7) NOT NULL,
    transfer_date    date NOT NULL,
    bank_account_id  bigint NOT NULL,
    total_pay        numeric(18,2) NOT NULL DEFAULT 0,
    total_deduction  numeric(18,2) NOT NULL DEFAULT 0,
    net_pay          numeric(18,2) NOT NULL DEFAULT 0,
    journal_entry_id bigint,
    created_by       character varying(50),
    CONSTRAINT uk_payroll_transfers_transfer_no UNIQUE (transfer_no),
    CONSTRAINT fk_payroll_transfers_bank_account_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
    CONSTRAINT fk_payroll_transfers_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id)
);
CREATE INDEX idx_payroll_transfers_bank_account_id  ON public.payroll_transfers (bank_account_id);
CREATE INDEX idx_payroll_transfers_journal_entry_id ON public.payroll_transfers (journal_entry_id);
CREATE INDEX idx_payroll_transfers_pay_month        ON public.payroll_transfers (pay_month);

CREATE TABLE public.payroll_transfer_lines (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id bigint NOT NULL,
    payslip_id  bigint NOT NULL,
    net_pay     numeric(18,2) NOT NULL,
    -- 같은 급여명세를 두 번 이체할 수 없다
    CONSTRAINT uk_payroll_transfer_lines_payslip UNIQUE (payslip_id),
    CONSTRAINT fk_payroll_transfer_lines_transfer_id FOREIGN KEY (transfer_id)
        REFERENCES public.payroll_transfers(id) ON DELETE CASCADE,
    CONSTRAINT fk_payroll_transfer_lines_payslip_id FOREIGN KEY (payslip_id) REFERENCES public.payslips(id)
);
CREATE INDEX idx_payroll_transfer_lines_transfer_id ON public.payroll_transfer_lines (transfer_id);

-- 급여이체 분개가 쓰는 계정
INSERT INTO public.accounts (code, name, division, detail_category, active) VALUES
    ('801', '급여', 'EXPENSE', '판매관리비', true),
    ('254', '예수금', 'LIABILITY', '유동부채', true);

-- 자주 쓰는 수당·공제 항목
INSERT INTO public.pay_items (code, name, kind, taxable, default_amount, active) VALUES
    ('MEAL',      '식대',       'ALLOWANCE', false, 200000, true),   -- 비과세
    ('VEHICLE',   '차량유지비', 'ALLOWANCE', false, 200000, true),   -- 비과세
    ('POSITION',  '직책수당',   'ALLOWANCE', true,  300000, true),
    ('OVERTIME',  '연장근로수당','ALLOWANCE', true, 0,      true),
    ('UNION_FEE', '노조회비',   'DEDUCTION', true,  0,      true);
