-- V80: 그룹웨어 공유정보 잔여 — 익명게시판 · 외근조회
--
-- 익명게시판은 게시판을 하나 더 만들지 않는다. 글에 anonymous 플래그를 달고, 익명 글은
-- API 응답에서 작성자를 '익명'으로 가린다. 작성자는 DB 에 그대로 남긴다 —
-- 지우려면 본인인지 확인해야 하고, 문제가 생기면 추적할 수 있어야 한다.
-- (완전 익명이 필요하면 그때는 작성자를 저장하지 않는 별도 테이블을 만든다. 지금은 아니다.)
--
-- 외근계는 근태와 나란히 본다. 출퇴근 기록이 없는 날에 외근이 승인돼 있으면 무단결근이 아니다.

ALTER TABLE public.board_posts ADD COLUMN anonymous boolean;
UPDATE public.board_posts SET anonymous = false WHERE anonymous IS NULL;
ALTER TABLE public.board_posts ALTER COLUMN anonymous SET NOT NULL;
ALTER TABLE public.board_posts ALTER COLUMN anonymous SET DEFAULT false;

CREATE TABLE public.field_works (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6) without time zone,
    updated_at    timestamp(6) without time zone,
    user_id       bigint NOT NULL,
    work_date     date NOT NULL,
    start_time    time without time zone,
    end_time      time without time zone,
    destination   character varying(200) NOT NULL,
    purpose       character varying(300) NOT NULL,
    -- REQUESTED(신청) → APPROVED(승인) / REJECTED(반려)
    status        character varying(20) NOT NULL DEFAULT 'REQUESTED',
    approver_id   bigint,
    reject_reason character varying(300),
    CONSTRAINT fk_field_works_user_id     FOREIGN KEY (user_id)     REFERENCES public.users(id),
    CONSTRAINT fk_field_works_approver_id FOREIGN KEY (approver_id) REFERENCES public.users(id),
    CONSTRAINT ck_field_works_status CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED'))
);
CREATE INDEX idx_field_works_user_id     ON public.field_works (user_id);
CREATE INDEX idx_field_works_approver_id ON public.field_works (approver_id);
CREATE INDEX idx_field_works_work_date   ON public.field_works (work_date);
CREATE INDEX idx_field_works_status      ON public.field_works (status);
