-- V85: 공통코드 마스터 (code_groups, common_codes)
--
-- 카드사·결제대행사·추가항목유형·결제조건 같은 "값의 목록"이 지금까지 화면마다 하드코딩된
-- 문자열 배열이었다(예: ExpensePage 의 PAYMENTS = ['법인카드','계좌이체','현금']). 그래서
-- 항목 하나를 추가하려면 코드를 고쳐 배포해야 했고, 같은 뜻의 값이 화면마다 조금씩 달랐다.
--
-- 코드 그룹(무엇의 목록인가) + 코드(그 목록의 값)로 나눈다. 그룹은 시스템이 쓰는 키
-- (group_code)를 갖고, 코드는 그룹 안에서 유일하다.
--
-- 주의: enum 으로 로직을 태우는 값(전표 상태, 소득구분 등)은 여기로 옮기지 않는다.
-- 그것들은 코드가 분기 조건으로 쓰므로 테이블로 빼면 로직이 데이터에 숨는다.
-- 여기 담는 것은 "그냥 목록"뿐이다.

CREATE TABLE public.code_groups (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6) without time zone,
    updated_at  timestamp(6) without time zone,
    group_code  varchar(50)  NOT NULL,
    name        varchar(100) NOT NULL,
    description varchar(300),
    -- 시스템이 참조하는 그룹은 삭제할 수 없다 (화면이 이 그룹을 이름으로 찾는다)
    system      boolean      NOT NULL DEFAULT false,
    active      boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_code_groups_group_code UNIQUE (group_code)
);

CREATE TABLE public.common_codes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    group_id   bigint       NOT NULL,
    code       varchar(50)  NOT NULL,
    name       varchar(100) NOT NULL,
    -- 그룹마다 의미가 다른 부가값 (예: 카드사 정산일, PG 수수료율)
    value1     varchar(100),
    value2     varchar(100),
    sort_order integer      NOT NULL DEFAULT 0,
    active     boolean      NOT NULL DEFAULT true,
    remark     varchar(300),
    CONSTRAINT uk_common_codes_group_code UNIQUE (group_id, code),
    CONSTRAINT fk_common_codes_group_id FOREIGN KEY (group_id)
        REFERENCES public.code_groups(id) ON DELETE CASCADE
);
CREATE INDEX idx_common_codes_group_id ON public.common_codes (group_id);

-- 기초등록에서 비어 있던 목록들을 시스템 그룹으로 만든다.
INSERT INTO public.code_groups (group_code, name, description, system, active) VALUES
    ('CARD_COMPANY',  '카드사',       '법인카드 발급 카드사', true, true),
    ('PG_COMPANY',    '결제대행사',   '쇼핑몰 결제대행(PG) 업체', true, true),
    ('EXTRA_FIELD',   '추가항목유형', '전표에 붙이는 사용자 정의 항목의 유형', true, true),
    ('PAYMENT_METHOD','결제수단',     '비용·정산의 결제수단', true, true);

INSERT INTO public.common_codes (group_id, code, name, sort_order, active)
SELECT g.id, c.code, c.name, c.sort_order, true
FROM public.code_groups g
JOIN (VALUES
    ('CARD_COMPANY',   'BC',        'BC카드',       1),
    ('CARD_COMPANY',   'SHINHAN',   '신한카드',     2),
    ('CARD_COMPANY',   'KB',        'KB국민카드',   3),
    ('CARD_COMPANY',   'SAMSUNG',   '삼성카드',     4),
    ('CARD_COMPANY',   'HYUNDAI',   '현대카드',     5),
    ('PG_COMPANY',     'TOSS',      '토스페이먼츠', 1),
    ('PG_COMPANY',     'NICE',      '나이스페이',   2),
    ('PG_COMPANY',     'KG',        'KG이니시스',   3),
    ('EXTRA_FIELD',    'TEXT',      '문자',         1),
    ('EXTRA_FIELD',    'NUMBER',    '숫자',         2),
    ('EXTRA_FIELD',    'DATE',      '날짜',         3),
    ('EXTRA_FIELD',    'SELECT',    '선택목록',     4),
    ('PAYMENT_METHOD', 'CARD',      '법인카드',     1),
    ('PAYMENT_METHOD', 'TRANSFER',  '계좌이체',     2),
    ('PAYMENT_METHOD', 'CASH',      '현금',         3)
) AS c(group_code, code, name, sort_order) ON c.group_code = g.group_code;
