-- V86: 현금거래 세분류 — 계좌간이동 · 법인카드 대금결제 (회계 I 4-6)
--
-- 계좌간이동: 회사 계좌 A → B. 회사 밖으로 나가는 돈이 아니라 손익에 영향이 없다.
--   차) 입금계좌 예금계정 / 대) 출금계좌 예금계정
--
-- 카드대금 결제: 카드사용 시점에 남긴 미지급금을 결제일에 갚는다.
--   카드사용  차)비용·부가세대급금 / 대)미지급금   (이미 있음)
--   대금결제  차)미지급금          / 대)예금계정   (여기)
-- 결제한 사용건은 다시 결제되지 않는다(card_payment_lines.card_usage_id 유니크).

ALTER TABLE public.journal_entries DROP CONSTRAINT ck_journal_entries_source_type;
ALTER TABLE public.journal_entries ADD CONSTRAINT ck_journal_entries_source_type
    CHECK (source_type IN ('SALES', 'PURCHASE', 'EXPENSE', 'BANK', 'CARD', 'NOTE',
                           'DEPRECIATION', 'DISPOSAL', 'VOUCHER', 'NONCASH', 'CHECK',
                           'PAYROLL', 'ACCOUNT_TRANSFER', 'CARD_PAYMENT', 'MANUAL'));

CREATE TABLE public.account_transfers (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6) without time zone,
    updated_at       timestamp(6) without time zone,
    transfer_no      character varying(30) NOT NULL,
    transfer_date    date NOT NULL,
    from_account_id  bigint NOT NULL,
    to_account_id    bigint NOT NULL,
    amount           numeric(18,2) NOT NULL,
    journal_entry_id bigint,
    description      character varying(200),
    created_by       character varying(50),
    CONSTRAINT uk_account_transfers_transfer_no UNIQUE (transfer_no),
    CONSTRAINT fk_account_transfers_from_account_id FOREIGN KEY (from_account_id) REFERENCES public.bank_accounts(id),
    CONSTRAINT fk_account_transfers_to_account_id FOREIGN KEY (to_account_id) REFERENCES public.bank_accounts(id),
    CONSTRAINT fk_account_transfers_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
    -- 같은 계좌 안에서의 이동은 아무 일도 하지 않는다
    CONSTRAINT ck_account_transfers_accounts CHECK (from_account_id <> to_account_id)
);
CREATE INDEX idx_account_transfers_from_account_id  ON public.account_transfers (from_account_id);
CREATE INDEX idx_account_transfers_to_account_id    ON public.account_transfers (to_account_id);
CREATE INDEX idx_account_transfers_journal_entry_id ON public.account_transfers (journal_entry_id);
CREATE INDEX idx_account_transfers_transfer_date    ON public.account_transfers (transfer_date);

CREATE TABLE public.card_payments (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamp(6) without time zone,
    updated_at       timestamp(6) without time zone,
    payment_no       character varying(30) NOT NULL,
    payment_date     date NOT NULL,
    card_id          bigint NOT NULL,
    bank_account_id  bigint NOT NULL,
    amount           numeric(18,2) NOT NULL DEFAULT 0,
    journal_entry_id bigint,
    created_by       character varying(50),
    CONSTRAINT uk_card_payments_payment_no UNIQUE (payment_no),
    CONSTRAINT fk_card_payments_card_id FOREIGN KEY (card_id) REFERENCES public.credit_cards(id),
    CONSTRAINT fk_card_payments_bank_account_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
    CONSTRAINT fk_card_payments_journal_entry_id FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id)
);
CREATE INDEX idx_card_payments_card_id          ON public.card_payments (card_id);
CREATE INDEX idx_card_payments_bank_account_id  ON public.card_payments (bank_account_id);
CREATE INDEX idx_card_payments_journal_entry_id ON public.card_payments (journal_entry_id);
CREATE INDEX idx_card_payments_payment_date     ON public.card_payments (payment_date);

CREATE TABLE public.card_payment_lines (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id    bigint NOT NULL,
    card_usage_id bigint NOT NULL,
    amount        numeric(18,2) NOT NULL,
    -- 같은 카드사용을 두 번 결제할 수 없다
    CONSTRAINT uk_card_payment_lines_usage UNIQUE (card_usage_id),
    CONSTRAINT fk_card_payment_lines_payment_id FOREIGN KEY (payment_id)
        REFERENCES public.card_payments(id) ON DELETE CASCADE,
    CONSTRAINT fk_card_payment_lines_card_usage_id FOREIGN KEY (card_usage_id) REFERENCES public.card_usages(id)
);
CREATE INDEX idx_card_payment_lines_payment_id ON public.card_payment_lines (payment_id);
