-- V91: E Note — 개인 메모 (우측 앱바 위젯, N-4)
--
-- 본인 것만 보이고 본인만 고칠 수 있다(조회 자체를 소유자로 걸어 남의 메모는 애초에 나오지 않는다).
-- 통합검색·알림은 기존 데이터를 읽기만 하므로 테이블이 필요 없다.

CREATE TABLE public.user_notes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    owner_id   bigint NOT NULL,
    content    text NOT NULL,
    pinned     boolean NOT NULL DEFAULT false,
    CONSTRAINT fk_user_notes_owner_id FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE INDEX idx_user_notes_owner_id ON public.user_notes (owner_id);
