-- 회사(테넌트) 레지스트리. public 스키마에만 둔다(로그인 전에, 테넌트를 모르는 상태에서 조회).
-- 각 회사는 자기 데이터 스키마(schema_name)를 하나씩 갖는다. 본사는 기존 데이터가 있는 public.
--
-- 새 회사는 co_000N 스키마를 새로 만들고 db/tenant baseline 으로 테이블을 구성한다(앱에서 처리).

CREATE TABLE companies (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        varchar(20)  NOT NULL UNIQUE,
    name        varchar(100) NOT NULL,
    schema_name varchar(63)  NOT NULL UNIQUE,
    active      boolean      NOT NULL DEFAULT true,
    created_at  timestamp(6)
);

-- 본사: 기존 데이터(public)를 1번 회사로 등록. 회사코드 0001 로 로그인.
INSERT INTO companies (code, name, schema_name, active, created_at)
VALUES ('0001', '본사', 'public', true, now());
